import Stokes.SingularCube.CubeAndFacesCompactAuto
import Stokes.SingularCube.SmoothExtensionMathlibAudit

/-!
# Core smooth singular extension input from compact carriers

This module packages the common extension step for smooth singular cubes:
once a compact carrier contains the full cube image and all boundary-face
images, a single inclusion of that carrier in an open extension set supplies
the containment data required by the core/open extension inputs.
-/

noncomputable section

open Set
open scoped Manifold Topology

namespace Stokes
namespace SingularCubeSmoothExtensionAudit

section CompactCarrierContainment

variable {n m : Nat}
variable {cube : SmoothSingularCube (n + 1) m}

/-- A compact carrier inclusion gives the full cube-image inclusion. -/
theorem cube_image_subset_of_compactCarrier_subset
    (D : CubeAndFacesCompactData cube) {U : Set (Fin m → Real)}
    (hD : D.carrier ⊆ U) :
    cube.toFun '' singularParameterCube (n + 1) ⊆ U :=
  subset_trans D.cube_image_subset_carrier hD

/-- A compact carrier inclusion gives every high-face image inclusion. -/
theorem highFace_image_subset_of_compactCarrier_subset
    (D : CubeAndFacesCompactData cube) {U : Set (Fin m → Real)}
    (hD : D.carrier ⊆ U) (i : Fin (n + 1)) :
    (singularFace cube i 1).toFun '' singularParameterCube n ⊆ U :=
  subset_trans (D.highFace_image_subset_carrier i) hD

/-- A compact carrier inclusion gives every low-face image inclusion. -/
theorem lowFace_image_subset_of_compactCarrier_subset
    (D : CubeAndFacesCompactData cube) {U : Set (Fin m → Real)}
    (hD : D.carrier ⊆ U) (i : Fin (n + 1)) :
    (singularFace cube i 0).toFun '' singularParameterCube n ⊆ U :=
  subset_trans (D.lowFace_image_subset_carrier i) hD

/-- A compact carrier inclusion gives the combined cube-and-faces inclusion. -/
theorem cubeAndFacesImage_subset_of_compactCarrier_subset
    (D : CubeAndFacesCompactData cube) {U : Set (Fin m → Real)}
    (hD : D.carrier ⊆ U) :
    cubeAndFacesImage cube ⊆ U :=
  (D.carrier_subset_iff).1 hD

/-- The full cube map lands in any set containing a compact carrier. -/
theorem cube_mapsTo_of_compactCarrier_subset
    (D : CubeAndFacesCompactData cube) {U : Set (Fin m → Real)}
    (hD : D.carrier ⊆ U) :
    MapsTo cube.toFun (singularParameterCube (n + 1)) U := by
  intro x hx
  exact hD (D.cube_image_subset_carrier ⟨x, hx, rfl⟩)

/-- A high boundary face lands in any set containing a compact carrier. -/
theorem highFace_mapsTo_of_compactCarrier_subset
    (D : CubeAndFacesCompactData cube) {U : Set (Fin m → Real)}
    (hD : D.carrier ⊆ U) (i : Fin (n + 1)) :
    MapsTo (singularFace cube i 1).toFun (singularParameterCube n) U := by
  intro x hx
  exact hD (D.highFace_image_subset_carrier i ⟨x, hx, rfl⟩)

/-- A low boundary face lands in any set containing a compact carrier. -/
theorem lowFace_mapsTo_of_compactCarrier_subset
    (D : CubeAndFacesCompactData cube) {U : Set (Fin m → Real)}
    (hD : D.carrier ⊆ U) (i : Fin (n + 1)) :
    MapsTo (singularFace cube i 0).toFun (singularParameterCube n) U := by
  intro x hx
  exact hD (D.lowFace_image_subset_carrier i ⟨x, hx, rfl⟩)

/-- Pointwise full-cube containment generated by compact carrier containment. -/
theorem cube_mem_of_compactCarrier_subset
    (D : CubeAndFacesCompactData cube) {U : Set (Fin m → Real)}
    (hD : D.carrier ⊆ U) {x : Fin (n + 1) → Real}
    (hx : x ∈ singularParameterCube (n + 1)) :
    cube.toFun x ∈ U :=
  cube_mapsTo_of_compactCarrier_subset D hD hx

/-- Pointwise high-face containment generated by compact carrier containment. -/
theorem highFace_mem_of_compactCarrier_subset
    (D : CubeAndFacesCompactData cube) {U : Set (Fin m → Real)}
    (hD : D.carrier ⊆ U) (i : Fin (n + 1))
    {x : Fin n → Real} (hx : x ∈ singularParameterCube n) :
    (singularFace cube i 1).toFun x ∈ U :=
  highFace_mapsTo_of_compactCarrier_subset D hD i hx

/-- Pointwise low-face containment generated by compact carrier containment. -/
theorem lowFace_mem_of_compactCarrier_subset
    (D : CubeAndFacesCompactData cube) {U : Set (Fin m → Real)}
    (hD : D.carrier ⊆ U) (i : Fin (n + 1))
    {x : Fin n → Real} (hx : x ∈ singularParameterCube n) :
    (singularFace cube i 0).toFun x ∈ U :=
  lowFace_mapsTo_of_compactCarrier_subset D hD i hx

/-- A small wrapper for the single carrier-containment fact used by extension inputs. -/
structure CubeAndFacesExtensionContainment
    (cube : SmoothSingularCube (n + 1) m) (extensionSet : Set (Fin m → Real)) where
  compactCarrier : CubeAndFacesCompactData cube
  carrier_subset_extensionSet : compactCarrier.carrier ⊆ extensionSet

namespace CubeAndFacesExtensionContainment

variable {extensionSet : Set (Fin m → Real)}

/-- Build the containment wrapper from an explicit compact carrier inclusion. -/
def ofCompactCarrierSubset
    (D : CubeAndFacesCompactData cube)
    (hD : D.carrier ⊆ extensionSet) :
    CubeAndFacesExtensionContainment cube extensionSet where
  compactCarrier := D
  carrier_subset_extensionSet := hD

/-- The wrapper exposes compactness of the chosen carrier. -/
theorem isCompact_carrier
    (C : CubeAndFacesExtensionContainment cube extensionSet) :
    IsCompact C.compactCarrier.carrier :=
  C.compactCarrier.isCompact_carrier

/-- The wrapper exposes the combined image inclusion. -/
theorem image_subset_extensionSet
    (C : CubeAndFacesExtensionContainment cube extensionSet) :
    cubeAndFacesImage cube ⊆ extensionSet :=
  cubeAndFacesImage_subset_of_compactCarrier_subset
    C.compactCarrier C.carrier_subset_extensionSet

/-- The wrapper exposes the full cube-image inclusion. -/
theorem cube_image_subset_extensionSet
    (C : CubeAndFacesExtensionContainment cube extensionSet) :
    cube.toFun '' singularParameterCube (n + 1) ⊆ extensionSet :=
  cube_image_subset_of_compactCarrier_subset
    C.compactCarrier C.carrier_subset_extensionSet

/-- The wrapper exposes high-face image inclusions. -/
theorem highFace_image_subset_extensionSet
    (C : CubeAndFacesExtensionContainment cube extensionSet)
    (i : Fin (n + 1)) :
    (singularFace cube i 1).toFun '' singularParameterCube n ⊆ extensionSet :=
  highFace_image_subset_of_compactCarrier_subset
    C.compactCarrier C.carrier_subset_extensionSet i

/-- The wrapper exposes low-face image inclusions. -/
theorem lowFace_image_subset_extensionSet
    (C : CubeAndFacesExtensionContainment cube extensionSet)
    (i : Fin (n + 1)) :
    (singularFace cube i 0).toFun '' singularParameterCube n ⊆ extensionSet :=
  lowFace_image_subset_of_compactCarrier_subset
    C.compactCarrier C.carrier_subset_extensionSet i

/-- The wrapper exposes the full cube `MapsTo` statement. -/
theorem cube_mapsTo_extensionSet
    (C : CubeAndFacesExtensionContainment cube extensionSet) :
    MapsTo cube.toFun (singularParameterCube (n + 1)) extensionSet :=
  cube_mapsTo_of_compactCarrier_subset
    C.compactCarrier C.carrier_subset_extensionSet

/-- The wrapper exposes high-face `MapsTo` statements. -/
theorem highFace_mapsTo_extensionSet
    (C : CubeAndFacesExtensionContainment cube extensionSet)
    (i : Fin (n + 1)) :
    MapsTo (singularFace cube i 1).toFun (singularParameterCube n) extensionSet :=
  highFace_mapsTo_of_compactCarrier_subset
    C.compactCarrier C.carrier_subset_extensionSet i

/-- The wrapper exposes low-face `MapsTo` statements. -/
theorem lowFace_mapsTo_extensionSet
    (C : CubeAndFacesExtensionContainment cube extensionSet)
    (i : Fin (n + 1)) :
    MapsTo (singularFace cube i 0).toFun (singularParameterCube n) extensionSet :=
  lowFace_mapsTo_of_compactCarrier_subset
    C.compactCarrier C.carrier_subset_extensionSet i

/-- The full cube pointwise membership expected by open extension inputs. -/
theorem cube_mem_extensionSet
    (C : CubeAndFacesExtensionContainment cube extensionSet)
    (x : Fin (n + 1) → Real) (hx : x ∈ singularParameterCube (n + 1)) :
    cube.toFun x ∈ extensionSet :=
  C.cube_mapsTo_extensionSet hx

/-- The high-face pointwise membership expected by open extension inputs. -/
theorem highFace_mem_extensionSet
    (C : CubeAndFacesExtensionContainment cube extensionSet)
    (i : Fin (n + 1)) (x : Fin n → Real)
    (hx : x ∈ singularParameterCube n) :
    (singularFace cube i 1).toFun x ∈ extensionSet :=
  C.highFace_mapsTo_extensionSet i hx

/-- The low-face pointwise membership expected by open extension inputs. -/
theorem lowFace_mem_extensionSet
    (C : CubeAndFacesExtensionContainment cube extensionSet)
    (i : Fin (n + 1)) (x : Fin n → Real)
    (hx : x ∈ singularParameterCube n) :
    (singularFace cube i 0).toFun x ∈ extensionSet :=
  C.lowFace_mapsTo_extensionSet i hx

@[simp]
theorem ofCompactCarrierSubset_compactCarrier
    (D : CubeAndFacesCompactData cube)
    (hD : D.carrier ⊆ extensionSet) :
    (ofCompactCarrierSubset (cube := cube) D hD).compactCarrier = D :=
  rfl

@[simp]
theorem ofCompactCarrierSubset_carrier_subset_extensionSet
    (D : CubeAndFacesCompactData cube)
    (hD : D.carrier ⊆ extensionSet) :
    (ofCompactCarrierSubset (cube := cube) D hD).carrier_subset_extensionSet = hD :=
  rfl

end CubeAndFacesExtensionContainment

end CompactCarrierContainment

section CompactExtensionInput

universe u w

variable {H : Type u} [TopologicalSpace H]
variable {M : Type w} [TopologicalSpace M] [ChartedSpace H M]

/--
Chartwise extension data where the extension neighborhood is controlled by a
compact carrier rather than by separately listing the full cube and each face.
-/
structure ChartwiseSingularCubeCompactExtensionInput {n m : Nat}
    {I : ModelWithCorners Real (Fin m → Real) H}
    (omega : ManifoldForm I M n)
    (chart : M) (cube : SmoothSingularCube (n + 1) m) where
  smoothSet : Set (Fin m → Real)
  isOpen_smoothSet : IsOpen smoothSet
  cube_mem_smoothSet : MapsTo cube.toFun (singularParameterCube (n + 1)) smoothSet
  smoothSet_subset_chartTarget : smoothSet ⊆ (extChartAt I chart).target
  chartwiseSmooth : ManifoldForm.ChartwiseSmooth I omega
  omegaExt : EuclideanForm m n
  contDiff_omegaExt : ContDiff Real ⊤ omegaExt
  extensionSet : Set (Fin m → Real)
  isOpen_extensionSet : IsOpen extensionSet
  compactCarrier : CubeAndFacesCompactData cube
  carrier_subset_extensionSet : compactCarrier.carrier ⊆ extensionSet
  agreesOn_extensionSet : EqOn omegaExt (chartLocalForm I chart omega) extensionSet

namespace ChartwiseSingularCubeCompactExtensionInput

variable {n m : Nat}
variable {I : ModelWithCorners Real (Fin m → Real) H}
variable {omega : ManifoldForm I M n}
variable {chart : M} {cube : SmoothSingularCube (n + 1) m}

/-- The carrier-containment wrapper extracted from compact extension input. -/
def containment
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    CubeAndFacesExtensionContainment cube E.extensionSet where
  compactCarrier := E.compactCarrier
  carrier_subset_extensionSet := E.carrier_subset_extensionSet

/-- The compact carrier used by the input is compact. -/
theorem isCompact_carrier
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    IsCompact E.compactCarrier.carrier :=
  E.compactCarrier.isCompact_carrier

/-- The combined cube-and-faces image lies in the extension set. -/
theorem image_subset_extensionSet
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    cubeAndFacesImage cube ⊆ E.extensionSet :=
  E.containment.image_subset_extensionSet

/-- The full cube image lies in the extension set. -/
theorem cube_image_subset_extensionSet
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    cube.toFun '' singularParameterCube (n + 1) ⊆ E.extensionSet :=
  E.containment.cube_image_subset_extensionSet

/-- Every high-face image lies in the extension set. -/
theorem highFace_image_subset_extensionSet
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube)
    (i : Fin (n + 1)) :
    (singularFace cube i 1).toFun '' singularParameterCube n ⊆ E.extensionSet :=
  E.containment.highFace_image_subset_extensionSet i

/-- Every low-face image lies in the extension set. -/
theorem lowFace_image_subset_extensionSet
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube)
    (i : Fin (n + 1)) :
    (singularFace cube i 0).toFun '' singularParameterCube n ⊆ E.extensionSet :=
  E.containment.lowFace_image_subset_extensionSet i

/-- The full cube map lands in the extension set. -/
theorem cube_mapsTo_extensionSet
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    MapsTo cube.toFun (singularParameterCube (n + 1)) E.extensionSet :=
  E.containment.cube_mapsTo_extensionSet

/-- Every high face lands in the extension set. -/
theorem highFace_mapsTo_extensionSet
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube)
    (i : Fin (n + 1)) :
    MapsTo (singularFace cube i 1).toFun (singularParameterCube n) E.extensionSet :=
  E.containment.highFace_mapsTo_extensionSet i

/-- Every low face lands in the extension set. -/
theorem lowFace_mapsTo_extensionSet
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube)
    (i : Fin (n + 1)) :
    MapsTo (singularFace cube i 0).toFun (singularParameterCube n) E.extensionSet :=
  E.containment.lowFace_mapsTo_extensionSet i

/-- Pointwise full-cube membership in the extension set. -/
theorem cube_mem_extensionSet
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube)
    (x : Fin (n + 1) → Real) (hx : x ∈ singularParameterCube (n + 1)) :
    cube.toFun x ∈ E.extensionSet :=
  E.containment.cube_mem_extensionSet x hx

/-- Pointwise high-face membership in the extension set. -/
theorem highFace_mem_extensionSet
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube)
    (i : Fin (n + 1)) (x : Fin n → Real)
    (hx : x ∈ singularParameterCube n) :
    (singularFace cube i 1).toFun x ∈ E.extensionSet :=
  E.containment.highFace_mem_extensionSet i x hx

/-- Pointwise low-face membership in the extension set. -/
theorem lowFace_mem_extensionSet
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube)
    (i : Fin (n + 1)) (x : Fin n → Real)
    (hx : x ∈ singularParameterCube n) :
    (singularFace cube i 0).toFun x ∈ E.extensionSet :=
  E.containment.lowFace_mem_extensionSet i x hx

/-- Convert compact-carrier extension input to the core extension input. -/
def toCoreExtensionInput
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    ChartwiseSingularCubeCoreExtensionInput omega chart cube where
  smoothSet := E.smoothSet
  isOpen_smoothSet := E.isOpen_smoothSet
  cube_mem_smoothSet := E.cube_mem_smoothSet
  smoothSet_subset_chartTarget := E.smoothSet_subset_chartTarget
  chartwiseSmooth := E.chartwiseSmooth
  omegaExt := E.omegaExt
  contDiff_omegaExt := E.contDiff_omegaExt
  extensionSet := E.extensionSet
  isOpen_extensionSet := E.isOpen_extensionSet
  image_subset_extensionSet := E.image_subset_extensionSet
  agreesOn_extensionSet := E.agreesOn_extensionSet

/-- Convert compact-carrier extension input to the open extension input. -/
def toOpenExtensionInput
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    ChartwiseSingularCubeOpenExtensionInput omega chart cube :=
  E.toCoreExtensionInput.toOpenExtensionInput

/-- Build compact-carrier input from core input using the canonical carrier. -/
def ofCoreExtensionInput
    (E : ChartwiseSingularCubeCoreExtensionInput omega chart cube) :
    ChartwiseSingularCubeCompactExtensionInput omega chart cube where
  smoothSet := E.smoothSet
  isOpen_smoothSet := E.isOpen_smoothSet
  cube_mem_smoothSet := E.cube_mem_smoothSet
  smoothSet_subset_chartTarget := E.smoothSet_subset_chartTarget
  chartwiseSmooth := E.chartwiseSmooth
  omegaExt := E.omegaExt
  contDiff_omegaExt := E.contDiff_omegaExt
  extensionSet := E.extensionSet
  isOpen_extensionSet := E.isOpen_extensionSet
  compactCarrier := cubeAndFacesCompactData cube
  carrier_subset_extensionSet := by
    simpa using E.image_subset_extensionSet
  agreesOn_extensionSet := E.agreesOn_extensionSet

/-- Build compact-carrier input directly from open extension input. -/
def ofOpenExtensionInput
    (E : ChartwiseSingularCubeOpenExtensionInput omega chart cube) :
    ChartwiseSingularCubeCompactExtensionInput omega chart cube :=
  ofCoreExtensionInput
    { smoothSet := E.smoothSet
      isOpen_smoothSet := E.isOpen_smoothSet
      cube_mem_smoothSet := E.cube_mem_smoothSet
      smoothSet_subset_chartTarget := E.smoothSet_subset_chartTarget
      chartwiseSmooth := E.chartwiseSmooth
      omegaExt := E.omegaExt
      contDiff_omegaExt := E.contDiff_omegaExt
      extensionSet := E.extensionSet
      isOpen_extensionSet := E.isOpen_extensionSet
      image_subset_extensionSet := by
        intro y hy
        rcases hy with hcube | hfaces
        · rcases hcube with ⟨x, hx, rfl⟩
          exact E.cube_mem_extensionSet x hx
        · rcases hfaces with hhigh | hlow
          · rcases mem_iUnion.1 hhigh with ⟨i, hi⟩
            rcases hi with ⟨x, hx, rfl⟩
            exact E.highFace_mem_extensionSet i x hx
          · rcases mem_iUnion.1 hlow with ⟨i, hi⟩
            rcases hi with ⟨x, hx, rfl⟩
            exact E.lowFace_mem_extensionSet i x hx
      agreesOn_extensionSet := E.agreesOn_extensionSet }

/-- Boundary-integral smooth singular Stokes from compact-carrier input. -/
theorem boundary_stokes
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    SingularCubeStokes.bdryIntegral_singular cube (chartLocalForm I chart omega) =
      integrateForm cube (fun y => extDeriv (chartLocalForm I chart omega) y) :=
  E.toCoreExtensionInput.boundary_stokes

/-- Chain-level smooth singular Stokes from compact-carrier input. -/
theorem chain_stokes
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    integrateChain (singularBoundarySingle cube) (chartLocalForm I chart omega) =
      integrateForm cube (fun y => extDeriv (chartLocalForm I chart omega) y) :=
  E.toCoreExtensionInput.chain_stokes

/-- The compact input supplies the existing open-input existential shape. -/
theorem exists_openExtensionInput
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    ExistsChartwiseSingularCubeOpenExtensionInput omega chart cube :=
  ⟨E.toOpenExtensionInput, trivial⟩

@[simp]
theorem containment_compactCarrier
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    E.containment.compactCarrier = E.compactCarrier :=
  rfl

@[simp]
theorem containment_carrier_subset_extensionSet
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    E.containment.carrier_subset_extensionSet = E.carrier_subset_extensionSet :=
  rfl

@[simp]
theorem toCoreExtensionInput_smoothSet
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    E.toCoreExtensionInput.smoothSet = E.smoothSet :=
  rfl

@[simp]
theorem toCoreExtensionInput_cube_mem_smoothSet
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    E.toCoreExtensionInput.cube_mem_smoothSet = E.cube_mem_smoothSet :=
  rfl

@[simp]
theorem toCoreExtensionInput_smoothSet_subset_chartTarget
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    E.toCoreExtensionInput.smoothSet_subset_chartTarget =
      E.smoothSet_subset_chartTarget :=
  rfl

@[simp]
theorem toCoreExtensionInput_omegaExt
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    E.toCoreExtensionInput.omegaExt = E.omegaExt :=
  rfl

@[simp]
theorem toCoreExtensionInput_extensionSet
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    E.toCoreExtensionInput.extensionSet = E.extensionSet :=
  rfl

@[simp]
theorem toCoreExtensionInput_agreesOn_extensionSet
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    E.toCoreExtensionInput.agreesOn_extensionSet = E.agreesOn_extensionSet :=
  rfl

@[simp]
theorem toOpenExtensionInput_smoothSet
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    E.toOpenExtensionInput.smoothSet = E.smoothSet :=
  rfl

@[simp]
theorem toOpenExtensionInput_omegaExt
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    E.toOpenExtensionInput.omegaExt = E.omegaExt :=
  rfl

@[simp]
theorem toOpenExtensionInput_extensionSet
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    E.toOpenExtensionInput.extensionSet = E.extensionSet :=
  rfl

@[simp]
theorem toOpenExtensionInput_cube_mem_extensionSet
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube)
    (x : Fin (n + 1) → Real) (hx : x ∈ singularParameterCube (n + 1)) :
    E.toOpenExtensionInput.cube_mem_extensionSet x hx =
      E.cube_mem_extensionSet x hx :=
  rfl

@[simp]
theorem toOpenExtensionInput_highFace_mem_extensionSet
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube)
    (i : Fin (n + 1)) (x : Fin n → Real)
    (hx : x ∈ singularParameterCube n) :
    E.toOpenExtensionInput.highFace_mem_extensionSet i x hx =
      E.highFace_mem_extensionSet i x hx :=
  rfl

@[simp]
theorem toOpenExtensionInput_lowFace_mem_extensionSet
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube)
    (i : Fin (n + 1)) (x : Fin n → Real)
    (hx : x ∈ singularParameterCube n) :
    E.toOpenExtensionInput.lowFace_mem_extensionSet i x hx =
      E.lowFace_mem_extensionSet i x hx :=
  rfl

@[simp]
theorem ofCoreExtensionInput_smoothSet
    (E : ChartwiseSingularCubeCoreExtensionInput omega chart cube) :
    (ofCoreExtensionInput E).smoothSet = E.smoothSet :=
  rfl

@[simp]
theorem ofCoreExtensionInput_omegaExt
    (E : ChartwiseSingularCubeCoreExtensionInput omega chart cube) :
    (ofCoreExtensionInput E).omegaExt = E.omegaExt :=
  rfl

@[simp]
theorem ofCoreExtensionInput_extensionSet
    (E : ChartwiseSingularCubeCoreExtensionInput omega chart cube) :
    (ofCoreExtensionInput E).extensionSet = E.extensionSet :=
  rfl

@[simp]
theorem ofCoreExtensionInput_compactCarrier
    (E : ChartwiseSingularCubeCoreExtensionInput omega chart cube) :
    (ofCoreExtensionInput E).compactCarrier = cubeAndFacesCompactData cube :=
  rfl

@[simp]
theorem ofOpenExtensionInput_smoothSet
    (E : ChartwiseSingularCubeOpenExtensionInput omega chart cube) :
    (ofOpenExtensionInput E).smoothSet = E.smoothSet :=
  rfl

@[simp]
theorem ofOpenExtensionInput_omegaExt
    (E : ChartwiseSingularCubeOpenExtensionInput omega chart cube) :
    (ofOpenExtensionInput E).omegaExt = E.omegaExt :=
  rfl

@[simp]
theorem ofOpenExtensionInput_extensionSet
    (E : ChartwiseSingularCubeOpenExtensionInput omega chart cube) :
    (ofOpenExtensionInput E).extensionSet = E.extensionSet :=
  rfl

end ChartwiseSingularCubeCompactExtensionInput

/-- The proposition shape produced by a compact-carrier extension theorem. -/
def ExistsChartwiseSingularCubeCompactExtensionInput {n m : Nat}
    {I : ModelWithCorners Real (Fin m → Real) H}
    (omega : ManifoldForm I M n)
    (chart : M) (cube : SmoothSingularCube (n + 1) m) : Prop :=
  ∃ _E : ChartwiseSingularCubeCompactExtensionInput omega chart cube, True

/-- Boundary-integral facade using compact-carrier extension input. -/
theorem chartwise_singular_boundary_stokes_of_compactExtensionInput {n m : Nat}
    {I : ModelWithCorners Real (Fin m → Real) H}
    {omega : ManifoldForm I M n}
    (chart : M) (cube : SmoothSingularCube (n + 1) m)
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    SingularCubeStokes.bdryIntegral_singular cube (chartLocalForm I chart omega) =
      integrateForm cube (fun y => extDeriv (chartLocalForm I chart omega) y) :=
  E.boundary_stokes

/-- Chain-level facade using compact-carrier extension input. -/
theorem chartwise_singular_chain_stokes_of_compactExtensionInput {n m : Nat}
    {I : ModelWithCorners Real (Fin m → Real) H}
    {omega : ManifoldForm I M n}
    (chart : M) (cube : SmoothSingularCube (n + 1) m)
    (E : ChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    integrateChain (singularBoundarySingle cube) (chartLocalForm I chart omega) =
      integrateForm cube (fun y => extDeriv (chartLocalForm I chart omega) y) :=
  E.chain_stokes

/-- Boundary-integral facade from the compact-carrier existential output. -/
theorem chartwise_singular_boundary_stokes_of_exists_compactExtensionInput {n m : Nat}
    {I : ModelWithCorners Real (Fin m → Real) H}
    {omega : ManifoldForm I M n}
    (chart : M) (cube : SmoothSingularCube (n + 1) m)
    (hE : ExistsChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    SingularCubeStokes.bdryIntegral_singular cube (chartLocalForm I chart omega) =
      integrateForm cube (fun y => extDeriv (chartLocalForm I chart omega) y) := by
  rcases hE with ⟨E, _⟩
  exact chartwise_singular_boundary_stokes_of_compactExtensionInput chart cube E

/-- Chain-level facade from the compact-carrier existential output. -/
theorem chartwise_singular_chain_stokes_of_exists_compactExtensionInput {n m : Nat}
    {I : ModelWithCorners Real (Fin m → Real) H}
    {omega : ManifoldForm I M n}
    (chart : M) (cube : SmoothSingularCube (n + 1) m)
    (hE : ExistsChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    integrateChain (singularBoundarySingle cube) (chartLocalForm I chart omega) =
      integrateForm cube (fun y => extDeriv (chartLocalForm I chart omega) y) := by
  rcases hE with ⟨E, _⟩
  exact chartwise_singular_chain_stokes_of_compactExtensionInput chart cube E

/-- A compact-carrier extension input supplies the existing open-input shape. -/
theorem exists_openExtensionInput_of_exists_compactExtensionInput {n m : Nat}
    {I : ModelWithCorners Real (Fin m → Real) H}
    {omega : ManifoldForm I M n}
    {chart : M} {cube : SmoothSingularCube (n + 1) m}
    (hE : ExistsChartwiseSingularCubeCompactExtensionInput omega chart cube) :
    ExistsChartwiseSingularCubeOpenExtensionInput omega chart cube := by
  rcases hE with ⟨E, _⟩
  exact E.exists_openExtensionInput

end CompactExtensionInput

end SingularCubeSmoothExtensionAudit
end Stokes

end
