import Stokes.Global.BoundaryUnifiedToControlledM8InputAuto
import Stokes.Global.NaturalCompactSupportCombinedEndpoint
import Stokes.Global.CanonicalCompactSupportEndpointFacade

/-!
# Unified boundary data to the compact-support endpoint base

This module is endpoint-facing glue for the unified boundary route.

`BoundarySourceAlignmentUnifiedData` can already be viewed as a controlled
target-image M8 input.  The constructors below package the remaining endpoint
facts so callers no longer pass the `targetImageInput` identification as a
loose argument whenever they build the compact-support separated-boundary
endpoint.
-/

noncomputable section

set_option linter.style.longLine false
set_option linter.unusedSectionVars false

open Set MeasureTheory
open scoped BigOperators Manifold Topology

namespace Stokes

section BoundaryUnifiedToEndpointBaseAuto

universe u w b ei eb

variable {H : Type u} [TopologicalSpace H]
variable {M : Type w} [TopologicalSpace M] [ChartedSpace H M]
variable {BoundaryPiece : Type b}
variable {ExtInteriorPiece : Type ei} {ExtBoundaryPiece : Type eb}
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) -> Real) H}
variable {omega : ManifoldForm I M n}
variable {rho : SmoothPartitionOfUnity M I M univ}
variable {mu : Measure (Fin (n + 1) -> Real)}
variable [IsFiniteMeasureOnCompacts mu]
variable [IsManifold I 1 M]

namespace NaturalCompactSupportBulkProjectLocalAutoCollapsedInput

variable
    (B :
      NaturalCompactSupportBulkProjectLocalAutoCollapsedInput
        ExtInteriorPiece ExtBoundaryPiece
        I omega BoundaryPiece rho mu)

/-- Target-image alignment between a bulk endpoint input and a unified
boundary source package.

This is the only equality needed to reinterpret the unified controlled-target
route as a boundary route for `B`; downstream endpoint constructors consume the
package instead of asking callers to pass the equality separately. -/
structure BoundaryUnifiedEndpointTargetImageAlignment
    (U :
      BoundarySourceAlignmentUnifiedData
        (I := I) (omega := omega)
        (selectedPartition := B.selectedPartition)
        (orientedBoundaryAtlas := B.orientedBoundaryAtlas)
        (BoundaryPiece := BoundaryPiece)) where
  /-- `B` uses the same M8 target-image input generated by the unified route. -/
  targetImageInput_eq :
    B.targetImageInput =
      U.toM8BoundaryControlledTargetInput.toM8TargetImageInput

namespace BoundaryUnifiedEndpointTargetImageAlignment

variable
    {B :
      NaturalCompactSupportBulkProjectLocalAutoCollapsedInput
        ExtInteriorPiece ExtBoundaryPiece
        I omega BoundaryPiece rho mu}
    {U :
      BoundarySourceAlignmentUnifiedData
        (I := I) (omega := omega)
        (selectedPartition := B.selectedPartition)
        (orientedBoundaryAtlas := B.orientedBoundaryAtlas)
        (BoundaryPiece := BoundaryPiece)}
    (A : BoundaryUnifiedEndpointTargetImageAlignment B U)

@[simp]
theorem targetImageInput_eq_self
    (A : BoundaryUnifiedEndpointTargetImageAlignment B U) :
    B.targetImageInput =
      U.toM8BoundaryControlledTargetInput.toM8TargetImageInput :=
  by
    cases A with
    | mk h => exact h

end BoundaryUnifiedEndpointTargetImageAlignment

/-- Global-measure package for routing unified boundary data into the combined
compact-support endpoint base. -/
structure BoundaryUnifiedEndpointGlobalMeasureData where
  /-- Unified boundary source-alignment and controlled-target data. -/
  unified :
    BoundarySourceAlignmentUnifiedData
      (I := I) (omega := omega)
      (selectedPartition := B.selectedPartition)
      (orientedBoundaryAtlas := B.orientedBoundaryAtlas)
      (BoundaryPiece := BoundaryPiece)
  /-- Alignment between `B.targetImageInput` and the target-image input
  generated by `unified`. -/
  targetImageAlignment :
    BoundaryUnifiedEndpointTargetImageAlignment B unified
  /-- Global boundary measure reconstruction facts for the unified
  project-local boundary package. -/
  globalMeasure :
    ProjectLocalBoundaryGlobalMeasureFacts
      unified.toProjectLocalGlobalStokesData
  /-- Canonical lower-face continuity/integrability facts. -/
  faceContinuity :
    ProjectLocalBoundaryCanonicalFaceContinuityData
      unified.toProjectLocalGlobalStokesData

namespace BoundaryUnifiedEndpointGlobalMeasureData

variable
    {B :
      NaturalCompactSupportBulkProjectLocalAutoCollapsedInput
        ExtInteriorPiece ExtBoundaryPiece
        I omega BoundaryPiece rho mu}
    (D : BoundaryUnifiedEndpointGlobalMeasureData B)

/-- The project-local boundary data carried by the unified package. -/
abbrev boundaryProjectLocal :
    ProjectLocalGlobalStokesData I omega M BoundaryPiece :=
  D.unified.toProjectLocalGlobalStokesData

/-- The controlled M8 boundary input generated by the unified package. -/
abbrev controlledInput :
    M8BoundaryControlledTargetInput I omega B.selectedPartition
      B.orientedBoundaryAtlas BoundaryPiece :=
  D.unified.toM8BoundaryControlledTargetInput

/-- Canonical boundary route for `B`, obtained from unified data and the
packaged target-image alignment. -/
def boundaryRoute :
    BoundaryCanonicalRouteMeasureInput B.targetImageInput
      D.boundaryProjectLocal := by
  simpa [D.targetImageAlignment.targetImageInput_eq] using
    D.unified.toBoundaryCanonicalRouteMeasureInputOfControlledM8
      D.globalMeasure D.faceContinuity

/-- Compact-support separated-boundary base input generated from unified
boundary data. -/
def toBulkBoundarySeparatedBaseInput :
    NaturalCompactSupportBulkBoundarySeparatedBaseInput
      ExtInteriorPiece ExtBoundaryPiece I omega BoundaryPiece rho mu :=
  B.toBulkBoundarySeparatedBaseInput D.boundaryProjectLocal D.boundaryRoute

/-- Same base constructor, explicitly routed through the controlled-target
endpoint bridge.  This is useful when comparing with older callers that used
`toBulkBoundarySeparatedBaseInputOfControlledM8` directly. -/
def toBulkBoundarySeparatedBaseInputViaControlledM8 :
    NaturalCompactSupportBulkBoundarySeparatedBaseInput
      ExtInteriorPiece ExtBoundaryPiece I omega BoundaryPiece rho mu :=
  B.toBulkBoundarySeparatedBaseInputOfControlledM8
    D.unified D.globalMeasure D.faceContinuity
    D.targetImageAlignment.targetImageInput_eq

@[simp]
theorem toBulkBoundarySeparatedBaseInput_targetImageInput :
    D.toBulkBoundarySeparatedBaseInput.targetImageInput =
      B.targetImageInput :=
  rfl

@[simp]
theorem toBulkBoundarySeparatedBaseInput_boundaryProjectLocal :
    D.toBulkBoundarySeparatedBaseInput.boundaryProjectLocal =
      D.boundaryProjectLocal :=
  rfl

@[simp]
theorem toBulkBoundarySeparatedBaseInput_boundaryRoute :
    D.toBulkBoundarySeparatedBaseInput.boundaryRoute =
      D.boundaryRoute :=
  rfl

/-- Canonical theorem-facing interface for the compact-support endpoint
generated from unified boundary data. -/
def canonicalIntegralInterface :
    CanonicalIntegralInterface I omega :=
  (D.toBulkBoundarySeparatedBaseInput.separatedMeasure.toM8MeasureLocalizationData).canonicalIntegralInterface

@[simp]
theorem canonicalIntegralInterface_manifoldExtDerivIntegral :
    D.canonicalIntegralInterface.manifoldExtDerivIntegral =
      (D.toBulkBoundarySeparatedBaseInput.separatedMeasure.toM8MeasureLocalizationData).bulkMeasureIntegral :=
  rfl

@[simp]
theorem canonicalIntegralInterface_boundaryFormIntegral :
    D.canonicalIntegralInterface.boundaryFormIntegral =
      (D.toBulkBoundarySeparatedBaseInput.separatedMeasure.toM8MeasureLocalizationData).boundaryMeasureIntegral :=
  rfl

/-- Full separated-boundary Stokes input generated from unified boundary data
once artificial-face cancellation is supplied for the produced M8 localization
data. -/
def toBulkBoundarySeparatedInput
    (artificial :
      M8ArtificialFaceFields I omega BoundaryPiece
        D.toBulkBoundarySeparatedBaseInput.selectedPartition
        D.toBulkBoundarySeparatedBaseInput.targetImageInput.targetImages
        D.toBulkBoundarySeparatedBaseInput.separatedMeasure.toM8MeasureLocalizationData) :
    NaturalCompactSupportBulkBoundarySeparatedInput
      ExtInteriorPiece ExtBoundaryPiece I omega BoundaryPiece rho mu where
  base := D.toBulkBoundarySeparatedBaseInput
  artificial := artificial

@[simp]
theorem toBulkBoundarySeparatedInput_base
    (artificial :
      M8ArtificialFaceFields I omega BoundaryPiece
        D.toBulkBoundarySeparatedBaseInput.selectedPartition
        D.toBulkBoundarySeparatedBaseInput.targetImageInput.targetImages
        D.toBulkBoundarySeparatedBaseInput.separatedMeasure.toM8MeasureLocalizationData) :
    (D.toBulkBoundarySeparatedInput artificial).base =
      D.toBulkBoundarySeparatedBaseInput :=
  rfl

/-- Stokes for the compact-support endpoint generated from unified boundary
data, stated in canonical interface form. -/
theorem canonical_stokes
    (artificial :
      M8ArtificialFaceFields I omega BoundaryPiece
        D.toBulkBoundarySeparatedBaseInput.selectedPartition
        D.toBulkBoundarySeparatedBaseInput.targetImageInput.targetImages
        D.toBulkBoundarySeparatedBaseInput.separatedMeasure.toM8MeasureLocalizationData) :
    D.canonicalIntegralInterface.stokesStatement := by
  simpa [canonicalIntegralInterface, CanonicalIntegralInterface.stokesStatement]
    using (D.toBulkBoundarySeparatedInput artificial).canonical_stokes

/-- Equality form of the unified-boundary compact-support endpoint theorem. -/
theorem manifoldExtDerivIntegral_eq_boundaryFormIntegral
    (artificial :
      M8ArtificialFaceFields I omega BoundaryPiece
        D.toBulkBoundarySeparatedBaseInput.selectedPartition
        D.toBulkBoundarySeparatedBaseInput.targetImageInput.targetImages
        D.toBulkBoundarySeparatedBaseInput.separatedMeasure.toM8MeasureLocalizationData) :
    D.canonicalIntegralInterface.manifoldExtDerivIntegral =
      D.canonicalIntegralInterface.boundaryFormIntegral := by
  simpa [CanonicalIntegralInterface.stokesStatement] using
    D.canonical_stokes artificial

end BoundaryUnifiedEndpointGlobalMeasureData

/-- Support-finite variant of the unified boundary endpoint package. -/
structure BoundaryUnifiedEndpointSupportFiniteData where
  /-- Unified boundary source-alignment and controlled-target data. -/
  unified :
    BoundarySourceAlignmentUnifiedData
      (I := I) (omega := omega)
      (selectedPartition := B.selectedPartition)
      (orientedBoundaryAtlas := B.orientedBoundaryAtlas)
      (BoundaryPiece := BoundaryPiece)
  /-- Alignment between `B.targetImageInput` and the unified target-image
  input. -/
  targetImageAlignment :
    BoundaryUnifiedEndpointTargetImageAlignment B unified
  /-- Support-finite boundary measure reconstruction facts. -/
  supportFinite :
    ProjectLocalBoundarySupportFiniteMeasureFacts
      unified.toProjectLocalGlobalStokesData
  /-- Canonical lower-face continuity/integrability facts. -/
  faceContinuity :
    ProjectLocalBoundaryCanonicalFaceContinuityData
      unified.toProjectLocalGlobalStokesData

namespace BoundaryUnifiedEndpointSupportFiniteData

variable
    {B :
      NaturalCompactSupportBulkProjectLocalAutoCollapsedInput
        ExtInteriorPiece ExtBoundaryPiece
        I omega BoundaryPiece rho mu}
    (D : BoundaryUnifiedEndpointSupportFiniteData B)

/-- Forget support-finite facts to the global-measure endpoint package. -/
def toGlobalMeasureData :
    BoundaryUnifiedEndpointGlobalMeasureData B where
  unified := D.unified
  targetImageAlignment := D.targetImageAlignment
  globalMeasure := D.supportFinite.toGlobalMeasureFacts
  faceContinuity := D.faceContinuity

/-- Compact-support separated-boundary base input from support-finite unified
boundary data. -/
def toBulkBoundarySeparatedBaseInput :
    NaturalCompactSupportBulkBoundarySeparatedBaseInput
      ExtInteriorPiece ExtBoundaryPiece I omega BoundaryPiece rho mu :=
  D.toGlobalMeasureData.toBulkBoundarySeparatedBaseInput

/-- Canonical interface for the support-finite unified boundary route. -/
def canonicalIntegralInterface :
    CanonicalIntegralInterface I omega :=
  D.toGlobalMeasureData.canonicalIntegralInterface

/-- Stokes for the support-finite unified boundary route. -/
theorem canonical_stokes
    (artificial :
      M8ArtificialFaceFields I omega BoundaryPiece
        D.toBulkBoundarySeparatedBaseInput.selectedPartition
        D.toBulkBoundarySeparatedBaseInput.targetImageInput.targetImages
        D.toBulkBoundarySeparatedBaseInput.separatedMeasure.toM8MeasureLocalizationData) :
    D.canonicalIntegralInterface.stokesStatement := by
  simpa [canonicalIntegralInterface, toBulkBoundarySeparatedBaseInput] using
    D.toGlobalMeasureData.canonical_stokes artificial

/-- Equality form of the support-finite unified boundary route. -/
theorem manifoldExtDerivIntegral_eq_boundaryFormIntegral
    (artificial :
      M8ArtificialFaceFields I omega BoundaryPiece
        D.toBulkBoundarySeparatedBaseInput.selectedPartition
        D.toBulkBoundarySeparatedBaseInput.targetImageInput.targetImages
        D.toBulkBoundarySeparatedBaseInput.separatedMeasure.toM8MeasureLocalizationData) :
    D.canonicalIntegralInterface.manifoldExtDerivIntegral =
      D.canonicalIntegralInterface.boundaryFormIntegral := by
  simpa [CanonicalIntegralInterface.stokesStatement] using
    D.canonical_stokes artificial

end BoundaryUnifiedEndpointSupportFiniteData

end NaturalCompactSupportBulkProjectLocalAutoCollapsedInput

end BoundaryUnifiedToEndpointBaseAuto

end Stokes

end
