import Stokes.Global.BoundaryCanonicalTargetFromControlledCOVAuto
import Stokes.Global.BoundaryControlledTargetOrientationEndpointAuto
import Stokes.Global.BoundaryPartitionTermAlignmentAuto

/-!
# Natural controlled boundary target inputs

This module packages the controlled-target canonical boundary route one layer
closer to endpoint code.

The existing controlled route already knows how to build a
`CanonicalBoundaryTargetCompactSupportInput` and the boundary-only M8 measure
data once callers provide the project-local source alignment, boundary
partition-term alignment, global/support-finite measure facts, and canonical
face continuity.  The records below collect those pieces into theorem-facing
inputs and expose the two downstream packages directly.
-/

noncomputable section

set_option linter.style.longLine false
set_option linter.unusedSectionVars false

open Set MeasureTheory
open scoped BigOperators Manifold Topology

namespace Stokes

section BoundaryCanonicalTargetNaturalInputAuto

universe u w b

variable {H : Type u} [TopologicalSpace H]
variable {M : Type w} [TopologicalSpace M] [ChartedSpace H M]
variable {BoundaryPiece : Type b}
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) -> Real) H}
variable {omega : ManifoldForm I M n}
variable {selectedPartition : SelectedBoxPartitionOfUnity I omega}
variable {orientedBoundaryAtlas : BoundaryChartOrientedAtlas I M}

namespace M8BoundaryControlledTargetInput

variable
    (D :
      M8BoundaryControlledTargetInput I omega selectedPartition
        orientedBoundaryAtlas BoundaryPiece)
    {P : ProjectLocalGlobalStokesData I omega M BoundaryPiece}

namespace BoundaryCanonicalProjectLocalFields

variable (A : BoundaryCanonicalProjectLocalFields D (P := P))

/-- Selected chart-change data generated by a controlled boundary target and
the packaged project-local alignment fields. -/
def toBoundaryChartChangeSelectedFamilyData
    [IsManifold I 1 M] :
    BoundaryChartChangeSelectedFamilyData P :=
  D.family.toTargetImageResolvedFamily
    |>.toBoundaryChartChangeSelectedFamilyDataOfOrientationMembership
      orientedBoundaryAtlas
      (BoundaryChartTargetImageResolvedFamily.boundaryAtlasMembershipOfProjectLocalAlignment
        (T := D.toM8TargetImageInput) (P := P)
        (F := D.family.toTargetImageResolvedFamily)
        A.sourceAlignment A.toResolvedProjectLocalCompatibility)
      A.toResolvedProjectLocalCompatibility

/-- Canonical-indicator global measure facts derived from controlled target
chart-change data and canonical face continuity. -/
def toGlobalMeasureFactsOfFaceContinuity
    [IsManifold I 1 M]
    (faceContinuity : ProjectLocalBoundaryCanonicalFaceContinuityData P) :
    ProjectLocalBoundaryGlobalMeasureFacts P :=
  faceContinuity.toGlobalMeasureFactsOfSelected
    (A.toBoundaryChartChangeSelectedFamilyData (D := D))

/-- Canonical route input derived without asking for a separate global-measure
record: the canonical indicator finite sum is used as the boundary integrand. -/
def toBoundaryCanonicalRouteMeasureInputOfFaceContinuity
    [IsManifold I 1 M]
    (faceContinuity : ProjectLocalBoundaryCanonicalFaceContinuityData P) :
    BoundaryCanonicalRouteMeasureInput D.toM8TargetImageInput P :=
  (A.toGlobalMeasureFactsOfFaceContinuity (D := D) faceContinuity)
    |>.toBoundaryCanonicalRouteMeasureInputOfOrientationMembershipTargetImageResolved
      faceContinuity A.sourceAlignment D.family.toTargetImageResolvedFamily
      A.toResolvedProjectLocalCompatibility

/-- Canonical compact-support boundary target input generated from the
canonical-indicator route. -/
def toCanonicalBoundaryTargetCompactSupportInputOfFaceContinuity
    [IsManifold I 1 M]
    (faceContinuity : ProjectLocalBoundaryCanonicalFaceContinuityData P) :
    CanonicalBoundaryTargetCompactSupportInput
      (α := Fin n -> Real) D.toM8TargetImageInput
      (volume : Measure (Fin n -> Real)) :=
  (A.toBoundaryCanonicalRouteMeasureInputOfFaceContinuity
    (D := D) faceContinuity).toCanonicalBoundaryTargetCompactSupportInput

/-- Boundary-only M8 measure data generated from the canonical-indicator route. -/
def toCanonicalBoundaryM8MeasureDataOfFaceContinuity
    [IsManifold I 1 M]
    (faceContinuity : ProjectLocalBoundaryCanonicalFaceContinuityData P) :
    M8BoundaryMeasureData I omega selectedPartition
      D.toM8TargetImageInput.targetImages :=
  (A.toBoundaryCanonicalRouteMeasureInputOfFaceContinuity
    (D := D) faceContinuity).toCanonicalBoundaryM8MeasureData

@[simp]
theorem toBoundaryCanonicalRouteMeasureInputOfFaceContinuity_sourceAlignment
    [IsManifold I 1 M]
    (faceContinuity : ProjectLocalBoundaryCanonicalFaceContinuityData P) :
    (A.toBoundaryCanonicalRouteMeasureInputOfFaceContinuity
      (D := D) faceContinuity).sourceAlignment =
      A.sourceAlignment := by
  rfl

end BoundaryCanonicalProjectLocalFields

end M8BoundaryControlledTargetInput

/-- Natural input for the controlled boundary target route with explicit
project-local global measure facts. -/
structure BoundaryCanonicalTargetNaturalGlobalInput
    (D :
      M8BoundaryControlledTargetInput I omega selectedPartition
        orientedBoundaryAtlas BoundaryPiece)
    (P : ProjectLocalGlobalStokesData I omega M BoundaryPiece) where
  /-- Source and partition-term alignment between `P` and the controlled target. -/
  projectLocalFields :
    M8BoundaryControlledTargetInput.BoundaryCanonicalProjectLocalFields
      D (P := P)
  /-- Global boundary measure reconstruction facts for `P`. -/
  globalMeasure : ProjectLocalBoundaryGlobalMeasureFacts P
  /-- Canonical lower-face continuity/integrability facts. -/
  faceContinuity : ProjectLocalBoundaryCanonicalFaceContinuityData P

namespace BoundaryCanonicalTargetNaturalGlobalInput

variable
    {D :
      M8BoundaryControlledTargetInput I omega selectedPartition
        orientedBoundaryAtlas BoundaryPiece}
    {P : ProjectLocalGlobalStokesData I omega M BoundaryPiece}
    (N : BoundaryCanonicalTargetNaturalGlobalInput D P)

/-- The controlled target package as the M8 target-image input. -/
abbrev toM8TargetImageInput :
    M8TargetImageInput I omega selectedPartition orientedBoundaryAtlas
      BoundaryPiece :=
  D.toM8TargetImageInput

/-- Canonical route input generated from the natural global-measure package. -/
def toBoundaryCanonicalRouteMeasureInput
    [IsManifold I 1 M] :
    BoundaryCanonicalRouteMeasureInput D.toM8TargetImageInput P :=
  N.projectLocalFields.toBoundaryCanonicalRouteMeasureInputOfGlobalMeasure
    (D := D) N.globalMeasure N.faceContinuity

/-- Canonical compact-support target package generated from the natural input. -/
def toCanonicalBoundaryTargetCompactSupportInput
    [IsManifold I 1 M] :
    CanonicalBoundaryTargetCompactSupportInput
      (α := Fin n -> Real) D.toM8TargetImageInput
      (volume : Measure (Fin n -> Real)) :=
  N.toBoundaryCanonicalRouteMeasureInput.toCanonicalBoundaryTargetCompactSupportInput

/-- Boundary-only M8 measure data generated from the natural input. -/
def toM8BoundaryMeasureData
    [IsManifold I 1 M] :
    M8BoundaryMeasureData I omega selectedPartition
      D.toM8TargetImageInput.targetImages :=
  N.toBoundaryCanonicalRouteMeasureInput.toCanonicalBoundaryM8MeasureData

@[simp]
theorem toBoundaryCanonicalRouteMeasureInput_sourceAlignment
    [IsManifold I 1 M] :
    N.toBoundaryCanonicalRouteMeasureInput.sourceAlignment =
      N.projectLocalFields.sourceAlignment := by
  rfl

@[simp]
theorem toCanonicalBoundaryTargetCompactSupportInput_boundaryMeasureIntegral
    [IsManifold I 1 M] :
    N.toCanonicalBoundaryTargetCompactSupportInput.boundaryMeasureIntegral =
      N.toBoundaryCanonicalRouteMeasureInput.projectLocal.boundaryMeasureIntegral := by
  rfl

@[simp]
theorem toM8BoundaryMeasureData_boundaryPartitionTerm
    [IsManifold I 1 M] :
    N.toM8BoundaryMeasureData.boundaryPartitionTerm =
      D.toM8TargetImageInput.assembly.boundaryPartitionTerm := by
  rfl

@[simp]
theorem toM8BoundaryMeasureData_boundaryMeasureIntegral
    [IsManifold I 1 M] :
    N.toM8BoundaryMeasureData.boundaryMeasureIntegral =
      N.toBoundaryCanonicalRouteMeasureInput.projectLocal.boundaryMeasureIntegral := by
  rfl

end BoundaryCanonicalTargetNaturalGlobalInput

/-- Natural input for the controlled boundary target route with support-finite
project-local measure facts. -/
structure BoundaryCanonicalTargetNaturalSupportFiniteInput
    (D :
      M8BoundaryControlledTargetInput I omega selectedPartition
        orientedBoundaryAtlas BoundaryPiece)
    (P : ProjectLocalGlobalStokesData I omega M BoundaryPiece) where
  /-- Source and partition-term alignment between `P` and the controlled target. -/
  projectLocalFields :
    M8BoundaryControlledTargetInput.BoundaryCanonicalProjectLocalFields
      D (P := P)
  /-- Support-finite boundary measure reconstruction facts for `P`. -/
  supportFinite : ProjectLocalBoundarySupportFiniteMeasureFacts P
  /-- Canonical lower-face continuity/integrability facts. -/
  faceContinuity : ProjectLocalBoundaryCanonicalFaceContinuityData P

namespace BoundaryCanonicalTargetNaturalSupportFiniteInput

variable
    {D :
      M8BoundaryControlledTargetInput I omega selectedPartition
        orientedBoundaryAtlas BoundaryPiece}
    {P : ProjectLocalGlobalStokesData I omega M BoundaryPiece}
    (N : BoundaryCanonicalTargetNaturalSupportFiniteInput D P)

/-- Forget support-finite facts to the global-measure natural input. -/
def toGlobalInput :
    BoundaryCanonicalTargetNaturalGlobalInput D P where
  projectLocalFields := N.projectLocalFields
  globalMeasure := N.supportFinite.toGlobalMeasureFacts
  faceContinuity := N.faceContinuity

/-- Canonical route input generated from support-finite facts. -/
def toBoundaryCanonicalRouteMeasureInput
    [IsManifold I 1 M] :
    BoundaryCanonicalRouteMeasureInput D.toM8TargetImageInput P :=
  N.projectLocalFields.toBoundaryCanonicalRouteMeasureInputOfSupportFinite
    (D := D) N.supportFinite N.faceContinuity

/-- Canonical compact-support target package generated from support-finite facts. -/
def toCanonicalBoundaryTargetCompactSupportInput
    [IsManifold I 1 M] :
    CanonicalBoundaryTargetCompactSupportInput
      (α := Fin n -> Real) D.toM8TargetImageInput
      (volume : Measure (Fin n -> Real)) :=
  N.toBoundaryCanonicalRouteMeasureInput.toCanonicalBoundaryTargetCompactSupportInput

/-- Boundary-only M8 measure data generated from support-finite facts. -/
def toM8BoundaryMeasureData
    [IsManifold I 1 M] :
    M8BoundaryMeasureData I omega selectedPartition
      D.toM8TargetImageInput.targetImages :=
  N.toBoundaryCanonicalRouteMeasureInput.toCanonicalBoundaryM8MeasureData

@[simp]
theorem toGlobalInput_projectLocalFields :
    N.toGlobalInput.projectLocalFields = N.projectLocalFields := by
  rfl

@[simp]
theorem toBoundaryCanonicalRouteMeasureInput_sourceAlignment
    [IsManifold I 1 M] :
    N.toBoundaryCanonicalRouteMeasureInput.sourceAlignment =
      N.projectLocalFields.sourceAlignment := by
  rfl

@[simp]
theorem toM8BoundaryMeasureData_boundaryMeasureIntegral
    [IsManifold I 1 M] :
    N.toM8BoundaryMeasureData.boundaryMeasureIntegral =
      N.toBoundaryCanonicalRouteMeasureInput.projectLocal.boundaryMeasureIntegral := by
  rfl

end BoundaryCanonicalTargetNaturalSupportFiniteInput

/-- Natural input for the controlled boundary target route using the canonical
indicator reconstruction generated by face continuity. -/
structure BoundaryCanonicalTargetNaturalFaceInput
    (D :
      M8BoundaryControlledTargetInput I omega selectedPartition
        orientedBoundaryAtlas BoundaryPiece)
    (P : ProjectLocalGlobalStokesData I omega M BoundaryPiece) where
  /-- Source and partition-term alignment between `P` and the controlled target. -/
  projectLocalFields :
    M8BoundaryControlledTargetInput.BoundaryCanonicalProjectLocalFields
      D (P := P)
  /-- Canonical lower-face continuity/integrability facts. -/
  faceContinuity : ProjectLocalBoundaryCanonicalFaceContinuityData P

namespace BoundaryCanonicalTargetNaturalFaceInput

variable
    {D :
      M8BoundaryControlledTargetInput I omega selectedPartition
        orientedBoundaryAtlas BoundaryPiece}
    {P : ProjectLocalGlobalStokesData I omega M BoundaryPiece}
    (N : BoundaryCanonicalTargetNaturalFaceInput D P)

/-- The global-measure natural input generated by canonical indicator facts. -/
def toGlobalInput
    [IsManifold I 1 M] :
    BoundaryCanonicalTargetNaturalGlobalInput D P where
  projectLocalFields := N.projectLocalFields
  globalMeasure :=
    N.projectLocalFields.toGlobalMeasureFactsOfFaceContinuity
      (D := D) N.faceContinuity
  faceContinuity := N.faceContinuity

/-- Canonical route input generated from face-continuity data alone. -/
def toBoundaryCanonicalRouteMeasureInput
    [IsManifold I 1 M] :
    BoundaryCanonicalRouteMeasureInput D.toM8TargetImageInput P :=
  N.projectLocalFields.toBoundaryCanonicalRouteMeasureInputOfFaceContinuity
    (D := D) N.faceContinuity

/-- Canonical compact-support target package generated from face-continuity data. -/
def toCanonicalBoundaryTargetCompactSupportInput
    [IsManifold I 1 M] :
    CanonicalBoundaryTargetCompactSupportInput
      (α := Fin n -> Real) D.toM8TargetImageInput
      (volume : Measure (Fin n -> Real)) :=
  N.toBoundaryCanonicalRouteMeasureInput.toCanonicalBoundaryTargetCompactSupportInput

/-- Boundary-only M8 measure data generated from face-continuity data. -/
def toM8BoundaryMeasureData
    [IsManifold I 1 M] :
    M8BoundaryMeasureData I omega selectedPartition
      D.toM8TargetImageInput.targetImages :=
  N.toBoundaryCanonicalRouteMeasureInput.toCanonicalBoundaryM8MeasureData

@[simp]
theorem toGlobalInput_projectLocalFields
    [IsManifold I 1 M] :
    N.toGlobalInput.projectLocalFields = N.projectLocalFields := by
  rfl

@[simp]
theorem toBoundaryCanonicalRouteMeasureInput_sourceAlignment
    [IsManifold I 1 M] :
    N.toBoundaryCanonicalRouteMeasureInput.sourceAlignment =
      N.projectLocalFields.sourceAlignment := by
  rfl

@[simp]
theorem toM8BoundaryMeasureData_boundaryMeasureIntegral
    [IsManifold I 1 M] :
    N.toM8BoundaryMeasureData.boundaryMeasureIntegral =
      N.toBoundaryCanonicalRouteMeasureInput.projectLocal.boundaryMeasureIntegral := by
  rfl

end BoundaryCanonicalTargetNaturalFaceInput

end BoundaryCanonicalTargetNaturalInputAuto

end Stokes

end
