import Stokes.Global.BulkExtDerivFromExtDerivConstructor

/-!
# Selected-partition alignment for bulk exterior-derivative constructors

This module removes the selected active/coefficient bookkeeping from the
bulk exterior-derivative constructor route.

The minimal real source of the alignment is the selected-partition
`LocalizedFormEventuallyEqData` package: once the partition-local eventual
fields are generated from
`SelectedBoxPartitionOfUnity.toBulkLocalizedFormEventuallyEqData`, their
active set and coefficient family are definitionally the selected bulk ones.
The projection lemmas below expose that fact for both
`ExtDerivOnSupportData` and `PartitionExtDerivConstructorData`.
-/

noncomputable section

open Set Filter MeasureTheory
open scoped BigOperators Manifold Topology

namespace Stokes

section BulkExtDerivSelectedAlignmentAuto

universe u w cb pb ei eb

variable {H : Type u} [TopologicalSpace H]
variable {M : Type w} [TopologicalSpace M] [ChartedSpace H M]
variable {BoundaryChart : Type cb} {BoundaryPiece : Type pb}
variable {ExtInteriorPiece : Type ei} {ExtBoundaryPiece : Type eb}
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) → Real) H}
variable {omega : ManifoldForm I M n}
variable {P : SelectedBoxPartitionOfUnity I omega}
variable {boundary : BoundaryPieceFamilyInput I omega BoundaryChart BoundaryPiece}
variable {localized : LocalizedInteriorM8Fields I omega P}

namespace SelectedBoxPartitionOfUnity

/--
The partition-local eventual-equality fields canonically generated by a
selected partition for the combined interior/boundary labels.

The chart support is `univ`, because
`toBulkLocalizedFormEventuallyEqData` has already promoted reconstruction from
the selected support containment to a global eventual equality.
-/
def bulkSelectedLocalizedEventually
    (P : SelectedBoxPartitionOfUnity I omega)
    (boundary : BoundaryPieceFamilyInput I omega BoundaryChart BoundaryPiece)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K) :
    PartitionLocalizedEventuallyFields I omega (M ⊕ BoundaryChart) :=
  (P.toBulkLocalizedFormEventuallyEqData
    (BoundaryChart := BoundaryChart) boundary homegaSupport)
    |>.toPartitionLocalizedEventuallyFieldsOnUniv

@[simp]
theorem bulkSelectedLocalizedEventually_activeCharts
    (P : SelectedBoxPartitionOfUnity I omega)
    (boundary : BoundaryPieceFamilyInput I omega BoundaryChart BoundaryPiece)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K) :
    (P.bulkSelectedLocalizedEventually
      (BoundaryChart := BoundaryChart) boundary homegaSupport).activeCharts =
      selectedPartitionBulkActive P boundary := by
  rfl

@[simp]
theorem bulkSelectedLocalizedEventually_coefficient
    (P : SelectedBoxPartitionOfUnity I omega)
    (boundary : BoundaryPieceFamilyInput I omega BoundaryChart BoundaryPiece)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K) :
    (P.bulkSelectedLocalizedEventually
      (BoundaryChart := BoundaryChart) boundary homegaSupport).coefficient =
      selectedPartitionBulkCoefficient
        (BoundaryChart := BoundaryChart) P := by
  rfl

@[simp]
theorem bulkSelectedLocalizedEventually_chartSupport
    (P : SelectedBoxPartitionOfUnity I omega)
    (boundary : BoundaryPieceFamilyInput I omega BoundaryChart BoundaryPiece)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K) :
    (P.bulkSelectedLocalizedEventually
      (BoundaryChart := BoundaryChart) boundary homegaSupport).chartSupport =
      fun _ _ => univ := by
  rfl

end SelectedBoxPartitionOfUnity

namespace ExtDerivOnSupportData

/--
Build on-support exterior-derivative data from the canonical selected
partition-local eventual-equality fields.

The only alignment input is the genuine reconstruction active-set equality:
the reconstruction package must use the selected combined labels.  The
coefficient family and chart support are inherited from the selected
partition constructor.
-/
def ofSelectedPartitionReconstructionData
    (R :
      PartitionReconstructionData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (hactive : selectedPartitionBulkActive P boundary = R.activeCharts)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K) :
    ExtDerivOnSupportData I omega (M ⊕ BoundaryChart)
      ExtInteriorPiece ExtBoundaryPiece :=
  (P.bulkSelectedLocalizedEventually
    (BoundaryChart := BoundaryChart) boundary homegaSupport)
    |>.toExtDerivOnSupportData R (by simpa using hactive)

@[simp]
theorem ofSelectedPartitionReconstructionData_activeCharts
    (R :
      PartitionReconstructionData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (hactive : selectedPartitionBulkActive P boundary = R.activeCharts)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K) :
    (ofSelectedPartitionReconstructionData
      (P := P) (boundary := boundary)
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      R hactive homegaSupport).activeCharts =
      selectedPartitionBulkActive P boundary := by
  simpa [ofSelectedPartitionReconstructionData] using hactive.symm

@[simp]
theorem ofSelectedPartitionReconstructionData_coefficient
    (R :
      PartitionReconstructionData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (hactive : selectedPartitionBulkActive P boundary = R.activeCharts)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K) :
    (ofSelectedPartitionReconstructionData
      (P := P) (boundary := boundary)
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      R hactive homegaSupport).coefficient =
      selectedPartitionBulkCoefficient
        (BoundaryChart := BoundaryChart) P := by
  rfl

@[simp]
theorem ofSelectedPartitionReconstructionData_chartSupport
    (R :
      PartitionReconstructionData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (hactive : selectedPartitionBulkActive P boundary = R.activeCharts)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K) :
    (ofSelectedPartitionReconstructionData
      (P := P) (boundary := boundary)
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      R hactive homegaSupport).chartSupport =
      fun _ _ => univ := by
  rfl

end ExtDerivOnSupportData

namespace PartitionExtDerivConstructorData

/--
Build the partition exterior-derivative constructor from the canonical
selected partition-local eventual-equality fields.

This constructor chooses chart support `univ`, so the support-cover field is
automatic.  Its projections below show that the generated
`extDerivOnSupport` data is active on, and uses coefficients from, the
selected bulk partition.
-/
def ofSelectedPartitionReconstructionData
    (R :
      PartitionReconstructionData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (hactive : selectedPartitionBulkActive P boundary = R.activeCharts)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K) :
    PartitionExtDerivConstructorData I omega (M ⊕ BoundaryChart)
      ExtInteriorPiece ExtBoundaryPiece :=
  ofPartitionReconstructionData R
    (P.bulkSelectedLocalizedEventually
      (BoundaryChart := BoundaryChart) boundary homegaSupport)
    (by simpa using hactive)
    (by
      intro _x0 _x1 _y
      simp [SelectedBoxPartitionOfUnity.bulkSelectedLocalizedEventually])

@[simp]
theorem ofSelectedPartitionReconstructionData_localizedEventually
    (R :
      PartitionReconstructionData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (hactive : selectedPartitionBulkActive P boundary = R.activeCharts)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K) :
    (ofSelectedPartitionReconstructionData
      (P := P) (boundary := boundary)
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      R hactive homegaSupport).localizedEventually =
      P.bulkSelectedLocalizedEventually
        (BoundaryChart := BoundaryChart) boundary homegaSupport := by
  rfl

@[simp]
theorem ofSelectedPartitionReconstructionData_extDerivOnSupport_activeCharts
    (R :
      PartitionReconstructionData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (hactive : selectedPartitionBulkActive P boundary = R.activeCharts)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K) :
    (ofSelectedPartitionReconstructionData
      (P := P) (boundary := boundary)
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      R hactive homegaSupport).extDerivOnSupport.activeCharts =
      selectedPartitionBulkActive P boundary := by
  simpa [ofSelectedPartitionReconstructionData] using hactive.symm

@[simp]
theorem ofSelectedPartitionReconstructionData_extDerivOnSupport_coefficient
    (R :
      PartitionReconstructionData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (hactive : selectedPartitionBulkActive P boundary = R.activeCharts)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K) :
    (ofSelectedPartitionReconstructionData
      (P := P) (boundary := boundary)
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      R hactive homegaSupport).extDerivOnSupport.coefficient =
      selectedPartitionBulkCoefficient
        (BoundaryChart := BoundaryChart) P := by
  rfl

/--
Projection lemma: if a constructor package's partition-local eventual fields
are the canonical selected-partition fields, then its support-local
exterior-derivative active set is automatically the selected bulk active set.
-/
theorem extDerivOnSupport_activeCharts_eq_selected_of_localizedEventually
    (D :
      PartitionExtDerivConstructorData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K)
    (hselected :
      D.localizedEventually =
        P.bulkSelectedLocalizedEventually
          (BoundaryChart := BoundaryChart) boundary homegaSupport) :
    D.extDerivOnSupport.activeCharts =
      selectedPartitionBulkActive P boundary := by
  calc
    D.extDerivOnSupport.activeCharts = D.localizedEventually.activeCharts :=
      D.activeCharts_eq.symm
    _ =
        (P.bulkSelectedLocalizedEventually
          (BoundaryChart := BoundaryChart) boundary homegaSupport).activeCharts := by
      rw [hselected]
    _ = selectedPartitionBulkActive P boundary := by
      rfl

/--
Projection lemma: if a constructor package's partition-local eventual fields
are the canonical selected-partition fields, then its support-local
exterior-derivative coefficient family is automatically the selected bulk
coefficient family.
-/
theorem extDerivOnSupport_coefficient_eq_selected_of_localizedEventually
    (D :
      PartitionExtDerivConstructorData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K)
    (hselected :
      D.localizedEventually =
        P.bulkSelectedLocalizedEventually
          (BoundaryChart := BoundaryChart) boundary homegaSupport) :
    D.extDerivOnSupport.coefficient =
      selectedPartitionBulkCoefficient
        (BoundaryChart := BoundaryChart) P := by
  calc
    D.extDerivOnSupport.coefficient = D.localizedEventually.coefficient :=
      D.coefficient_eq.symm
    _ =
        (P.bulkSelectedLocalizedEventually
          (BoundaryChart := BoundaryChart) boundary homegaSupport).coefficient := by
      rw [hselected]
    _ =
        selectedPartitionBulkCoefficient
          (BoundaryChart := BoundaryChart) P := by
      rfl

end PartitionExtDerivConstructorData

namespace BulkIntegrandAEProjectLocalAutoInput

/--
Project-local automatic bulk a.e. input from a partition exterior-derivative
constructor whose localized-eventual source is the canonical selected
partition package.

Compared with
`ofPartitionExtDerivConstructorData`, callers no longer provide separate
selected active/coefficient alignment proofs; they are projected from the
stored constructor alignment against the selected localized-eventual source.
-/
def ofSelectedPartitionExtDerivConstructorData
    (D :
      PartitionExtDerivConstructorData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K)
    (hselected :
      D.localizedEventually =
        P.bulkSelectedLocalizedEventually
          (BoundaryChart := BoundaryChart) boundary homegaSupport)
    (measure : M → M → Measure (Fin (n + 1) → Real)) :
    BulkIntegrandAEProjectLocalAutoInput
      (BoundaryChart := BoundaryChart)
      ExtInteriorPiece ExtBoundaryPiece P boundary localized :=
  ofPartitionExtDerivConstructorData
    (P := P) (boundary := boundary) (localized := localized)
    D
    (D.extDerivOnSupport_activeCharts_eq_selected_of_localizedEventually
      (P := P) (boundary := boundary) homegaSupport hselected)
    (D.extDerivOnSupport_coefficient_eq_selected_of_localizedEventually
      (P := P) (boundary := boundary) homegaSupport hselected)
    measure

/--
Project-local automatic bulk a.e. input from reconstruction data using the
canonical selected partition exterior-derivative constructor.

The only active-set equality is the genuine one between the reconstruction
package and the selected combined labels.  The exterior-derivative
active/coefficient alignment is then automatic from the constructor above.
-/
def ofSelectedPartitionReconstructionData
    (R :
      PartitionReconstructionData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (hactive : selectedPartitionBulkActive P boundary = R.activeCharts)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K)
    (measure : M → M → Measure (Fin (n + 1) → Real)) :
    BulkIntegrandAEProjectLocalAutoInput
      (BoundaryChart := BoundaryChart)
      ExtInteriorPiece ExtBoundaryPiece P boundary localized :=
  ofSelectedPartitionExtDerivConstructorData
    (P := P) (boundary := boundary) (localized := localized)
    (PartitionExtDerivConstructorData.ofSelectedPartitionReconstructionData
      (P := P) (boundary := boundary)
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      R hactive homegaSupport)
    homegaSupport rfl measure

@[simp]
theorem ofSelectedPartitionExtDerivConstructorData_localizedEventually
    (D :
      PartitionExtDerivConstructorData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K)
    (hselected :
      D.localizedEventually =
        P.bulkSelectedLocalizedEventually
          (BoundaryChart := BoundaryChart) boundary homegaSupport)
    (measure : M → M → Measure (Fin (n + 1) → Real)) :
    (ofSelectedPartitionExtDerivConstructorData
      (P := P) (boundary := boundary) (localized := localized)
      D homegaSupport hselected measure).localizedEventually =
      D.localizedEventually := by
  rfl

@[simp]
theorem ofSelectedPartitionExtDerivConstructorData_reconstruction
    (D :
      PartitionExtDerivConstructorData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K)
    (hselected :
      D.localizedEventually =
        P.bulkSelectedLocalizedEventually
          (BoundaryChart := BoundaryChart) boundary homegaSupport)
    (measure : M → M → Measure (Fin (n + 1) → Real)) :
    (ofSelectedPartitionExtDerivConstructorData
      (P := P) (boundary := boundary) (localized := localized)
      D homegaSupport hselected measure).reconstruction =
      D.toPartitionReconstructionData := by
  rfl

@[simp]
theorem ofSelectedPartitionReconstructionData_reconstruction
    (R :
      PartitionReconstructionData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (hactive : selectedPartitionBulkActive P boundary = R.activeCharts)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K)
    (measure : M → M → Measure (Fin (n + 1) → Real)) :
    (ofSelectedPartitionReconstructionData
      (P := P) (boundary := boundary) (localized := localized)
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      R hactive homegaSupport measure).reconstruction =
      R := by
  rfl

@[simp]
theorem ofSelectedPartitionReconstructionData_measure
    (R :
      PartitionReconstructionData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (hactive : selectedPartitionBulkActive P boundary = R.activeCharts)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K)
    (measure : M → M → Measure (Fin (n + 1) → Real)) :
    (ofSelectedPartitionReconstructionData
      (P := P) (boundary := boundary) (localized := localized)
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      R hactive homegaSupport measure).measure =
      measure := by
  rfl

end BulkIntegrandAEProjectLocalAutoInput

end BulkExtDerivSelectedAlignmentAuto

end Stokes

end
