import Stokes.Global.ActiveStrictInnerOuterFromCompactSupportAuto
import Stokes.Global.NaturalCompactSupportOnePackageStokesAuto
import Stokes.Global.EndpointSelectedStrictMarginsFromNaturalChartBoxesAuto

/-!
# Compact-source strict-containment endpoint route

This file gives the compact-source object itself theorem-facing projections to
the endpoint chart-box containment route.  It keeps callers from manually
invoking `selectedStrictMarginsOfChartBoxContainment` before entering the
one-package compact-support Stokes theorem.
-/

noncomputable section

set_option linter.style.longLine false
set_option linter.unusedSectionVars false

open Set MeasureTheory
open scoped BigOperators Manifold Topology

namespace Stokes

section CompactSourceStrictContainmentRouteAuto

universe u w b ei eb

variable {H : Type u} [TopologicalSpace H]
variable {M : Type w} [TopologicalSpace M] [ChartedSpace H M]
variable {BoundaryPiece : Type b}
variable {ExtInteriorPiece : Type ei} {ExtBoundaryPiece : Type eb}
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) -> Real) H}
variable {omega : ManifoldForm I M n}
variable {rho : SmoothPartitionOfUnity M I M univ}
variable {mu : Measure (Fin (n + 1) -> Real)}
variable [IsFiniteMeasureOnCompacts mu]
variable [IsManifold I 1 M]

namespace CompactlySupportedSmoothFormData.NaturalFiniteActiveFromCompactSupportData

variable {formData : CompactlySupportedSmoothFormData I omega}
variable
    (D :
      CompactlySupportedSmoothFormData.NaturalFiniteActiveFromCompactSupportData
        (I := I) (omega := omega) (rho := rho) formData)

/-- Endpoint boundary/measure inputs over the selected chart boxes generated by
the compact-source package. -/
abbrev EndpointBoundaryMeasureInput :=
  NaturalCompactSupportEndpointNaturalBoundaryMeasureInput
    (I := I) (omega := omega) (rho := rho)
    D.toNaturalFiniteActiveChartBoxSelectionData
    ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu

/-- Endpoint chart-box containment over the compact-source selected boxes. -/
abbrev EndpointStrictContainment
    (boundaryMeasure : D.EndpointBoundaryMeasureInput
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      (BoundaryPiece := BoundaryPiece)
      (mu := mu)) :=
  boundaryMeasure.StrictAlignmentChartBoxContainmentData

/-- Endpoint selected strict margins generated from compact-source chart-box
containment. -/
def endpointSelectedStrictMarginsOfStrictContainment
    (boundaryMeasure : D.EndpointBoundaryMeasureInput
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      (BoundaryPiece := BoundaryPiece)
      (mu := mu))
    (C : D.EndpointStrictContainment boundaryMeasure) :
    boundaryMeasure.toSelectedReconstructionEndpointSource.EndpointSelectedBoxStrictMargins :=
  boundaryMeasure.selectedStrictMarginsOfChartBoxContainment C

/-- Chart-box one-package input generated from compact-source data and endpoint
chart-box containment. -/
def toOnePackageChartBoxStokesInputOfStrictContainment
    (boundaryMeasure : D.EndpointBoundaryMeasureInput
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      (BoundaryPiece := BoundaryPiece)
      (mu := mu))
    (chartAlignment :
      LocalizedInteriorM8ChartAlignment
        boundaryMeasure.toSelectedReconstructionEndpointSource.localized)
    (C : D.EndpointStrictContainment boundaryMeasure) :
    NaturalCompactSupportOnePackageChartBoxStokesInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu where
  formData := formData
  compactSource := D
  boundaryMeasure := boundaryMeasure
  chartAlignment := chartAlignment
  containment := C

/-- Selected-margin one-package input obtained by projecting the chart-box
one-package input; the strict margins are generated internally from
containment. -/
def toOnePackageStokesInputOfStrictContainment
    (boundaryMeasure : D.EndpointBoundaryMeasureInput
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      (BoundaryPiece := BoundaryPiece)
      (mu := mu))
    (chartAlignment :
      LocalizedInteriorM8ChartAlignment
        boundaryMeasure.toSelectedReconstructionEndpointSource.localized)
    (C : D.EndpointStrictContainment boundaryMeasure) :
    NaturalCompactSupportOnePackageStokesInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  (D.toOnePackageChartBoxStokesInputOfStrictContainment
    boundaryMeasure chartAlignment C).toSelectedMarginInput

@[simp]
theorem toOnePackageStokesInputOfStrictContainment_strictMargins
    (boundaryMeasure : D.EndpointBoundaryMeasureInput
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      (BoundaryPiece := BoundaryPiece)
      (mu := mu))
    (chartAlignment :
      LocalizedInteriorM8ChartAlignment
        boundaryMeasure.toSelectedReconstructionEndpointSource.localized)
    (C : D.EndpointStrictContainment boundaryMeasure) :
    (D.toOnePackageStokesInputOfStrictContainment
      boundaryMeasure chartAlignment C).strictMargins =
      D.endpointSelectedStrictMarginsOfStrictContainment boundaryMeasure C := by
  rfl

/-- Canonical compact-support Stokes from compact-source data and endpoint
chart-box containment. -/
theorem canonical_stokes_ofStrictContainment
    (boundaryMeasure : D.EndpointBoundaryMeasureInput
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      (BoundaryPiece := BoundaryPiece)
      (mu := mu))
    (chartAlignment :
      LocalizedInteriorM8ChartAlignment
        boundaryMeasure.toSelectedReconstructionEndpointSource.localized)
    (C : D.EndpointStrictContainment boundaryMeasure) :
    boundaryMeasure.canonicalIntegralInterface.stokesStatement :=
  NaturalCompactSupportOnePackageChartBoxStokesInput.canonical_stokes
    (D.toOnePackageChartBoxStokesInputOfStrictContainment
      boundaryMeasure chartAlignment C)

/-- Equality form of compact-support Stokes from compact-source data and
endpoint chart-box containment. -/
theorem manifoldExtDerivIntegral_eq_boundaryFormIntegral_ofStrictContainment
    (boundaryMeasure : D.EndpointBoundaryMeasureInput
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      (BoundaryPiece := BoundaryPiece)
      (mu := mu))
    (chartAlignment :
      LocalizedInteriorM8ChartAlignment
        boundaryMeasure.toSelectedReconstructionEndpointSource.localized)
    (C : D.EndpointStrictContainment boundaryMeasure) :
    boundaryMeasure.canonicalIntegralInterface.manifoldExtDerivIntegral =
      boundaryMeasure.canonicalIntegralInterface.boundaryFormIntegral :=
  NaturalCompactSupportOnePackageChartBoxStokesInput.manifoldExtDerivIntegral_eq_boundaryFormIntegral
    (D.toOnePackageChartBoxStokesInputOfStrictContainment
      boundaryMeasure chartAlignment C)

end CompactlySupportedSmoothFormData.NaturalFiniteActiveFromCompactSupportData

end CompactSourceStrictContainmentRouteAuto

end Stokes

end
