import Stokes.Global.CompactSupportChartBox
import Stokes.Global.PartitionCompactSupport
import Stokes.Global.NaturalInputData

/-!
# Compact-support finite-active selections

This module is a convenience entry point for the compact-support part of the
global Stokes pipeline.  Given a compact control set and a smooth partition of
unity, `FiniteActiveOnCompact.ofCompact` supplies the canonical finite active
chart set.  The constructors below then attach active compact coordinate
supports and, in finite real coordinates, automatically choose compact
coordinate boxes for them.

The remaining chart-domain facts are deliberately fieldized: the compact-box
selection theorem only boxes a compact coordinate set, while proving that the
chosen closed box lies in a chart target or chart overlap is local geometry.
-/

noncomputable section

open Set MeasureTheory Filter
open scoped Manifold Topology

namespace Stokes

set_option linter.unusedFintypeInType false

section CommonContainment

universe u v w

variable {E : Type u} [NormedAddCommGroup E] [NormedSpace Real E] [Preorder E]
variable {H : Type v} [TopologicalSpace H]
variable {M : Type w} [TopologicalSpace M] [ChartedSpace H M]
variable {I : ModelWithCorners Real E H} {k : Nat}

/--
The chart-domain containments still needed after compact coordinate boxes have
been selected for the active chart indices.
-/
structure ActiveCompactBoxChartContainment
    (P : FiniteActiveOnCompact (M := M) I)
    (box : M → CompactCoordinateBoxSelection E) where
  /-- Every active selected box lies in the target of its source chart. -/
  Icc_subset_target :
    ∀ i ∈ P.active, Set.Icc (box i).a (box i).b ⊆ (extChartAt I i).target
  /-- Every active selected box lies in the self-overlap chart domain. -/
  Icc_subset_overlap :
    ∀ i ∈ P.active, Set.Icc (box i).a (box i).b ⊆ ManifoldForm.chartOverlap I i i

/--
The smoothness-neighborhood data needed to upgrade selected compact active
boxes to extended boxes.
-/
structure ActiveCompactBoxSmoothness
    (P : FiniteActiveOnCompact (M := M) I)
    (box : M → CompactCoordinateBoxSelection E)
    (ω : ManifoldForm I M k) where
  /-- An ambient smoothness neighborhood for each active selected box. -/
  smoothSet : M → Set E
  /-- The smoothness neighborhood is open for every active index. -/
  isOpen_smoothSet :
    ∀ i ∈ P.active, IsOpen (smoothSet i)
  /-- The selected closed coordinate box is contained in the smoothness neighborhood. -/
  Icc_subset_smoothSet :
    ∀ i ∈ P.active, Set.Icc (box i).a (box i).b ⊆ smoothSet i
  /-- The transition-pullback representative is smooth on the chosen neighborhood. -/
  contDiffOn_smoothSet :
    ∀ i ∈ P.active,
      ContDiffOn Real ⊤ (ManifoldForm.transitionPullbackInChart I i i ω) (smoothSet i)

namespace CompactActiveBoxData

variable {ω : ManifoldForm I M k}

/--
Upgrade compact active selected boxes to compact active extended boxes using a
separate smoothness-neighborhood package.
-/
def toCompactActiveExtendedBoxDataOfSmoothness
    (D : CompactActiveBoxData I ω)
    (S : ActiveCompactBoxSmoothness D.finiteActive D.box ω) :
    CompactActiveExtendedBoxData I ω where
  boxData := D
  smoothSet := S.smoothSet
  isOpen_smoothSet := S.isOpen_smoothSet
  Icc_subset_smoothSet := by
    intro i hi
    simpa [CompactActiveBoxData.lower, CompactActiveBoxData.upper] using
      S.Icc_subset_smoothSet i hi
  contDiffOn_smoothSet := S.contDiffOn_smoothSet

@[simp]
theorem toCompactActiveExtendedBoxDataOfSmoothness_boxData
    (D : CompactActiveBoxData I ω)
    (S : ActiveCompactBoxSmoothness D.finiteActive D.box ω) :
    (D.toCompactActiveExtendedBoxDataOfSmoothness S).boxData = D :=
  rfl

@[simp]
theorem toCompactActiveExtendedBoxDataOfSmoothness_smoothSet
    (D : CompactActiveBoxData I ω)
    (S : ActiveCompactBoxSmoothness D.finiteActive D.box ω) :
    (D.toCompactActiveExtendedBoxDataOfSmoothness S).smoothSet = S.smoothSet :=
  rfl

end CompactActiveBoxData

end CommonContainment

section CompactSupportFiniteActive

universe u v w

variable {E : Type u} [NormedAddCommGroup E] [NormedSpace Real E] [Preorder E]
variable {H : Type v} [TopologicalSpace H]
variable {M : Type w} [TopologicalSpace M] [ChartedSpace H M]
variable {I : ModelWithCorners Real E H} {k : Nat}

namespace FiniteActiveOnCompact

/--
Canonical active chart compact-support data from a compact control set and a
smooth partition.  The active finite set is generated by
`FiniteActiveOnCompact.ofCompact`.
-/
def activeChartCompactSupportDataOfCompactSupport
    (ρ : SmoothPartitionOfUnity M I M univ)
    (K : Set M) (hK : IsCompact K)
    (ω : ManifoldForm I M k)
    (coordSupport : M → Set E)
    (hcompact :
      ∀ i ∈ (FiniteActiveOnCompact.ofCompact ρ K hK).active,
        IsCompact (coordSupport i))
    (hsupp :
      ∀ i ∈ (FiniteActiveOnCompact.ofCompact ρ K hK).active,
        tsupport (ManifoldForm.transitionPullbackInChart I i i ω) ⊆
          coordSupport i) :
    ActiveChartCompactSupportData (FiniteActiveOnCompact.ofCompact ρ K hK) ω :=
  ActiveChartCompactSupportData.of coordSupport hcompact hsupp

omit [Preorder E] in
@[simp]
theorem activeChartCompactSupportDataOfCompactSupport_coordSupport
    (ρ : SmoothPartitionOfUnity M I M univ)
    (K : Set M) (hK : IsCompact K)
    (ω : ManifoldForm I M k)
    (coordSupport : M → Set E)
    (hcompact :
      ∀ i ∈ (FiniteActiveOnCompact.ofCompact ρ K hK).active,
        IsCompact (coordSupport i))
    (hsupp :
      ∀ i ∈ (FiniteActiveOnCompact.ofCompact ρ K hK).active,
        tsupport (ManifoldForm.transitionPullbackInChart I i i ω) ⊆
          coordSupport i) :
    (activeChartCompactSupportDataOfCompactSupport ρ K hK ω coordSupport
      hcompact hsupp).coordSupport = coordSupport :=
  rfl

/--
Canonical active chart compact-image data from compact manifold-side supports.
Containment of the supports in chart sources gives the required chart
continuity; the active finite set again comes from `ofCompact`.
-/
def activeChartCompactImagesOfCompactSupport
    (ρ : SmoothPartitionOfUnity M I M univ)
    (K : Set M) (hK : IsCompact K)
    (sourceSupport : M → Set M)
    (hcompact :
      ∀ i ∈ (FiniteActiveOnCompact.ofCompact ρ K hK).active,
        IsCompact (sourceSupport i))
    (hsource :
      ∀ i ∈ (FiniteActiveOnCompact.ofCompact ρ K hK).active,
        sourceSupport i ⊆ (extChartAt I i).source) :
    ActiveChartCompactImages (I := I) (FiniteActiveOnCompact.ofCompact ρ K hK) :=
  ActiveChartCompactImages.ofSubsetSource sourceSupport hcompact hsource

omit [Preorder E] in
@[simp]
theorem activeChartCompactImagesOfCompactSupport_sourceSupport
    (ρ : SmoothPartitionOfUnity M I M univ)
    (K : Set M) (hK : IsCompact K)
    (sourceSupport : M → Set M)
    (hcompact :
      ∀ i ∈ (FiniteActiveOnCompact.ofCompact ρ K hK).active,
        IsCompact (sourceSupport i))
    (hsource :
      ∀ i ∈ (FiniteActiveOnCompact.ofCompact ρ K hK).active,
        sourceSupport i ⊆ (extChartAt I i).source) :
    (activeChartCompactImagesOfCompactSupport (I := I) ρ K hK sourceSupport
      hcompact hsource).sourceSupport = sourceSupport :=
  rfl

end FiniteActiveOnCompact

end CompactSupportFiniteActive

section PiRealCompactBoxes

universe u v w

variable {ι : Type u} [Fintype ι]
variable {H : Type v} [TopologicalSpace H]
variable {M : Type w} [TopologicalSpace M] [ChartedSpace H M]
variable {I : ModelWithCorners Real (ι → Real) H} {k : Nat}
variable {P : FiniteActiveOnCompact (M := M) I}
variable {ω : ManifoldForm I M k}

namespace ActiveChartCompactSupportData

/--
Turn active compact-support data into compact active box data, using the
fieldized chart target/overlap containments for the automatically selected
boxes.
-/
def toCompactActiveBoxDataOfContainment
    (D : ActiveChartCompactSupportData P ω)
    (C : ActiveCompactBoxChartContainment P D.box) :
    CompactActiveBoxData I ω :=
  D.toCompactActiveBoxData C.Icc_subset_target C.Icc_subset_overlap

@[simp]
theorem toCompactActiveBoxDataOfContainment_finiteActive
    (D : ActiveChartCompactSupportData P ω)
    (C : ActiveCompactBoxChartContainment P D.box) :
    (D.toCompactActiveBoxDataOfContainment C).finiteActive = P :=
  rfl

@[simp]
theorem toCompactActiveBoxDataOfContainment_coordSupport
    (D : ActiveChartCompactSupportData P ω)
    (C : ActiveCompactBoxChartContainment P D.box) :
    (D.toCompactActiveBoxDataOfContainment C).coordSupport = D.coordSupport :=
  rfl

@[simp]
theorem toCompactActiveBoxDataOfContainment_box
    (D : ActiveChartCompactSupportData P ω)
    (C : ActiveCompactBoxChartContainment P D.box) :
    (D.toCompactActiveBoxDataOfContainment C).box = D.box :=
  rfl

end ActiveChartCompactSupportData

namespace ActiveChartCompactImages

/--
Turn active compact chart images into compact active box data.  The coordinate
supports and boxes are generated from the image package; support containment
and chart-domain containment remain explicit inputs.
-/
def toCompactActiveBoxDataOfContainment
    (C : ActiveChartCompactImages (I := I) P)
    (ω : ManifoldForm I M k)
    (htsupport :
      ∀ i ∈ P.active,
        tsupport (ManifoldForm.transitionPullbackInChart I i i ω) ⊆
          C.coordSupport i)
    (hcontain : ActiveCompactBoxChartContainment P C.box) :
    CompactActiveBoxData I ω :=
  C.toCompactActiveBoxData ω htsupport hcontain.Icc_subset_target
    hcontain.Icc_subset_overlap

@[simp]
theorem toCompactActiveBoxDataOfContainment_finiteActive
    (C : ActiveChartCompactImages (I := I) P)
    (ω : ManifoldForm I M k)
    (htsupport :
      ∀ i ∈ P.active,
        tsupport (ManifoldForm.transitionPullbackInChart I i i ω) ⊆
          C.coordSupport i)
    (hcontain : ActiveCompactBoxChartContainment P C.box) :
    (C.toCompactActiveBoxDataOfContainment ω htsupport hcontain).finiteActive = P :=
  rfl

@[simp]
theorem toCompactActiveBoxDataOfContainment_coordSupport
    (C : ActiveChartCompactImages (I := I) P)
    (ω : ManifoldForm I M k)
    (htsupport :
      ∀ i ∈ P.active,
        tsupport (ManifoldForm.transitionPullbackInChart I i i ω) ⊆
          C.coordSupport i)
    (hcontain : ActiveCompactBoxChartContainment P C.box) :
    (C.toCompactActiveBoxDataOfContainment ω htsupport hcontain).coordSupport =
      C.coordSupport :=
  rfl

@[simp]
theorem toCompactActiveBoxDataOfContainment_box
    (C : ActiveChartCompactImages (I := I) P)
    (ω : ManifoldForm I M k)
    (htsupport :
      ∀ i ∈ P.active,
        tsupport (ManifoldForm.transitionPullbackInChart I i i ω) ⊆
          C.coordSupport i)
    (hcontain : ActiveCompactBoxChartContainment P C.box) :
    (C.toCompactActiveBoxDataOfContainment ω htsupport hcontain).box = C.box :=
  rfl

end ActiveChartCompactImages

namespace FiniteActiveOnCompact

/--
Direct compact-support constructor for compact active boxes.  It first builds
the canonical finite active package from `ρ`, `K`, and `hK`, then chooses
boxes for the active compact coordinate supports.
-/
def compactActiveBoxDataOfCompactSupport
    (ρ : SmoothPartitionOfUnity M I M univ)
    (K : Set M) (hK : IsCompact K)
    (ω : ManifoldForm I M k)
    (coordSupport : M → Set (ι → Real))
    (hcompact :
      ∀ i ∈ (FiniteActiveOnCompact.ofCompact ρ K hK).active,
        IsCompact (coordSupport i))
    (hsupp :
      ∀ i ∈ (FiniteActiveOnCompact.ofCompact ρ K hK).active,
        tsupport (ManifoldForm.transitionPullbackInChart I i i ω) ⊆
          coordSupport i)
    (hcontain :
      ActiveCompactBoxChartContainment
        (FiniteActiveOnCompact.ofCompact ρ K hK)
        (FiniteActiveOnCompact.activeChartCompactSupportDataOfCompactSupport
          ρ K hK ω coordSupport hcompact hsupp).box) :
    CompactActiveBoxData I ω :=
  (FiniteActiveOnCompact.activeChartCompactSupportDataOfCompactSupport
    ρ K hK ω coordSupport hcompact hsupp).toCompactActiveBoxDataOfContainment
      hcontain

@[simp]
theorem compactActiveBoxDataOfCompactSupport_finiteActive
    (ρ : SmoothPartitionOfUnity M I M univ)
    (K : Set M) (hK : IsCompact K)
    (ω : ManifoldForm I M k)
    (coordSupport : M → Set (ι → Real))
    (hcompact :
      ∀ i ∈ (FiniteActiveOnCompact.ofCompact ρ K hK).active,
        IsCompact (coordSupport i))
    (hsupp :
      ∀ i ∈ (FiniteActiveOnCompact.ofCompact ρ K hK).active,
        tsupport (ManifoldForm.transitionPullbackInChart I i i ω) ⊆
          coordSupport i)
    (hcontain :
      ActiveCompactBoxChartContainment
        (FiniteActiveOnCompact.ofCompact ρ K hK)
        (FiniteActiveOnCompact.activeChartCompactSupportDataOfCompactSupport
          ρ K hK ω coordSupport hcompact hsupp).box) :
    (compactActiveBoxDataOfCompactSupport ρ K hK ω coordSupport hcompact
      hsupp hcontain).finiteActive = FiniteActiveOnCompact.ofCompact ρ K hK :=
  rfl

/--
Direct compact-image constructor for compact active boxes.  The source supports
are compact manifold-side sets inside their chart sources; their coordinate
images and boxes are generated automatically.
-/
def compactActiveBoxDataOfChartCompactImages
    (ρ : SmoothPartitionOfUnity M I M univ)
    (K : Set M) (hK : IsCompact K)
    (ω : ManifoldForm I M k)
    (sourceSupport : M → Set M)
    (hcompact :
      ∀ i ∈ (FiniteActiveOnCompact.ofCompact ρ K hK).active,
        IsCompact (sourceSupport i))
    (hsource :
      ∀ i ∈ (FiniteActiveOnCompact.ofCompact ρ K hK).active,
        sourceSupport i ⊆ (extChartAt I i).source)
    (htsupport :
      ∀ i ∈ (FiniteActiveOnCompact.ofCompact ρ K hK).active,
        tsupport (ManifoldForm.transitionPullbackInChart I i i ω) ⊆
          (FiniteActiveOnCompact.activeChartCompactImagesOfCompactSupport
            ρ K hK sourceSupport hcompact hsource).coordSupport i)
    (hcontain :
      ActiveCompactBoxChartContainment
        (FiniteActiveOnCompact.ofCompact ρ K hK)
        (FiniteActiveOnCompact.activeChartCompactImagesOfCompactSupport
          ρ K hK sourceSupport hcompact hsource).box) :
    CompactActiveBoxData I ω :=
  (FiniteActiveOnCompact.activeChartCompactImagesOfCompactSupport
    ρ K hK sourceSupport hcompact hsource).toCompactActiveBoxDataOfContainment
      ω htsupport hcontain

@[simp]
theorem compactActiveBoxDataOfChartCompactImages_finiteActive
    (ρ : SmoothPartitionOfUnity M I M univ)
    (K : Set M) (hK : IsCompact K)
    (ω : ManifoldForm I M k)
    (sourceSupport : M → Set M)
    (hcompact :
      ∀ i ∈ (FiniteActiveOnCompact.ofCompact ρ K hK).active,
        IsCompact (sourceSupport i))
    (hsource :
      ∀ i ∈ (FiniteActiveOnCompact.ofCompact ρ K hK).active,
        sourceSupport i ⊆ (extChartAt I i).source)
    (htsupport :
      ∀ i ∈ (FiniteActiveOnCompact.ofCompact ρ K hK).active,
        tsupport (ManifoldForm.transitionPullbackInChart I i i ω) ⊆
          (FiniteActiveOnCompact.activeChartCompactImagesOfCompactSupport
            ρ K hK sourceSupport hcompact hsource).coordSupport i)
    (hcontain :
      ActiveCompactBoxChartContainment
        (FiniteActiveOnCompact.ofCompact ρ K hK)
        (FiniteActiveOnCompact.activeChartCompactImagesOfCompactSupport
          ρ K hK sourceSupport hcompact hsource).box) :
    (compactActiveBoxDataOfChartCompactImages ρ K hK ω sourceSupport hcompact
      hsource htsupport hcontain).finiteActive =
        FiniteActiveOnCompact.ofCompact ρ K hK :=
  rfl

end FiniteActiveOnCompact

/--
A compact support set, smooth partition, active compact-support package, and
the remaining chart-domain containments for the automatically selected boxes.

This is the ergonomic record form of
`FiniteActiveOnCompact.compactActiveBoxDataOfCompactSupport`.
-/
structure CompactSupportFiniteActiveSelection
    (ρ : SmoothPartitionOfUnity M I M univ)
    (K : Set M) (hK : IsCompact K)
    (ω : ManifoldForm I M k) where
  /-- Active compact-support data indexed by the canonical active set. -/
  supportData :
    ActiveChartCompactSupportData (FiniteActiveOnCompact.ofCompact ρ K hK) ω
  /-- Chart target and overlap containments for the automatically selected boxes. -/
  containment :
    ActiveCompactBoxChartContainment (FiniteActiveOnCompact.ofCompact ρ K hK)
      supportData.box

namespace CompactSupportFiniteActiveSelection

variable {ρ : SmoothPartitionOfUnity M I M univ}
variable {K : Set M} {hK : IsCompact K}

/-- The compact active box data generated by this selection. -/
def compactActiveBoxData
    (S : CompactSupportFiniteActiveSelection (I := I) ρ K hK ω) :
    CompactActiveBoxData I ω :=
  S.supportData.toCompactActiveBoxDataOfContainment S.containment

/-- The canonical finite-active package associated to this selection. -/
def finiteActive
    (S : CompactSupportFiniteActiveSelection (I := I) ρ K hK ω) :
    FiniteActiveOnCompact (M := M) I :=
  S.compactActiveBoxData.finiteActive

@[simp]
theorem compactActiveBoxData_finiteActive
    (S : CompactSupportFiniteActiveSelection (I := I) ρ K hK ω) :
    S.compactActiveBoxData.finiteActive = FiniteActiveOnCompact.ofCompact ρ K hK :=
  rfl

@[simp]
theorem compactActiveBoxData_coordSupport
    (S : CompactSupportFiniteActiveSelection (I := I) ρ K hK ω) :
    S.compactActiveBoxData.coordSupport = S.supportData.coordSupport :=
  rfl

@[simp]
theorem compactActiveBoxData_box
    (S : CompactSupportFiniteActiveSelection (I := I) ρ K hK ω) :
    S.compactActiveBoxData.box = S.supportData.box :=
  rfl

/-- Constructor from explicit active compact coordinate supports. -/
def ofCoordSupport
    (ρ : SmoothPartitionOfUnity M I M univ)
    (K : Set M) (hK : IsCompact K)
    (ω : ManifoldForm I M k)
    (coordSupport : M → Set (ι → Real))
    (hcompact :
      ∀ i ∈ (FiniteActiveOnCompact.ofCompact ρ K hK).active,
        IsCompact (coordSupport i))
    (hsupp :
      ∀ i ∈ (FiniteActiveOnCompact.ofCompact ρ K hK).active,
        tsupport (ManifoldForm.transitionPullbackInChart I i i ω) ⊆
          coordSupport i)
    (hcontain :
      ActiveCompactBoxChartContainment
        (FiniteActiveOnCompact.ofCompact ρ K hK)
        (FiniteActiveOnCompact.activeChartCompactSupportDataOfCompactSupport
          ρ K hK ω coordSupport hcompact hsupp).box) :
    CompactSupportFiniteActiveSelection (I := I) ρ K hK ω where
  supportData :=
    FiniteActiveOnCompact.activeChartCompactSupportDataOfCompactSupport
      ρ K hK ω coordSupport hcompact hsupp
  containment := hcontain

@[simp]
theorem ofCoordSupport_supportData
    (ρ : SmoothPartitionOfUnity M I M univ)
    (K : Set M) (hK : IsCompact K)
    (ω : ManifoldForm I M k)
    (coordSupport : M → Set (ι → Real))
    (hcompact :
      ∀ i ∈ (FiniteActiveOnCompact.ofCompact ρ K hK).active,
        IsCompact (coordSupport i))
    (hsupp :
      ∀ i ∈ (FiniteActiveOnCompact.ofCompact ρ K hK).active,
        tsupport (ManifoldForm.transitionPullbackInChart I i i ω) ⊆
          coordSupport i)
    (hcontain :
      ActiveCompactBoxChartContainment
        (FiniteActiveOnCompact.ofCompact ρ K hK)
        (FiniteActiveOnCompact.activeChartCompactSupportDataOfCompactSupport
          ρ K hK ω coordSupport hcompact hsupp).box) :
    (ofCoordSupport ρ K hK ω coordSupport hcompact hsupp hcontain).supportData =
      FiniteActiveOnCompact.activeChartCompactSupportDataOfCompactSupport
        ρ K hK ω coordSupport hcompact hsupp :=
  rfl

/-- Upgrade this selection to compact active extended boxes. -/
def compactActiveExtendedBoxData
    (S : CompactSupportFiniteActiveSelection (I := I) ρ K hK ω)
    (smoothness : ActiveCompactBoxSmoothness S.finiteActive S.supportData.box ω) :
    CompactActiveExtendedBoxData I ω :=
  S.compactActiveBoxData.toCompactActiveExtendedBoxDataOfSmoothness smoothness

/-- Package this selection as the existing selected-box partition wrapper. -/
def selectedBoxPartitionOfUnity
    (S : CompactSupportFiniteActiveSelection (I := I) ρ K hK ω)
    (smoothness : ActiveCompactBoxSmoothness S.finiteActive S.supportData.box ω) :
    SelectedBoxPartitionOfUnity I ω :=
  (S.compactActiveExtendedBoxData smoothness).toSelectedBoxPartitionOfUnity

@[simp]
theorem selectedBoxPartitionOfUnity_partition
    (S : CompactSupportFiniteActiveSelection (I := I) ρ K hK ω)
    (smoothness : ActiveCompactBoxSmoothness S.finiteActive S.supportData.box ω) :
    (S.selectedBoxPartitionOfUnity smoothness).partition = ρ :=
  rfl

@[simp]
theorem selectedBoxPartitionOfUnity_K
    (S : CompactSupportFiniteActiveSelection (I := I) ρ K hK ω)
    (smoothness : ActiveCompactBoxSmoothness S.finiteActive S.supportData.box ω) :
    (S.selectedBoxPartitionOfUnity smoothness).K = K :=
  rfl

@[simp]
theorem selectedBoxPartitionOfUnity_active
    (S : CompactSupportFiniteActiveSelection (I := I) ρ K hK ω)
    (smoothness : ActiveCompactBoxSmoothness S.finiteActive S.supportData.box ω) :
    (S.selectedBoxPartitionOfUnity smoothness).active =
      (FiniteActiveOnCompact.ofCompact ρ K hK).active :=
  rfl

end CompactSupportFiniteActiveSelection

end PiRealCompactBoxes

section CompactlySupportedSmoothFormFiniteActive

universe u w

variable {H : Type u} [TopologicalSpace H]
variable {M : Type w} [TopologicalSpace M] [ChartedSpace H M]
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) → Real) H}
variable {ω : ManifoldForm I M n}

namespace CompactlySupportedSmoothFormData

/--
The canonical finite-active package over the compact support set recorded by
`formData`.

This is the first natural selection step for compact-support Stokes: a smooth
partition of unity is restricted to the finitely many terms whose topological
supports meet `formData.supportSet`.
-/
def finiteActiveOfPartition
    (formData : CompactlySupportedSmoothFormData I ω)
    (ρ : SmoothPartitionOfUnity M I M univ) :
    FiniteActiveOnCompact (M := M) I :=
  FiniteActiveOnCompact.ofCompact ρ formData.supportSet
    formData.isCompact_supportSet

@[simp]
theorem finiteActiveOfPartition_partition
    (formData : CompactlySupportedSmoothFormData I ω)
    (ρ : SmoothPartitionOfUnity M I M univ) :
    (formData.finiteActiveOfPartition ρ).partition = ρ :=
  rfl

@[simp]
theorem finiteActiveOfPartition_K
    (formData : CompactlySupportedSmoothFormData I ω)
    (ρ : SmoothPartitionOfUnity M I M univ) :
    (formData.finiteActiveOfPartition ρ).K = formData.supportSet :=
  rfl

theorem finiteActiveOfPartition_isCompact_K
    (formData : CompactlySupportedSmoothFormData I ω)
    (ρ : SmoothPartitionOfUnity M I M univ) :
    (formData.finiteActiveOfPartition ρ).isCompact_K =
      formData.isCompact_supportSet :=
  rfl

/-- The compact part of the `i`-th partition support over `formData.supportSet`. -/
def partitionTSupportOnSupport
    (formData : CompactlySupportedSmoothFormData I ω)
    (ρ : SmoothPartitionOfUnity M I M univ) (i : M) : Set M :=
  (formData.finiteActiveOfPartition ρ).partitionTSupportOnCompact i

@[simp]
theorem partitionTSupportOnSupport_eq
    (formData : CompactlySupportedSmoothFormData I ω)
    (ρ : SmoothPartitionOfUnity M I M univ) (i : M) :
    formData.partitionTSupportOnSupport ρ i =
      tsupport (ρ i) ∩ formData.supportSet :=
  rfl

theorem isCompact_partitionTSupportOnSupport
    (formData : CompactlySupportedSmoothFormData I ω)
    (ρ : SmoothPartitionOfUnity M I M univ) (i : M) :
    IsCompact (formData.partitionTSupportOnSupport ρ i) :=
  (formData.finiteActiveOfPartition ρ).isCompact_partitionTSupportOnCompact i

/-- A nonempty partition support piece over `formData.supportSet` is active. -/
theorem mem_active_of_partitionTSupportOnSupport_nonempty
    (formData : CompactlySupportedSmoothFormData I ω)
    (ρ : SmoothPartitionOfUnity M I M univ) {i : M}
    (hi : (formData.partitionTSupportOnSupport ρ i).Nonempty) :
    i ∈ (formData.finiteActiveOfPartition ρ).active :=
  (formData.finiteActiveOfPartition ρ)
    |>.mem_active_of_partitionTSupportOnCompact_nonempty hi

/-- Inactive partition terms do not meet `formData.supportSet` in topological support. -/
theorem partitionTSupportOnSupport_eq_empty_of_not_mem_active
    (formData : CompactlySupportedSmoothFormData I ω)
    (ρ : SmoothPartitionOfUnity M I M univ) {i : M}
    (hi : i ∉ (formData.finiteActiveOfPartition ρ).active) :
    formData.partitionTSupportOnSupport ρ i = ∅ :=
  (formData.finiteActiveOfPartition ρ)
    |>.partitionTSupportOnCompact_eq_empty_of_not_mem_active hi

/--
The localized form cannot have algebraic support outside the compact support
set of the original form.
-/
theorem localizedForm_support_subset_supportSet
    (formData : CompactlySupportedSmoothFormData I ω)
    (ρ : SmoothPartitionOfUnity M I M univ) (i : M) :
    ManifoldForm.support I (ManifoldForm.localizedForm I (ρ i) ω) ⊆
      formData.supportSet := by
  exact
    (ManifoldForm.localizedForm_support_subset_form_support
      (I := I) (ρ i) ω).trans formData.support_subset_supportSet

/--
On `formData.supportSet`, the localized support lies in the compact part of
the coefficient support.
-/
theorem localizedForm_support_inter_supportSet_subset_partitionTSupportOnSupport
    (formData : CompactlySupportedSmoothFormData I ω)
    (ρ : SmoothPartitionOfUnity M I M univ) (i : M) :
    ManifoldForm.support I (ManifoldForm.localizedForm I (ρ i) ω) ∩
        formData.supportSet ⊆
      formData.partitionTSupportOnSupport ρ i := by
  simpa [finiteActiveOfPartition, partitionTSupportOnSupport] using
    (formData.finiteActiveOfPartition ρ)
      |>.localizedForm_support_inter_K_subset_partitionTSupportOnCompact
        (ω := ω) i

/--
On `formData.supportSet`, a localized form can be nonzero only where both the
coefficient is topologically active and the base form is algebraically nonzero.
-/
theorem localizedForm_support_inter_supportSet_subset_partitionTSupportOnSupport_inter_form_support
    (formData : CompactlySupportedSmoothFormData I ω)
    (ρ : SmoothPartitionOfUnity M I M univ) (i : M) :
    ManifoldForm.support I (ManifoldForm.localizedForm I (ρ i) ω) ∩
        formData.supportSet ⊆
      formData.partitionTSupportOnSupport ρ i ∩ ManifoldForm.support I ω := by
  simpa [finiteActiveOfPartition, partitionTSupportOnSupport] using
    (formData.finiteActiveOfPartition ρ)
      |>.localizedForm_support_inter_K_subset_partitionTSupportOnCompact_inter_form_support
        (ω := ω) i

/-- If a localized summand is nonzero on `formData.supportSet`, its index is active. -/
theorem mem_active_of_mem_localizedForm_support_on_supportSet
    (formData : CompactlySupportedSmoothFormData I ω)
    (ρ : SmoothPartitionOfUnity M I M univ) {x i : M}
    (hxK : x ∈ formData.supportSet)
    (hxloc :
      x ∈ ManifoldForm.support I (ManifoldForm.localizedForm I (ρ i) ω)) :
    i ∈ (formData.finiteActiveOfPartition ρ).active := by
  simpa [finiteActiveOfPartition] using
    (formData.finiteActiveOfPartition ρ)
      |>.mem_active_of_mem_localizedForm_support
        (ω := ω) (x := x) (i := i) hxK hxloc

/-- Inactive localized summands have empty algebraic support on `formData.supportSet`. -/
theorem localizedForm_support_inter_supportSet_eq_empty_of_not_mem_active
    (formData : CompactlySupportedSmoothFormData I ω)
    (ρ : SmoothPartitionOfUnity M I M univ) {i : M}
    (hi : i ∉ (formData.finiteActiveOfPartition ρ).active) :
    ManifoldForm.support I (ManifoldForm.localizedForm I (ρ i) ω) ∩
        formData.supportSet = ∅ := by
  simpa [finiteActiveOfPartition] using
    (formData.finiteActiveOfPartition ρ)
      |>.localizedForm_support_inter_K_eq_empty_of_not_mem_active
        (ω := ω) (i := i) hi

/-- Inactive localized summands are support-disjoint from `formData.supportSet`. -/
theorem disjoint_localizedForm_support_supportSet_of_not_mem_active
    (formData : CompactlySupportedSmoothFormData I ω)
    (ρ : SmoothPartitionOfUnity M I M univ) {i : M}
    (hi : i ∉ (formData.finiteActiveOfPartition ρ).active) :
    Disjoint
      (ManifoldForm.support I (ManifoldForm.localizedForm I (ρ i) ω))
      formData.supportSet := by
  simpa [finiteActiveOfPartition] using
    (formData.finiteActiveOfPartition ρ)
      |>.disjoint_localizedForm_support_K_of_not_mem_active
        (ω := ω) (i := i) hi

/-- Inactive localized summands vanish pointwise on `formData.supportSet`. -/
theorem localizedForm_eq_zero_of_mem_supportSet_of_not_mem_active
    (formData : CompactlySupportedSmoothFormData I ω)
    (ρ : SmoothPartitionOfUnity M I M univ) {x i : M}
    (hxK : x ∈ formData.supportSet)
    (hi : i ∉ (formData.finiteActiveOfPartition ρ).active) :
    ManifoldForm.localizedForm I (ρ i) ω x = 0 := by
  simpa [finiteActiveOfPartition] using
    (formData.finiteActiveOfPartition ρ)
      |>.localizedForm_eq_zero_of_mem_K_of_not_mem_active
        (ω := ω) (x := x) (i := i) hxK hi

/--
Construct the finite-active selected-box package over `formData.supportSet`
from compact coordinate supports.

The only geometric obligations left are the two actual local-domain facts for
the selected boxes: target containment and self-overlap containment.  Later
open-box/domain lemmas should prove these two hypotheses, instead of adding
more raw fields to the compact-support input.
-/
def finiteActiveSelectionOfCoordSupportOnSupport
    (formData : CompactlySupportedSmoothFormData I ω)
    (ρ : SmoothPartitionOfUnity M I M univ)
    (coordSupport : M → Set (Fin (n + 1) → Real))
    (hcompact :
      ∀ i ∈ (formData.finiteActiveOfPartition ρ).active,
        IsCompact (coordSupport i))
    (hsupp :
      ∀ i ∈ (formData.finiteActiveOfPartition ρ).active,
        tsupport (ManifoldForm.transitionPullbackInChart I i i ω) ⊆
          coordSupport i)
    (hIcc_subset_target :
      ∀ i ∈ (formData.finiteActiveOfPartition ρ).active,
        Set.Icc
          ((FiniteActiveOnCompact.activeChartCompactSupportDataOfCompactSupport
            ρ formData.supportSet formData.isCompact_supportSet ω
            coordSupport hcompact hsupp).box i).a
          ((FiniteActiveOnCompact.activeChartCompactSupportDataOfCompactSupport
            ρ formData.supportSet formData.isCompact_supportSet ω
            coordSupport hcompact hsupp).box i).b ⊆
          (extChartAt I i).target)
    (hIcc_subset_overlap :
      ∀ i ∈ (formData.finiteActiveOfPartition ρ).active,
        Set.Icc
          ((FiniteActiveOnCompact.activeChartCompactSupportDataOfCompactSupport
            ρ formData.supportSet formData.isCompact_supportSet ω
            coordSupport hcompact hsupp).box i).a
          ((FiniteActiveOnCompact.activeChartCompactSupportDataOfCompactSupport
            ρ formData.supportSet formData.isCompact_supportSet ω
            coordSupport hcompact hsupp).box i).b ⊆
          ManifoldForm.chartOverlap I i i) :
    CompactSupportFiniteActiveSelection
      (I := I) ρ formData.supportSet formData.isCompact_supportSet ω :=
  CompactSupportFiniteActiveSelection.ofCoordSupport
    ρ formData.supportSet formData.isCompact_supportSet ω
    coordSupport hcompact hsupp
    { Icc_subset_target := hIcc_subset_target
      Icc_subset_overlap := hIcc_subset_overlap }

@[simp]
theorem finiteActiveSelectionOfCoordSupportOnSupport_finiteActive
    (formData : CompactlySupportedSmoothFormData I ω)
    (ρ : SmoothPartitionOfUnity M I M univ)
    (coordSupport : M → Set (Fin (n + 1) → Real))
    (hcompact :
      ∀ i ∈ (formData.finiteActiveOfPartition ρ).active,
        IsCompact (coordSupport i))
    (hsupp :
      ∀ i ∈ (formData.finiteActiveOfPartition ρ).active,
        tsupport (ManifoldForm.transitionPullbackInChart I i i ω) ⊆
          coordSupport i)
    (hIcc_subset_target :
      ∀ i ∈ (formData.finiteActiveOfPartition ρ).active,
        Set.Icc
          ((FiniteActiveOnCompact.activeChartCompactSupportDataOfCompactSupport
            ρ formData.supportSet formData.isCompact_supportSet ω
            coordSupport hcompact hsupp).box i).a
          ((FiniteActiveOnCompact.activeChartCompactSupportDataOfCompactSupport
            ρ formData.supportSet formData.isCompact_supportSet ω
            coordSupport hcompact hsupp).box i).b ⊆
          (extChartAt I i).target)
    (hIcc_subset_overlap :
      ∀ i ∈ (formData.finiteActiveOfPartition ρ).active,
        Set.Icc
          ((FiniteActiveOnCompact.activeChartCompactSupportDataOfCompactSupport
            ρ formData.supportSet formData.isCompact_supportSet ω
            coordSupport hcompact hsupp).box i).a
          ((FiniteActiveOnCompact.activeChartCompactSupportDataOfCompactSupport
            ρ formData.supportSet formData.isCompact_supportSet ω
            coordSupport hcompact hsupp).box i).b ⊆
          ManifoldForm.chartOverlap I i i) :
    (formData.finiteActiveSelectionOfCoordSupportOnSupport ρ coordSupport
      hcompact hsupp hIcc_subset_target hIcc_subset_overlap).finiteActive =
      formData.finiteActiveOfPartition ρ :=
  rfl

@[simp]
theorem finiteActiveSelectionOfCoordSupportOnSupport_supportSet
    (formData : CompactlySupportedSmoothFormData I ω)
    (ρ : SmoothPartitionOfUnity M I M univ)
    (coordSupport : M → Set (Fin (n + 1) → Real))
    (hcompact :
      ∀ i ∈ (formData.finiteActiveOfPartition ρ).active,
        IsCompact (coordSupport i))
    (hsupp :
      ∀ i ∈ (formData.finiteActiveOfPartition ρ).active,
        tsupport (ManifoldForm.transitionPullbackInChart I i i ω) ⊆
          coordSupport i)
    (hIcc_subset_target :
      ∀ i ∈ (formData.finiteActiveOfPartition ρ).active,
        Set.Icc
          ((FiniteActiveOnCompact.activeChartCompactSupportDataOfCompactSupport
            ρ formData.supportSet formData.isCompact_supportSet ω
            coordSupport hcompact hsupp).box i).a
          ((FiniteActiveOnCompact.activeChartCompactSupportDataOfCompactSupport
            ρ formData.supportSet formData.isCompact_supportSet ω
            coordSupport hcompact hsupp).box i).b ⊆
          (extChartAt I i).target)
    (hIcc_subset_overlap :
      ∀ i ∈ (formData.finiteActiveOfPartition ρ).active,
        Set.Icc
          ((FiniteActiveOnCompact.activeChartCompactSupportDataOfCompactSupport
            ρ formData.supportSet formData.isCompact_supportSet ω
            coordSupport hcompact hsupp).box i).a
          ((FiniteActiveOnCompact.activeChartCompactSupportDataOfCompactSupport
            ρ formData.supportSet formData.isCompact_supportSet ω
            coordSupport hcompact hsupp).box i).b ⊆
          ManifoldForm.chartOverlap I i i) :
    (formData.finiteActiveSelectionOfCoordSupportOnSupport ρ coordSupport
      hcompact hsupp hIcc_subset_target hIcc_subset_overlap).compactActiveBoxData.finiteActive.K =
      formData.supportSet :=
  rfl

end CompactlySupportedSmoothFormData

end CompactlySupportedSmoothFormFiniteActive

end Stokes

end
