import Stokes.Global.CoverIndexedZeroCompactRefinedEndpointAdapter

/-!
# Reconstruction from refined local Stokes to represented Stokes

This file is the Wave 2 reconstruction handoff for the compact-support
represented Stokes route.  It does not introduce a new integral definition:
all represented bulk and boundary quantities come from the refined endpoint
adapter, and this module only records the finite-sum algebra that turns a
refined local Stokes equality into the represented equality.

The adapter already provides the reconstruction fields

* represented bulk integral = refined local bulk sum;
* refined local boundary sum = selected boundary-partition sum; and
* represented boundary integral = selected boundary-partition sum.

The public theorem below composes those fields with local Stokes.  Two entry
points are provided: one for the nested refined sum, and one for the flattened
sigma-indexed sum produced by the endpoint adapter.
-/

noncomputable section

set_option linter.unusedSectionVars false
set_option linter.style.longLine false

open Set MeasureTheory Filter
open scoped BigOperators Manifold Topology

namespace Stokes

section RefinedReconstruction

universe uH uM uP

variable {H : Type uH} [TopologicalSpace H]
variable {M : Type uM} [TopologicalSpace M] [ChartedSpace H M]
variable {BoundaryPiece : Type uP}
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) -> Real) H}
variable {K : Set M}
variable {omega : ManifoldForm I M n}
variable {C : CompactSupportChartCoverSelection I K}
variable {P : SupportControlledSelectedPartition C}

namespace CoverIndexedBoundaryBoxRefinedPartition

namespace RefinedEndpointAdapter

variable
    {D :
      CoverIndexedBoundaryBoxRefinedPartition
        (I := I) (K := K) C P omega BoundaryPiece}
    (A : D.RefinedEndpointAdapter (I := I) (K := K))

/--
Represented compact-support Stokes from a nested refined local Stokes equality.

This is the reconstruction theorem expected by the Wave 2 local-Stokes module:
the only analytic input is the equality of the finite refined local bulk and
boundary sums.  The endpoint adapter supplies all represented-integral
reconstruction fields.
-/
theorem representedStokes_of_refinedLocalStokes
    (hlocal :
      D.refinedBoundaryNestedSum (I := I) (K := K) D.localBulkTerm =
        D.refinedBoundaryNestedSum (I := I) (K := K) D.localBoundaryTerm) :
    A.representedBulkIntegral = A.representedBoundaryIntegral :=
  A.representedBulkIntegral_eq_representedBoundaryIntegral
    (I := I) (K := K) hlocal

/--
Represented compact-support Stokes from a flattened sigma-indexed refined local
Stokes equality.

This is the same theorem as `representedStokes_of_refinedLocalStokes`, but it
consumes the flattened finite-sum shape generated by
`D.refinedBoundaryIndexSet`.  It is the bookkeeping bridge between agents that
prefer nested sums and agents that prefer flattened sigma indices.
-/
theorem representedStokes_of_refinedFlatLocalStokes
    (hflat :
      D.refinedBoundaryFlatSum (I := I) (K := K) D.localBulkTerm =
        D.refinedBoundaryFlatSum (I := I) (K := K) D.localBoundaryTerm) :
    A.representedBulkIntegral = A.representedBoundaryIntegral := by
  apply A.representedStokes_of_refinedLocalStokes (I := I) (K := K)
  calc
    D.refinedBoundaryNestedSum (I := I) (K := K) D.localBulkTerm =
        D.refinedBoundaryFlatSum (I := I) (K := K) D.localBulkTerm :=
      D.refinedLocalBulkNestedSum_eq_flatSum (I := I) (K := K)
    _ = D.refinedBoundaryFlatSum (I := I) (K := K) D.localBoundaryTerm :=
      hflat
    _ = D.refinedBoundaryNestedSum (I := I) (K := K) D.localBoundaryTerm :=
      (D.refinedLocalBoundaryNestedSum_eq_flatSum (I := I) (K := K)).symm

/--
Represented compact-support Stokes from a local Stokes equality over the
logical flattened refined-piece type.

This variant is useful when later code phrases refined pieces as
`CoverIndexedRefinedBoundaryPiece D` rather than as raw sigma indices.
-/
theorem representedStokes_of_refinedPieceLocalStokes
    (hpiece :
      D.refinedBoundaryPieceSum (I := I) (K := K)
          (fun r =>
            D.localBulkTerm
              (CoverIndexedRefinedBoundaryPiece.owner r)
              (CoverIndexedRefinedBoundaryPiece.piece r)) =
        D.refinedBoundaryPieceSum (I := I) (K := K)
          (fun r =>
            D.localBoundaryTerm
              (CoverIndexedRefinedBoundaryPiece.owner r)
              (CoverIndexedRefinedBoundaryPiece.piece r))) :
    A.representedBulkIntegral = A.representedBoundaryIntegral := by
  apply A.representedStokes_of_refinedLocalStokes (I := I) (K := K)
  calc
    D.refinedBoundaryNestedSum (I := I) (K := K) D.localBulkTerm =
        D.refinedBoundaryPieceSum (I := I) (K := K)
          (fun r =>
            D.localBulkTerm
              (CoverIndexedRefinedBoundaryPiece.owner r)
              (CoverIndexedRefinedBoundaryPiece.piece r)) :=
      D.refinedBoundaryNestedSum_eq_pieceSum (I := I) (K := K)
        D.localBulkTerm
    _ = D.refinedBoundaryPieceSum (I := I) (K := K)
          (fun r =>
            D.localBoundaryTerm
              (CoverIndexedRefinedBoundaryPiece.owner r)
              (CoverIndexedRefinedBoundaryPiece.piece r)) :=
      hpiece
    _ = D.refinedBoundaryNestedSum (I := I) (K := K) D.localBoundaryTerm :=
      (D.refinedBoundaryNestedSum_eq_pieceSum (I := I) (K := K)
        D.localBoundaryTerm).symm

end RefinedEndpointAdapter

end CoverIndexedBoundaryBoxRefinedPartition

/--
Decision-complete input package for refined represented reconstruction.

It keeps the three pieces that are mathematically distinct at this stage:
the refined partition `D`, the endpoint reconstruction adapter, and the local
Stokes equality over the refined local sums.
-/
structure CoverIndexedZeroCompactRefinedReconstructionInput where
  D :
    CoverIndexedBoundaryBoxRefinedPartition
      (I := I) (K := K) C P omega BoundaryPiece
  adapter : D.RefinedEndpointAdapter (I := I) (K := K)
  refinedLocalStokes :
    D.refinedBoundaryNestedSum (I := I) (K := K) D.localBulkTerm =
      D.refinedBoundaryNestedSum (I := I) (K := K) D.localBoundaryTerm

namespace CoverIndexedZeroCompactRefinedReconstructionInput

variable (R :
  CoverIndexedZeroCompactRefinedReconstructionInput
    (I := I) (K := K) (omega := omega)
    (C := C) (P := P) (BoundaryPiece := BoundaryPiece))

/-- Bulk finite-additivity data carried by the endpoint adapter. -/
def bulkFiniteAdditivityData :
    LocalIntegralFiniteAdditivityData
      (CoverIndexedBoundaryIndex (I := I) C) BoundaryPiece :=
  R.adapter.bulkFiniteAdditivityData (I := I) (K := K)

/-- Boundary finite-additivity data carried by the endpoint adapter. -/
def boundaryFiniteAdditivityData :
    LocalIntegralFiniteAdditivityData
      (CoverIndexedBoundaryIndex (I := I) C) BoundaryPiece :=
  R.adapter.boundaryFiniteAdditivityData (I := I) (K := K)

/-- Existing partition reconstruction package generated by the endpoint adapter. -/
def toPartitionReconstructionData :
    PartitionReconstructionData I omega
      (CoverIndexedBoundaryIndex (I := I) C) Empty BoundaryPiece :=
  R.adapter.toPartitionReconstructionData (I := I) (K := K)

@[simp]
theorem toPartitionReconstructionData_globalBulkIntegral :
    (R.toPartitionReconstructionData
      (I := I) (K := K) (omega := omega)).globalBulkIntegral =
      R.adapter.representedBulkIntegral :=
  rfl

@[simp]
theorem toPartitionReconstructionData_globalBoundaryIntegral :
    (R.toPartitionReconstructionData
      (I := I) (K := K) (omega := omega)).globalBoundaryIntegral =
      R.adapter.representedBoundaryIntegral :=
  rfl

/--
Final reconstruction theorem for the input package: local refined Stokes plus
the stored reconstruction adapter proves represented bulk equals represented
boundary.
-/
theorem representedStokes :
    R.adapter.representedBulkIntegral =
      R.adapter.representedBoundaryIntegral :=
  CoverIndexedBoundaryBoxRefinedPartition.RefinedEndpointAdapter.representedStokes_of_refinedLocalStokes
    (I := I) (K := K) R.adapter R.refinedLocalStokes

/-- Alias in the explicit equality style used by reconstruction packages. -/
theorem representedBulkIntegral_eq_representedBoundaryIntegral :
    R.adapter.representedBulkIntegral =
      R.adapter.representedBoundaryIntegral :=
  representedStokes (I := I) (K := K) (omega := omega) R

end CoverIndexedZeroCompactRefinedReconstructionInput

end RefinedReconstruction

end Stokes

end
