import Stokes.Global.CoverIndexedZeroCompactBoxPartitionRefinement

/-!
# Canonical endpoint for localized refined boundary partitions

This module records the final bookkeeping step for a boundary-localized
refined partition whose local bulk and boundary terms have already been
constructed.  The represented integrals here are generated by construction:

* represented bulk integral = the nested finite sum of local bulk terms; and
* represented boundary integral = the nested finite sum of local boundary
  terms.

Consequently, a finite-sum local Stokes equality immediately reconstructs the
represented endpoint equality.  No manifold-native integral claim is made in
this file.
-/

noncomputable section

set_option linter.unusedSectionVars false
set_option linter.style.longLine false

open Set MeasureTheory Filter
open scoped BigOperators Manifold Topology

namespace Stokes

section BoundaryLocalizedRefinedEndpoint

universe uH uM uB

variable {H : Type uH} [TopologicalSpace H]
variable {M : Type uM} [TopologicalSpace M] [ChartedSpace H M]
variable {BoundaryPiece : Type uB}
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) → Real) H}
variable {K : Set M}
variable {ω : ManifoldForm I M n}
variable {C : CompactSupportChartCoverSelection I K}
variable {P : SupportControlledSelectedPartition C}

/--
Boundary-localized refined partition data at the endpoint algebra layer.

The structure intentionally stores only the finite refined boundary family and
the two local scalar term families.  Geometry, support, smoothness, and local
Stokes proofs belong to earlier construction modules.
-/
structure CoverIndexedBoundaryLocalizedRefinedPartition
    (C : CompactSupportChartCoverSelection I K)
    (P : SupportControlledSelectedPartition C)
    (ω : ManifoldForm I M n) (BoundaryPiece : Type uB) where
  /-- Finite localized refined pieces attached to each boundary cover index. -/
  boundaryPieces : CoverIndexedBoundaryIndex (I := I) C → Finset BoundaryPiece
  /-- Local represented bulk term on one localized refined boundary piece. -/
  localBulkTerm : CoverIndexedBoundaryIndex (I := I) C → BoundaryPiece → Real
  /-- Local represented boundary term on one localized refined boundary piece. -/
  localBoundaryTerm :
    CoverIndexedBoundaryIndex (I := I) C → BoundaryPiece → Real

namespace CoverIndexedBoundaryLocalizedRefinedPartition

variable
    (D :
      CoverIndexedBoundaryLocalizedRefinedPartition
        (I := I) (K := K) C P ω BoundaryPiece)

/-- Nested finite sum of generated local bulk representatives. -/
def generatedRepresentedBulkIntegral : Real :=
  Finset.sum
    (Finset.univ : Finset (CoverIndexedBoundaryIndex (I := I) C)) fun i =>
      Finset.sum (D.boundaryPieces i) fun q => D.localBulkTerm i q

/-- Nested finite sum of generated local boundary representatives. -/
def generatedRepresentedBoundaryIntegral : Real :=
  Finset.sum
    (Finset.univ : Finset (CoverIndexedBoundaryIndex (I := I) C)) fun i =>
      Finset.sum (D.boundaryPieces i) fun q => D.localBoundaryTerm i q

/--
Represented Stokes for generated endpoint names, from the local finite-sum
Stokes equality.

This is represented-by-construction: both sides are the nested sums above.
-/
theorem representedStokes_of_localStokes
    (hlocal :
      (Finset.sum
          (Finset.univ : Finset (CoverIndexedBoundaryIndex (I := I) C)) fun i =>
          Finset.sum (D.boundaryPieces i) fun q => D.localBulkTerm i q) =
        Finset.sum
          (Finset.univ : Finset (CoverIndexedBoundaryIndex (I := I) C)) fun i =>
          Finset.sum (D.boundaryPieces i) fun q => D.localBoundaryTerm i q) :
    D.generatedRepresentedBulkIntegral (I := I) (K := K) =
      D.generatedRepresentedBoundaryIntegral (I := I) (K := K) := by
  simpa [generatedRepresentedBulkIntegral,
    generatedRepresentedBoundaryIntegral] using hlocal

end CoverIndexedBoundaryLocalizedRefinedPartition

end BoundaryLocalizedRefinedEndpoint

end Stokes

end
