import Stokes.Global.CoverIndexedZeroRelativeBoundaryAssemblyInputConstructor
import Stokes.Global.CoverIndexedZeroCompactRelativeAssemblyConstructor
import Stokes.Global.CoverIndexedZeroRelativeSourceNeighborhoodWrappers

/-!
# Natural constructor for the compact-support relative zero endpoint

This file packages the glue needed by the relative compact-support zero route.
It does not choose source neighborhoods or target boxes.  Instead, once those
geometric data are available, it builds the relative source-target assembly and
the compact-support constructor input with the boundary scalar specialized to
the actual target boundary integral.
-/

noncomputable section

set_option linter.unusedSectionVars false
set_option linter.style.longLine false

open Set MeasureTheory Filter
open scoped BigOperators Manifold Topology

namespace Stokes

section CoverIndexedZeroCompactRelativeNaturalConstructor

universe uH uM

variable {H : Type uH} [TopologicalSpace H]
variable {M : Type uM} [TopologicalSpace M] [ChartedSpace H M]
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) → Real) H}
variable {K : Set M}
variable {omega : ManifoldForm I M n}
variable {C : CompactSupportChartCoverSelection I K}
variable {P : SupportControlledSelectedPartition C}
variable {muBulk : Measure (Fin (n + 1) → Real)}

/-- Natural input for the compact-support zero route using relative source
neighborhoods.

The record stores only the geometric and compact-support fields that upstream
selection lemmas should produce.  The zero target-boundary scalar support, the
relative source-target assembly package, and the final constructor input are
derived below. -/
structure CoverIndexedZeroCompactRelativeNaturalInput
    (C : CompactSupportChartCoverSelection I K)
    (P : SupportControlledSelectedPartition C)
    (omega : ManifoldForm I M n)
    (muBulk : Measure (Fin (n + 1) → Real)) where
  carrierData :
    CoverIndexedCompactSupportCarrierData
      (I := I) (K := K) C P omega
  neighborhoodData :
    CoverIndexedCompactSupportNeighborhoodDataInfty
      (I := I) (K := K) C P omega
  measure_eq_volume :
    muBulk = (volume : Measure (Fin (n + 1) → Real))
  transitionSupportData :
    CoverIndexedCompactSupportTransitionSupportData
      (I := I) (K := K) C P omega
  sourceNeighborhood :
    CoverIndexedCompactSupportNeighborhoodDataInfty.BoundaryNeighborhoodSubsetTransitionSource
      (I := I) (K := K) neighborhoodData transitionSupportData
  targetBox :
    CoverIndexedBoundaryTargetBoxData (I := I) (K := K) C P omega
  targetChart_eq :
    ∀ i : {x : M // x ∈ C.boundaryCenters},
      transitionSupportData.targetChart i = targetBox.targetChart i
  targetBox_subset_target :
    ∀ i : {x : M // x ∈ C.boundaryCenters},
      Icc (targetBox.targetLower i) (targetBox.targetUpper i) ⊆
        (extChartAt I (targetBox.targetChart i)).target
  hK : IsCompact K
  hsource :
    ∀ i : {x : M // x ∈ C.boundaryCenters},
      K ⊆ (extChartAt I (targetBox.targetChart i)).source
  homegaSupport : ManifoldForm.support I omega ⊆ K
  coordinateImage_subset_targetBox :
    targetBox.TargetChartCoordinateImageSubsetIccField

namespace CoverIndexedZeroCompactRelativeNaturalInput

variable
    (D :
      CoverIndexedZeroCompactRelativeNaturalInput
        (I := I) (K := K) C P omega muBulk)

/-- The boundary scalar used by the natural constructor: the actual target
zero-boundary integral. -/
def boundaryIntegral : Real :=
  ∫ y, P.coverIndexBoundaryTargetZeroPieceSum D.targetBox.targetChart omega y
    ∂(volume : Measure (Fin n → Real))

/-- Compact global support supplies the zero target-boundary scalar support
field required by the represented Stokes endpoint. -/
theorem boundaryZeroScalarSupportSubsetImageField :
    D.targetBox.BoundaryZeroScalarSupportSubsetImageField :=
  D.targetBox.boundaryZeroScalarSupportSubsetImageField_of_globalManifoldSupport
    (I := I) (K := K) (C := C) (P := P) (ω := omega)
    D.hK D.hsource D.homegaSupport D.coordinateImage_subset_targetBox

/-- Build the relative source-target assembly input, with the boundary scalar
already specialized to `D.boundaryIntegral`. -/
def sourceTargetAssembly
    [IsManifold I 1 M] [BoundaryChartOrientedManifold I M] :
    CoverIndexedZeroBoundaryRelativeSourceAssemblyInput
      (I := I) (K := K) C P omega :=
  CoverIndexedZeroBoundaryRelativeSourceAssemblyInput.ofTargetBoxZeroBoundaryIntegral
    (I := I) (K := K) (C := C) (P := P) (omega := omega)
    D.carrierData D.neighborhoodData D.transitionSupportData D.sourceNeighborhood
    D.targetBox D.targetChart_eq D.targetBox_subset_target
    D.boundaryZeroScalarSupportSubsetImageField
    D.boundaryIntegral rfl

/-- The relative compact-support assembly constructor input generated by the
natural package. -/
def toAssemblyConstructorInput
    [IsManifold I 1 M] [BoundaryChartOrientedManifold I M] :
    CoverIndexedZeroCompactRelativeAssemblyConstructorInput
      (I := I) (K := K) C P omega muBulk where
  carrierData := D.carrierData
  measure_eq_volume := D.measure_eq_volume
  targetBox := D.targetBox
  hK := D.hK
  hsource := D.hsource
  homegaSupport := D.homegaSupport
  coordinateImage_subset_targetBox := D.coordinateImage_subset_targetBox
  targetBox_subset_target := D.targetBox_subset_target
  sourceTargetAssembly := D.sourceTargetAssembly
  globalBoundaryIntegral_eq_integral := by
    rfl

/-- The generated source-target assembly has the same neighborhood data as the
natural input. -/
theorem sourceTargetAssembly_neighborhoodData
    [IsManifold I 1 M] [BoundaryChartOrientedManifold I M] :
    D.sourceTargetAssembly.neighborhoodData = D.neighborhoodData := by
  rfl

/-- The generated source-target assembly has the same transition-support data
as the natural input. -/
theorem sourceTargetAssembly_transitionSupportData
    [IsManifold I 1 M] [BoundaryChartOrientedManifold I M] :
    D.sourceTargetAssembly.transitionSupportData = D.transitionSupportData := by
  rfl

/-- The generated source-target assembly stores the target boundary integral as
its global boundary scalar. -/
theorem sourceTargetAssembly_globalBoundaryIntegral
    [IsManifold I 1 M] [BoundaryChartOrientedManifold I M] :
    D.sourceTargetAssembly.globalBoundaryIntegral = D.boundaryIntegral := by
  rfl

/-- The natural package gives both the represented Stokes equality and the
relative zero source-target assembly equality. -/
theorem representedStokes_and_zeroSourceTargetBulkAssembly
    [IsFiniteMeasureOnCompacts muBulk]
    [IsManifold I ⊤ M] [IsManifold I 1 M]
    [BoundaryChartOrientedManifold I M] :
    (D.carrierData.assignedSelfBulkInputInfty
        (I := I) (K := K) (C := C) (P := P) (ω := omega)
        (μBulk := muBulk) D.neighborhoodData D.measure_eq_volume).globalIntegral =
        D.boundaryIntegral ∧
      D.transitionSupportData.boundaryZeroBulkSetIntegralSum
          (I := I) (K := K) (C := C) (P := P) (omega := omega) =
        D.boundaryIntegral := by
  simpa [toAssemblyConstructorInput, sourceTargetAssembly, boundaryIntegral] using
    (D.toAssemblyConstructorInput.representedStokes_and_zeroSourceTargetBulkAssembly
      (I := I) (K := K) (C := C) (P := P) (omega := omega)
      (muBulk := muBulk))

/-- Integral-facing form of
`representedStokes_and_zeroSourceTargetBulkAssembly`, with no artificial
`globalBoundaryIntegral` argument. -/
theorem representedStokes_and_zeroSourceTargetBulkAssembly_eq_integral
    [IsFiniteMeasureOnCompacts muBulk]
    [IsManifold I ⊤ M] [IsManifold I 1 M]
    [BoundaryChartOrientedManifold I M] :
    (D.carrierData.assignedSelfBulkInputInfty
        (I := I) (K := K) (C := C) (P := P) (ω := omega)
        (μBulk := muBulk) D.neighborhoodData D.measure_eq_volume).globalIntegral =
        ∫ y, P.coverIndexBoundaryTargetZeroPieceSum D.targetBox.targetChart omega y
          ∂(volume : Measure (Fin n → Real)) ∧
      D.transitionSupportData.boundaryZeroBulkSetIntegralSum
          (I := I) (K := K) (C := C) (P := P) (omega := omega) =
        ∫ y, P.coverIndexBoundaryTargetZeroPieceSum D.targetBox.targetChart omega y
          ∂(volume : Measure (Fin n → Real)) := by
  simpa [boundaryIntegral] using
    D.representedStokes_and_zeroSourceTargetBulkAssembly
      (I := I) (K := K) (C := C) (P := P) (omega := omega)
      (muBulk := muBulk)

end CoverIndexedZeroCompactRelativeNaturalInput

end CoverIndexedZeroCompactRelativeNaturalConstructor

end Stokes

end
