import Stokes.Global.CoverIndexedZeroRelativeBoundaryAssemblyInputConstructor
import Stokes.Global.CoverIndexedZeroCompactRelativeAssemblyConstructor

/-!
# Natural compact-support zero theorem via relative sources

This file is the endpoint-facing version of the compact-support zero route
which uses the boundary-compatible relative-source assembly input.

The theorem here is the direct replacement for
`compactSupportRepresentedStokesZeroCompact_of_globalSupport` when working near
manifold boundary charts: it keeps the honest selected-neighborhood containment
field and removes the ambient-open chart-transition-source hypothesis.
-/

noncomputable section

set_option linter.unusedSectionVars false
set_option linter.style.longLine false

open Set MeasureTheory Filter
open scoped BigOperators Manifold Topology

namespace Stokes

section CoverIndexedZeroCompactRelativeNaturalTheorem

universe uH uM

variable {H : Type uH} [TopologicalSpace H]
variable {M : Type uM} [TopologicalSpace M] [ChartedSpace H M]
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) → Real) H}
variable {K : Set M}
variable {omega : ManifoldForm I M n}
variable {C : CompactSupportChartCoverSelection I K}
variable {P : SupportControlledSelectedPartition C}
variable {muBulk : Measure (Fin (n + 1) → Real)}

/-- Compact-support represented Stokes for the zero-extension route, using the
relative-source boundary assembly input.

Compared with `compactSupportRepresentedStokesZeroCompact_of_globalSupport`,
this theorem no longer asks for
`IsOpen (ManifoldForm.chartTransitionSource ...)`.  The source-side datum is
only the selected boundary neighborhood containment in the chart-transition
source; the relative source-neighborhood field and zero source support are
generated by the transition-support package. -/
theorem compactSupportRepresentedStokesZeroCompact_of_globalSupport_relative
    [IsFiniteMeasureOnCompacts muBulk]
    [IsManifold I ⊤ M] [IsManifold I 1 M]
    [BoundaryChartOrientedManifold I M]
    (carrierData :
      CoverIndexedCompactSupportCarrierData
        (I := I) (K := K) C P omega)
    (neighborhoodData :
      CoverIndexedCompactSupportNeighborhoodDataInfty
        (I := I) (K := K) C P omega)
    (measure_eq_volume :
      muBulk = (volume : Measure (Fin (n + 1) → Real)))
    (transitionSupportData :
      CoverIndexedCompactSupportTransitionSupportData
        (I := I) (K := K) C P omega)
    (sourceNeighborhood :
      CoverIndexedCompactSupportNeighborhoodDataInfty.BoundaryNeighborhoodSubsetTransitionSource
        (I := I) (K := K) neighborhoodData transitionSupportData)
    (targetBox :
      CoverIndexedBoundaryTargetBoxData (I := I) (K := K) C P omega)
    (targetChart_eq :
      ∀ i : {x : M // x ∈ C.boundaryCenters},
        transitionSupportData.targetChart i = targetBox.targetChart i)
    (targetBox_subset_target :
      ∀ i : {x : M // x ∈ C.boundaryCenters},
        Icc (targetBox.targetLower i) (targetBox.targetUpper i) ⊆
          (extChartAt I (targetBox.targetChart i)).target)
    (hK : IsCompact K)
    (hsource :
      ∀ i : {x : M // x ∈ C.boundaryCenters},
        K ⊆ (extChartAt I (targetBox.targetChart i)).source)
    (homegaSupport : ManifoldForm.support I omega ⊆ K)
    (coordinateImage_subset_targetBox :
      targetBox.TargetChartCoordinateImageSubsetIccField)
    (globalBoundaryIntegral : Real)
    (globalBoundaryIntegral_eq_integral :
      globalBoundaryIntegral =
        ∫ y, P.coverIndexBoundaryTargetZeroPieceSum targetBox.targetChart omega y
          ∂(volume : Measure (Fin n → Real))) :
    (carrierData.assignedSelfBulkInputInfty
        (I := I) (K := K) (C := C) (P := P) (ω := omega)
        (μBulk := muBulk) neighborhoodData measure_eq_volume).globalIntegral =
        globalBoundaryIntegral ∧
      transitionSupportData.boundaryZeroBulkSetIntegralSum
          (I := I) (K := K) (C := C) (P := P) (omega := omega) =
        globalBoundaryIntegral := by
  have hzeroScalar :
      targetBox.BoundaryZeroScalarSupportSubsetImageField :=
    targetBox.boundaryZeroScalarSupportSubsetImageField_of_globalManifoldSupport
      (I := I) (K := K) (C := C) (P := P) (ω := omega)
      hK hsource homegaSupport coordinateImage_subset_targetBox
  let sourceTargetAssembly :
      CoverIndexedZeroBoundaryRelativeSourceAssemblyInput
        (I := I) (K := K) C P omega :=
    CoverIndexedZeroBoundaryRelativeSourceAssemblyInput.ofTargetBoxZeroBoundaryIntegral
      (I := I) (K := K) (C := C) (P := P) (omega := omega)
      carrierData neighborhoodData transitionSupportData sourceNeighborhood
      targetBox targetChart_eq targetBox_subset_target hzeroScalar
      globalBoundaryIntegral globalBoundaryIntegral_eq_integral
  let D :
      CoverIndexedZeroCompactRelativeAssemblyConstructorInput
        (I := I) (K := K) C P omega muBulk := {
    carrierData := carrierData
    measure_eq_volume := measure_eq_volume
    targetBox := targetBox
    hK := hK
    hsource := hsource
    homegaSupport := homegaSupport
    coordinateImage_subset_targetBox := coordinateImage_subset_targetBox
    targetBox_subset_target := targetBox_subset_target
    sourceTargetAssembly := sourceTargetAssembly
    globalBoundaryIntegral_eq_integral := by
      simpa [sourceTargetAssembly] using globalBoundaryIntegral_eq_integral
  }
  simpa [sourceTargetAssembly, D] using
    D.representedStokes_and_zeroSourceTargetBulkAssembly
      (I := I) (K := K) (C := C) (P := P) (omega := omega)
      (muBulk := muBulk)

end CoverIndexedZeroCompactRelativeNaturalTheorem

end Stokes

end
