import Stokes.Global.CoverIndexedCompactSupportNaturalTheorem
import Stokes.Global.CoverIndexedInteriorCarrierSelection
import Stokes.Global.CoverIndexedBoundaryCarrierSelection
import Stokes.Global.CoverIndexedBoxNeighborhoodSelection

/-!
# Compact-support chart-box data assembly

This file is a thin integration layer for the compact-support represented
Stokes endpoint.  It combines the previously separated carrier-selection and
open-neighborhood packages into the two grouped records used by
`CoverIndexedCompactSupportNaturalTheorem`.

The only analytic residue kept explicit is the legacy
`ContDiffOn Real ⊤` hypothesis for localized interior representatives.  The
natural `C^infty` route is available elsewhere, but this adapter targets the
current endpoint record without adding fake smoothness conversions.
-/

noncomputable section

set_option linter.style.longLine false
set_option linter.unusedSectionVars false

open Set MeasureTheory Filter
open scoped Manifold Topology

namespace Stokes

section CompactSupportBoxDataAssembly

universe uH uM

variable {H : Type uH} [TopologicalSpace H]
variable {M : Type uM} [TopologicalSpace M] [ChartedSpace H M]
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) -> Real) H}
variable {K : Set M}
variable {C : CompactSupportChartCoverSelection I K}
variable {P : SupportControlledSelectedPartition C}
variable {omega : ManifoldForm I M n}

namespace CoverIndexedCompactSupportCarrierData

/-- Assemble compact-support carrier data from the interior and boundary
carrier-selection packages.

This removes the repeated fields:

* coordinate carriers;
* base topological-support containment;
* inverse-chart maps-to-support facts;
* chart-target containment;
* boundary compactness and half-space containment.
-/
def ofCarrierSelections
    (interiorCarrier :
      CoverIndexedInteriorCarrierSelection (I := I) (K := K) C omega)
    (boundaryCarrier :
      CoverIndexedBoundaryCarrierSelection (I := I) (K := K) C omega) :
    CoverIndexedCompactSupportCarrierData
      (I := I) (K := K) C P omega where
  interiorCoordSupport :=
    CoverIndexedInteriorCarrierSelection.coordSupport interiorCarrier
  interior_base_tsupport_subset :=
    CoverIndexedInteriorCarrierSelection.base_tsupport_subset interiorCarrier
  interior_coord_mapsTo_support :=
    CoverIndexedInteriorCarrierSelection.coord_mapsTo_support interiorCarrier
  interior_coord_subset_target :=
    CoverIndexedInteriorCarrierSelection.coord_subset_target interiorCarrier
  boundaryCoordSupport :=
    boundaryCarrier.coordSupport
  boundary_coord_compact :=
    boundaryCarrier.coord_compact
  boundary_coord_subset_halfSpace :=
    boundaryCarrier.coord_subset_halfSpace
  boundary_base_tsupport_subset :=
    boundaryCarrier.base_tsupport_subset
  boundary_coord_mapsTo_support :=
    boundaryCarrier.coord_mapsTo_support
  boundary_coord_subset_target :=
    boundaryCarrier.coord_subset_target

@[simp]
theorem ofCarrierSelections_interiorCoordSupport
    (interiorCarrier :
      CoverIndexedInteriorCarrierSelection (I := I) (K := K) C omega)
    (boundaryCarrier :
      CoverIndexedBoundaryCarrierSelection (I := I) (K := K) C omega) :
    (ofCarrierSelections (I := I) (K := K) (C := C) (P := P)
      (omega := omega) interiorCarrier boundaryCarrier).interiorCoordSupport =
      CoverIndexedInteriorCarrierSelection.coordSupport interiorCarrier :=
  rfl

@[simp]
theorem ofCarrierSelections_boundaryCoordSupport
    (interiorCarrier :
      CoverIndexedInteriorCarrierSelection (I := I) (K := K) C omega)
    (boundaryCarrier :
      CoverIndexedBoundaryCarrierSelection (I := I) (K := K) C omega) :
    (ofCarrierSelections (I := I) (K := K) (C := C) (P := P)
      (omega := omega) interiorCarrier boundaryCarrier).boundaryCoordSupport =
      boundaryCarrier.coordSupport :=
  rfl

end CoverIndexedCompactSupportCarrierData

namespace CoverIndexedCompactSupportNeighborhoodData

/-- Assemble the neighborhood/smoothness data from selected source-box open
neighborhoods.

The source-box geometry fields are generated by the neighborhood packages.  The
remaining explicit inputs are exactly the smoothness facts not contained in
those point-set packages:

* global chartwise smoothness of the original form;
* chartwise smoothness of localized boundary pieces;
* the legacy project-local `ContDiffOn Real ⊤` field for localized interior
  pieces.
-/
def ofBoxNeighborhoods
    (chartwiseSmooth : ManifoldForm.ChartwiseSmooth I omega)
    (localizedChartwiseSmooth :
      forall i : {x : M // x ∈ C.boundaryCenters},
        ManifoldForm.ChartwiseSmooth I
          (P.coverIndexLocalizedForm omega (Sum.inr i)))
    (interiorNeighborhoods :
      CoverIndexedInteriorBoxNeighborhoods (I := I) C)
    (boundaryNeighborhoods :
      CoverIndexedBoundaryBoxNeighborhoods (I := I) C)
    (interior_localized_contDiffOn_top :
      forall i : {x : M // x ∈ C.interiorCenters},
        ContDiffOn Real ⊤
          (ManifoldForm.transitionPullbackInChart I
            (C.interiorChart i.1) (C.interiorChart i.1)
            (P.coverIndexLocalizedForm omega (Sum.inl i)))
          (interiorNeighborhoods.neighborhood i)) :
    CoverIndexedCompactSupportNeighborhoodData
      (I := I) (K := K) C P omega where
  chartwiseSmooth := chartwiseSmooth
  localizedChartwiseSmooth := localizedChartwiseSmooth
  interiorNeighborhood := interiorNeighborhoods.neighborhood
  interior_neighborhood_open :=
    interiorNeighborhoods.neighborhood_open
  interior_Icc_subset_neighborhood :=
    interiorNeighborhoods.Icc_subset_neighborhood
  interior_neighborhood_subset_target :=
    interiorNeighborhoods.neighborhood_subset_target
  interior_localized_contDiffOn_top :=
    interior_localized_contDiffOn_top
  boundaryNeighborhood := boundaryNeighborhoods.neighborhood
  boundary_neighborhood_open :=
    boundaryNeighborhoods.neighborhood_open
  boundary_Icc_subset_neighborhood :=
    boundaryNeighborhoods.Icc_subset_neighborhood
  boundary_neighborhood_subset_target :=
    boundaryNeighborhoods.neighborhood_subset_target

@[simp]
theorem ofBoxNeighborhoods_interiorNeighborhood
    (chartwiseSmooth : ManifoldForm.ChartwiseSmooth I omega)
    (localizedChartwiseSmooth :
      forall i : {x : M // x ∈ C.boundaryCenters},
        ManifoldForm.ChartwiseSmooth I
          (P.coverIndexLocalizedForm omega (Sum.inr i)))
    (interiorNeighborhoods :
      CoverIndexedInteriorBoxNeighborhoods (I := I) C)
    (boundaryNeighborhoods :
      CoverIndexedBoundaryBoxNeighborhoods (I := I) C)
    (interior_localized_contDiffOn_top :
      forall i : {x : M // x ∈ C.interiorCenters},
        ContDiffOn Real ⊤
          (ManifoldForm.transitionPullbackInChart I
            (C.interiorChart i.1) (C.interiorChart i.1)
            (P.coverIndexLocalizedForm omega (Sum.inl i)))
          (interiorNeighborhoods.neighborhood i)) :
    (ofBoxNeighborhoods (I := I) (K := K) (C := C) (P := P)
      (omega := omega) chartwiseSmooth localizedChartwiseSmooth
      interiorNeighborhoods boundaryNeighborhoods
      interior_localized_contDiffOn_top).interiorNeighborhood =
      interiorNeighborhoods.neighborhood :=
  rfl

@[simp]
theorem ofBoxNeighborhoods_boundaryNeighborhood
    (chartwiseSmooth : ManifoldForm.ChartwiseSmooth I omega)
    (localizedChartwiseSmooth :
      forall i : {x : M // x ∈ C.boundaryCenters},
        ManifoldForm.ChartwiseSmooth I
          (P.coverIndexLocalizedForm omega (Sum.inr i)))
    (interiorNeighborhoods :
      CoverIndexedInteriorBoxNeighborhoods (I := I) C)
    (boundaryNeighborhoods :
      CoverIndexedBoundaryBoxNeighborhoods (I := I) C)
    (interior_localized_contDiffOn_top :
      forall i : {x : M // x ∈ C.interiorCenters},
        ContDiffOn Real ⊤
          (ManifoldForm.transitionPullbackInChart I
            (C.interiorChart i.1) (C.interiorChart i.1)
            (P.coverIndexLocalizedForm omega (Sum.inl i)))
          (interiorNeighborhoods.neighborhood i)) :
    (ofBoxNeighborhoods (I := I) (K := K) (C := C) (P := P)
      (omega := omega) chartwiseSmooth localizedChartwiseSmooth
      interiorNeighborhoods boundaryNeighborhoods
      interior_localized_contDiffOn_top).boundaryNeighborhood =
      boundaryNeighborhoods.neighborhood :=
  rfl

end CoverIndexedCompactSupportNeighborhoodData

/-- A compact-support chart-box assembly package for the current represented
endpoint.

This is intentionally just a bundling of already-established mathematical
inputs.  It is useful when the caller has chosen:

* compact coordinate carriers for interior and boundary pieces;
* open neighborhoods around the selected source boxes;
* chartwise smoothness data.

It can then project to the endpoint's `carrierData` and `neighborhoodData`
without repeating all carrier and neighborhood fields.
-/
structure CoverIndexedCompactSupportBoxDataAssembly
    (C : CompactSupportChartCoverSelection I K)
    (P : SupportControlledSelectedPartition C)
    (omega : ManifoldForm I M n) where
  interiorCarrier :
    CoverIndexedInteriorCarrierSelection (I := I) (K := K) C omega
  boundaryCarrier :
    CoverIndexedBoundaryCarrierSelection (I := I) (K := K) C omega
  interiorNeighborhoods :
    CoverIndexedInteriorBoxNeighborhoods (I := I) C
  boundaryNeighborhoods :
    CoverIndexedBoundaryBoxNeighborhoods (I := I) C
  chartwiseSmooth : ManifoldForm.ChartwiseSmooth I omega
  localizedChartwiseSmooth :
    forall i : {x : M // x ∈ C.boundaryCenters},
      ManifoldForm.ChartwiseSmooth I
        (P.coverIndexLocalizedForm omega (Sum.inr i))
  interior_localized_contDiffOn_top :
    forall i : {x : M // x ∈ C.interiorCenters},
      ContDiffOn Real ⊤
        (ManifoldForm.transitionPullbackInChart I
          (C.interiorChart i.1) (C.interiorChart i.1)
          (P.coverIndexLocalizedForm omega (Sum.inl i)))
        (interiorNeighborhoods.neighborhood i)

namespace CoverIndexedCompactSupportBoxDataAssembly

variable
    (D :
      CoverIndexedCompactSupportBoxDataAssembly
        (I := I) (K := K) C P omega)

/-- Carrier data generated from the packaged carrier selections. -/
def carrierData :
    CoverIndexedCompactSupportCarrierData
      (I := I) (K := K) C P omega :=
  CoverIndexedCompactSupportCarrierData.ofCarrierSelections
    (I := I) (K := K) (C := C) (P := P) (omega := omega)
    D.interiorCarrier D.boundaryCarrier

/-- Neighborhood data generated from the packaged source-box neighborhoods. -/
def neighborhoodData :
    CoverIndexedCompactSupportNeighborhoodData
      (I := I) (K := K) C P omega :=
  CoverIndexedCompactSupportNeighborhoodData.ofBoxNeighborhoods
    (I := I) (K := K) (C := C) (P := P) (omega := omega)
    D.chartwiseSmooth D.localizedChartwiseSmooth
    D.interiorNeighborhoods D.boundaryNeighborhoods
    D.interior_localized_contDiffOn_top

/-- Compact-support local-data package generated by the assembly. -/
def localDataFromCompactSupport :
    CoverIndexedLocalDataFromCompactSupport
      (I := I) (K := K) C P omega :=
  (D.carrierData).localDataFromCompactSupport D.neighborhoodData

/-- Endpoint assigned-box local data generated by the assembly. -/
def assignedBoxLocalData
    [IsManifold I ⊤ M] :
    CoverIndexedAssignedBoxLocalData (I := I) (K := K) C P omega :=
  (D.carrierData).assignedBoxLocalData D.neighborhoodData

@[simp]
theorem carrierData_interiorCoordSupport :
    D.carrierData.interiorCoordSupport =
      CoverIndexedInteriorCarrierSelection.coordSupport D.interiorCarrier :=
  rfl

@[simp]
theorem carrierData_boundaryCoordSupport :
    D.carrierData.boundaryCoordSupport =
      D.boundaryCarrier.coordSupport :=
  rfl

@[simp]
theorem neighborhoodData_interiorNeighborhood :
    D.neighborhoodData.interiorNeighborhood =
      D.interiorNeighborhoods.neighborhood :=
  rfl

@[simp]
theorem neighborhoodData_boundaryNeighborhood :
    D.neighborhoodData.boundaryNeighborhood =
      D.boundaryNeighborhoods.neighborhood :=
  rfl

end CoverIndexedCompactSupportBoxDataAssembly

end CompactSupportBoxDataAssembly

end Stokes

end
