import Stokes.Global.CoverIndexedZeroCompactChartTransitionShrink
import Stokes.BoundaryChart.SourceShrinkMapsToAuto

/-!
# Continuity shrink for compact zero endpoints

This file isolates the topological step behind the remaining compact-support
geometry: once a source neighborhood `U` is chosen and the target set `V` is
open, continuity on `U` makes `U ∩ f ⁻¹' V` an open shrink of the source.

It also records how the existing boundary source-shrink API fits into this
picture.  `BoundaryChartSourceShrinkMapsToData` controls the lower-zero
boundary face via `boundaryChartTransition`; it is exactly the right input for
boundary change of variables, but it is not the whole ambient half-space
`MapsTo` required by the compact zero endpoint.  The whole-box route still
needs the ambient `ManifoldForm.chartTransition` on `halfSpaceSupportBox`.
-/

noncomputable section

set_option linter.unusedSectionVars false
set_option linter.style.longLine false

open Set MeasureTheory Filter
open scoped BigOperators Manifold Topology

namespace Stokes

section GeneralContinuityShrink

universe u v

variable {X : Type u} {Y : Type v}
variable [TopologicalSpace X] [TopologicalSpace Y]
variable {f : X -> Y} {K U : Set X} {V : Set Y}

/-- The basic relative-open preimage shrink supplied by continuity on an open
source set. -/
theorem isOpen_inter_preimage_of_continuousOn
    (hUopen : IsOpen U) (hf : ContinuousOn f U) (hVopen : IsOpen V) :
    IsOpen (U ∩ f ⁻¹' V) :=
  hf.isOpen_inter_preimage hUopen hVopen

/-- If the image of a carrier lies in the target open set, then the carrier is
contained in the preimage shrink.  Compactness is not used here; compactness
enters earlier when one chooses finitely many source/target boxes. -/
theorem subset_inter_preimage_of_subset_image_subset
    (hKU : K ⊆ U) (himage : f '' K ⊆ V) :
    K ⊆ U ∩ f ⁻¹' V := by
  intro x hx
  exact ⟨hKU hx, himage ⟨x, hx, rfl⟩⟩

/-- The canonical open shrink generated by continuity and image containment. -/
theorem exists_open_shrink_of_continuousOn_image_subset
    (hUopen : IsOpen U) (hf : ContinuousOn f U) (hVopen : IsOpen V)
    (hKU : K ⊆ U) (himage : f '' K ⊆ V) :
    ∃ W : Set X, IsOpen W ∧ K ⊆ W ∧ W ⊆ U ∩ f ⁻¹' V := by
  refine ⟨U ∩ f ⁻¹' V, ?_, ?_, subset_rfl⟩
  · exact isOpen_inter_preimage_of_continuousOn hUopen hf hVopen
  · exact subset_inter_preimage_of_subset_image_subset hKU himage

/-- Compact-carrier spelling of `exists_open_shrink_of_continuousOn_image_subset`.
The compactness hypothesis is intentionally unused by the proof: it belongs to
the preceding finite-box selection step, while the shrink itself is pure
continuity. -/
theorem exists_open_shrink_of_isCompact_continuousOn_image_subset
    (_hK : IsCompact K)
    (hUopen : IsOpen U) (hf : ContinuousOn f U) (hVopen : IsOpen V)
    (hKU : K ⊆ U) (himage : f '' K ⊆ V) :
    ∃ W : Set X, IsOpen W ∧ K ⊆ W ∧ W ⊆ U ∩ f ⁻¹' V :=
  exists_open_shrink_of_continuousOn_image_subset hUopen hf hVopen hKU himage

end GeneralContinuityShrink

section CoverIndexedContinuityShrink

universe uH uM

variable {H : Type uH} [TopologicalSpace H]
variable {M : Type uM} [TopologicalSpace M] [ChartedSpace H M]
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) -> Real) H}
variable {K : Set M}
variable {C : CompactSupportChartCoverSelection I K}
variable {P : SupportControlledSelectedPartition C}
variable {omega : ManifoldForm I M n}

namespace CoverIndexedBoundaryTransitionBoxNeighborhoods

variable {targetChart : {x : M // x ∈ C.boundaryCenters} -> M}

/-- Per-boundary-index open preimage shrink from continuity on the chosen
transition neighborhood and image containment for the selected source box. -/
def preimageChartBoxOpenNeighborhoodsOfContinuousOnImageSubset
    (nbrs :
      CoverIndexedBoundaryTransitionBoxNeighborhoods
        (I := I) (K := K) C targetChart)
    (targetOpen :
      {x : M // x ∈ C.boundaryCenters} -> Set (Fin (n + 1) -> Real))
    (hcont :
      ∀ i : {x : M // x ∈ C.boundaryCenters},
        ContinuousOn
          (ManifoldForm.chartTransition I
            (C.boundaryChart i.1) (targetChart i))
          (nbrs.boundaryNeighborhood i))
    (hVopen :
      ∀ i : {x : M // x ∈ C.boundaryCenters},
        IsOpen (targetOpen i))
    (himage :
      ∀ i : {x : M // x ∈ C.boundaryCenters},
        (ManifoldForm.chartTransition I
          (C.boundaryChart i.1) (targetChart i)) ''
            Icc (C.boundaryLower i.1) (C.boundaryUpper i.1) ⊆
          targetOpen i)
    (i : {x : M // x ∈ C.boundaryCenters}) :
    ChartBoxOpenNeighborhood
      ((ManifoldForm.chartTransition I
        (C.boundaryChart i.1) (targetChart i)) ⁻¹'
        targetOpen i)
      (C.boundaryLower i.1) (C.boundaryUpper i.1) where
  neighborhood :=
    nbrs.boundaryNeighborhood i ∩
      (ManifoldForm.chartTransition I
        (C.boundaryChart i.1) (targetChart i)) ⁻¹'
        targetOpen i
  isOpen_neighborhood :=
    isOpen_inter_preimage_of_continuousOn
      (nbrs.boundary_neighborhood_open i) (hcont i) (hVopen i)
  Icc_subset_neighborhood := by
    intro y hy
    exact
      ⟨nbrs.boundary_Icc_subset_neighborhood i hy,
        himage i ⟨y, hy, rfl⟩⟩
  neighborhood_subset_target := by
    intro y hy
    exact hy.2

@[simp]
theorem preimageChartBoxOpenNeighborhoodsOfContinuousOnImageSubset_neighborhood
    (nbrs :
      CoverIndexedBoundaryTransitionBoxNeighborhoods
        (I := I) (K := K) C targetChart)
    (targetOpen :
      {x : M // x ∈ C.boundaryCenters} -> Set (Fin (n + 1) -> Real))
    (hcont :
      ∀ i : {x : M // x ∈ C.boundaryCenters},
        ContinuousOn
          (ManifoldForm.chartTransition I
            (C.boundaryChart i.1) (targetChart i))
          (nbrs.boundaryNeighborhood i))
    (hVopen :
      ∀ i : {x : M // x ∈ C.boundaryCenters},
        IsOpen (targetOpen i))
    (himage :
      ∀ i : {x : M // x ∈ C.boundaryCenters},
        (ManifoldForm.chartTransition I
          (C.boundaryChart i.1) (targetChart i)) ''
            Icc (C.boundaryLower i.1) (C.boundaryUpper i.1) ⊆
          targetOpen i)
    (i : {x : M // x ∈ C.boundaryCenters}) :
    (preimageChartBoxOpenNeighborhoodsOfContinuousOnImageSubset
      (I := I) (K := K) (C := C) (targetChart := targetChart)
      nbrs targetOpen hcont hVopen himage i).neighborhood =
      nbrs.boundaryNeighborhood i ∩
        (ManifoldForm.chartTransition I
          (C.boundaryChart i.1) (targetChart i)) ⁻¹'
          targetOpen i :=
  rfl

/-- Continuity/image-containment version of the whole half-space source-box
`MapsTo` field used by compact zero endpoints. -/
theorem chartTransition_mapsTo_halfSpaceSupportBox_of_continuousOn_image_subset
    (nbrs :
      CoverIndexedBoundaryTransitionBoxNeighborhoods
        (I := I) (K := K) C targetChart)
    (targetOpen :
      {x : M // x ∈ C.boundaryCenters} -> Set (Fin (n + 1) -> Real))
    (targetLower targetUpper :
      {x : M // x ∈ C.boundaryCenters} -> Fin (n + 1) -> Real)
    (hcont :
      ∀ i : {x : M // x ∈ C.boundaryCenters},
        ContinuousOn
          (ManifoldForm.chartTransition I
            (C.boundaryChart i.1) (targetChart i))
          (nbrs.boundaryNeighborhood i))
    (hVopen :
      ∀ i : {x : M // x ∈ C.boundaryCenters},
        IsOpen (targetOpen i))
    (hVsubset :
      ∀ i : {x : M // x ∈ C.boundaryCenters},
        targetOpen i ⊆ Icc (targetLower i) (targetUpper i))
    (himage :
      ∀ i : {x : M // x ∈ C.boundaryCenters},
        (ManifoldForm.chartTransition I
          (C.boundaryChart i.1) (targetChart i)) ''
            Icc (C.boundaryLower i.1) (C.boundaryUpper i.1) ⊆
          targetOpen i) :
    ∀ i : {x : M // x ∈ C.boundaryCenters},
      MapsTo
        (ManifoldForm.chartTransition I
          (C.boundaryChart i.1) (targetChart i))
        (halfSpaceSupportBox (C.boundaryLower i.1)
          (C.boundaryUpper i.1))
        (Icc (targetLower i) (targetUpper i)) :=
  chartTransition_mapsTo_halfSpaceSupportBox_of_chartBoxOpenNeighborhoods
    (I := I) (K := K) (C := C) (targetChart := targetChart)
    targetOpen targetLower targetUpper hVsubset
    (preimageChartBoxOpenNeighborhoodsOfContinuousOnImageSubset
      (I := I) (K := K) (C := C) (targetChart := targetChart)
      nbrs targetOpen hcont hVopen himage)

end CoverIndexedBoundaryTransitionBoxNeighborhoods

namespace CoverIndexedBoundaryTargetBoxData

variable
  (D : CoverIndexedBoundaryTargetBoxData (I := I) (K := K) C P omega)

/-- Direct target-zero support field from continuity shrink and image
containment of the selected source `Icc` into target open boxes. -/
theorem targetInChartZero_tsupport_subset_Icc_of_continuousOn_image_subset
    (homegaSupport : ManifoldForm.support I omega ⊆ K)
    (nbrs :
      CoverIndexedBoundaryTransitionBoxNeighborhoods
        (I := I) (K := K) C D.targetChart)
    (targetOpen :
      {x : M // x ∈ C.boundaryCenters} -> Set (Fin (n + 1) -> Real))
    (hcont :
      ∀ i : {x : M // x ∈ C.boundaryCenters},
        ContinuousOn
          (ManifoldForm.chartTransition I
            (C.boundaryChart i.1) (D.targetChart i))
          (nbrs.boundaryNeighborhood i))
    (hVopen :
      ∀ i : {x : M // x ∈ C.boundaryCenters},
        IsOpen (targetOpen i))
    (hVsubset :
      ∀ i : {x : M // x ∈ C.boundaryCenters},
        targetOpen i ⊆ Icc (D.targetLower i) (D.targetUpper i))
    (himage :
      ∀ i : {x : M // x ∈ C.boundaryCenters},
        (ManifoldForm.chartTransition I
          (C.boundaryChart i.1) (D.targetChart i)) ''
            Icc (C.boundaryLower i.1) (C.boundaryUpper i.1) ⊆
          targetOpen i) :
    D.TargetInChartZeroTSupportSubsetIccField :=
  D.targetInChartZero_tsupport_subset_Icc_of_chartTransition_mapsTo
    (I := I) (K := K) (C := C) (P := P) (omega := omega)
    homegaSupport
    (CoverIndexedBoundaryTransitionBoxNeighborhoods.chartTransition_mapsTo_halfSpaceSupportBox_of_continuousOn_image_subset
      (I := I) (K := K) (C := C) (targetChart := D.targetChart)
      nbrs targetOpen D.targetLower D.targetUpper hcont hVopen hVsubset himage)

end CoverIndexedBoundaryTargetBoxData

end CoverIndexedContinuityShrink

section SourceShrinkComparison

universe uM

variable {H : Type uM} [TopologicalSpace H]
variable {M : Type*} [TopologicalSpace M] [ChartedSpace H M]
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) -> Real) H}
variable {x0 x1 : M}
variable {a b c d : Fin (n + 1) -> Real}
variable {u : Fin n -> Real}

namespace BoundaryChartSourceShrinkMapsToData

/-- Existing source-shrink data gives ambient target-box containment only after
re-embedding the tangential boundary transition into the boundary hyperplane. -/
theorem mapsTo_boundaryInclusion_selectedTargetIcc
    (D : BoundaryChartSourceShrinkMapsToData I x0 x1 a b c d u)
    (hc0 : c 0 = 0) (hle : c ≤ d) :
    MapsTo
      (fun y : Fin n -> Real =>
        boundaryInclusion n (boundaryChartTransition I x0 x1 y))
      (lowerZeroFaceDomain D.sourceLowerCorner D.sourceUpperCorner)
      (Icc c d) := by
  intro y hy
  exact
    boundaryInclusion_mem_Icc_of_mem_lowerZeroFaceDomain
      (n := n) (a := c) (b := d) hc0 hle
      (D.mapsTo_selectedTarget hy)

/-- If the ambient chart transition is known to preserve the boundary face on
the shrunken source, then source-shrink data gives an ambient `MapsTo` statement
on that boundary face.  This still has domain `lowerZeroFaceDomain`, not the
whole `halfSpaceSupportBox`. -/
theorem mapsTo_ambientBoundaryFaceIcc_of_preservesBoundary
    (D : BoundaryChartSourceShrinkMapsToData I x0 x1 a b c d u)
    (hc0 : c 0 = 0) (hle : c ≤ d)
    (hpres :
      ∀ y ∈ lowerZeroFaceDomain D.sourceLowerCorner D.sourceUpperCorner,
        boundaryChartTransitionPreservesBoundaryAt I x0 x1 y) :
    MapsTo
      (fun y : Fin n -> Real =>
        ManifoldForm.chartTransition I x0 x1 (boundaryInclusion n y))
      (lowerZeroFaceDomain D.sourceLowerCorner D.sourceUpperCorner)
      (Icc c d) := by
  intro y hy
  have hmem :
      boundaryInclusion n (boundaryChartTransition I x0 x1 y) ∈ Icc c d :=
    D.mapsTo_boundaryInclusion_selectedTargetIcc hc0 hle hy
  change ManifoldForm.chartTransition I x0 x1 (boundaryInclusion n y) ∈ Icc c d
  rw [hpres y hy]
  exact hmem

end BoundaryChartSourceShrinkMapsToData

end SourceShrinkComparison

end Stokes

end
