import Stokes.Global.CoverIndexedZeroCompactRefinedSmoothness
import Stokes.Global.CoverIndexedZeroCompactSmoothBoxRefinement

/-!
# Natural smoothness constructors for collar-generated refined boxes

This module is the smoothness compression layer for the collar/refinement route.
The refined local Stokes package still stores transition-coordinate coefficient
smoothness, but callers should only have to prove smoothness of the scalar
coefficient in the source chart.  The constructors below perform that transport
using the source/target chart-overlap neighborhood field.

For coefficients literally generated by `BoundarySmoothBoxRefinement.coefficient`
we also record the honest smooth-partition product smoothness available from
mathlib, at the `C^\infty` level `((top : ENat) : WithTop ENat)`.  The current
refined local-Stokes field asks for the stronger project-local `top`, so the
field constructor keeps a source-chart `ContDiffOn Real top` coefficient
hypothesis as the remaining input.
-/

noncomputable section

set_option linter.style.longLine false
set_option linter.unusedSectionVars false

open Set MeasureTheory Filter
open scoped BigOperators Manifold Topology

namespace Stokes

section GeneratedCoefficientFields

universe u w b

variable {H : Type u} [TopologicalSpace H]
variable {M : Type w} [TopologicalSpace M] [ChartedSpace H M]
variable {BoundaryPiece : Type b}
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) -> Real) H}
variable {K : Set M}
variable {omega : ManifoldForm I M n}
variable {C : CompactSupportChartCoverSelection I K}
variable {P : SupportControlledSelectedPartition C}
variable
  {D :
    CoverIndexedBoundaryBoxRefinedPartition
      (I := I) (K := K) C P omega BoundaryPiece}
  {U :
    CoverIndexedBoundaryIndex (I := I) C -> BoundaryPiece ->
      Set (Fin (n + 1) -> Real)}

namespace CoverIndexedBoundaryBoxRefinedSmoothnessFields

/--
Build refined smoothness fields from generated/source-chart coefficient
smoothness.

This is the intended natural input shape for the refined collar route:
chartwise smoothness of the base form, target/overlap containment for each
smoothness neighborhood, and source-chart smoothness of the refined scalar
coefficient.  The transition-coordinate coefficient field is generated by the
existing overlap bridge.
-/
def ofGeneratedCoefficientInChart
    [IsManifold I ⊤ M]
    (homega : ManifoldForm.ChartwiseSmooth I omega)
    (hUtarget :
      forall i q, q ∈ D.boundaryPieces i ->
        U i q ⊆ (extChartAt I (D.sourceChart i q)).target)
    (hUoverlap :
      forall i q, q ∈ D.boundaryPieces i ->
        U i q ⊆
          ManifoldForm.chartOverlap I (D.sourceChart i q) (D.targetChart i q))
    (hcoeffInChart :
      forall i q, q ∈ D.boundaryPieces i ->
        ContDiffOn Real ⊤
          (ManifoldForm.coefficientInChart I
            (D.sourceChart i q) (D.coefficient i q))
          (U i q)) :
    CoverIndexedBoundaryBoxRefinedSmoothnessFields D U :=
  ofCoefficientInChart
    (I := I) (K := K) (omega := omega) (C := C) (P := P)
    (D := D) (U := U)
    homega hUtarget hUoverlap hcoeffInChart

/--
Same constructor, named for smooth box refinements.

The equality hypothesis records that the refined partition really uses the
coefficient produced by `BoundarySmoothBoxRefinement.coefficient`.  The
remaining analytic input is still the minimal source-chart
`ContDiffOn Real top` statement for that generated coefficient; the constructor
removes any need to mention `transitionCoefficientInChart`.
-/
def ofSmoothRefinementCoefficientInChart
    [DecidableEq BoundaryPiece] [IsManifold I ⊤ M]
    (R : BoundarySmoothBoxRefinement (I := I) (K := K) C P BoundaryPiece)
    (homega : ManifoldForm.ChartwiseSmooth I omega)
    (hUtarget :
      forall i q, q ∈ D.boundaryPieces i ->
        U i q ⊆ (extChartAt I (D.sourceChart i q)).target)
    (hUoverlap :
      forall i q, q ∈ D.boundaryPieces i ->
        U i q ⊆
          ManifoldForm.chartOverlap I (D.sourceChart i q) (D.targetChart i q))
    (hcoefficient :
      forall i q, q ∈ D.boundaryPieces i ->
        D.coefficient i q = R.coefficient i q)
    (hcoeffInChart :
      forall i q, q ∈ D.boundaryPieces i ->
        ContDiffOn Real ⊤
          (ManifoldForm.coefficientInChart I
            (D.sourceChart i q) (R.coefficient i q))
          (U i q)) :
    CoverIndexedBoundaryBoxRefinedSmoothnessFields D U :=
  ofGeneratedCoefficientInChart
    (I := I) (K := K) (omega := omega) (C := C) (P := P)
    (D := D) (U := U)
    homega hUtarget hUoverlap
    (by
      intro i q hq
      rw [hcoefficient i q hq]
      exact hcoeffInChart i q hq)

end CoverIndexedBoundaryBoxRefinedSmoothnessFields

end GeneratedCoefficientFields

section SmoothRefinementCoefficientFacts

universe u w b

variable {H : Type u} [TopologicalSpace H]
variable {M : Type w} [TopologicalSpace M] [ChartedSpace H M]
variable {BoundaryPiece : Type b} [DecidableEq BoundaryPiece]
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) -> Real) H}
variable {K : Set M}
variable {C : CompactSupportChartCoverSelection I K}
variable {P : SupportControlledSelectedPartition C}

namespace BoundarySmoothBoxRefinement

variable
  (R : BoundarySmoothBoxRefinement
    (I := I) (K := K) C P BoundaryPiece)

/--
Source-chart spelling of a generated refined coefficient.

For a genuine refined piece, the chart coefficient is the product of the source
chart coefficients of the selected boundary partition term and the smooth
subpartition term.
-/
theorem coefficientInChart_eq_mul_of_mem
    (i : CoverIndexedBoundaryIndex (I := I) C) {q : BoundaryPiece}
    (hq : q ∈ R.boundaryPieces i) (x0 : M) :
    ManifoldForm.coefficientInChart I x0 (R.coefficient i q) =
      fun y =>
        ManifoldForm.coefficientInChart I x0 (P.partition (Sum.inr i)) y *
          ManifoldForm.coefficientInChart I x0
            (R.subpartition i ⟨q, hq⟩) y := by
  funext y
  simp [ManifoldForm.coefficientInChart, R.coefficient_of_mem i hq]

/--
Honest `C^\infty` source-chart smoothness of a generated refined coefficient.

This is the smoothness level supplied directly by mathlib's smooth partition of
unity API for both factors.  The stronger project-local `top` hypothesis still
has to be supplied when constructing
`CoverIndexedBoundaryBoxRefinedSmoothnessFields`.
-/
theorem contDiffOn_infty_coefficientInChart
    [IsManifold I ⊤ M]
    (i : CoverIndexedBoundaryIndex (I := I) C) {q : BoundaryPiece}
    (hq : q ∈ R.boundaryPieces i) (x0 : M)
    {U : Set (Fin (n + 1) -> Real)}
    (hUtarget : U ⊆ (extChartAt I x0).target) :
    ContDiffOn Real ((⊤ : ℕ∞) : WithTop ℕ∞)
      (ManifoldForm.coefficientInChart I x0 (R.coefficient i q)) U := by
  have hbase :
      ContDiffOn Real ((⊤ : ℕ∞) : WithTop ℕ∞)
        (ManifoldForm.coefficientInChart I x0 (P.partition (Sum.inr i))) U :=
    ManifoldForm.contDiffOn_coefficientInChart_smoothPartition_indexed
      (I := I) P.partition x0 (Sum.inr i) hUtarget
  have hsub :
      ContDiffOn Real ((⊤ : ℕ∞) : WithTop ℕ∞)
        (ManifoldForm.coefficientInChart I x0 (R.subpartition i ⟨q, hq⟩)) U :=
    ManifoldForm.contDiffOn_coefficientInChart_smoothPartition_indexed
      (I := I) (R.subpartition i) x0 ⟨q, hq⟩ hUtarget
  simpa [R.coefficientInChart_eq_mul_of_mem i hq x0] using hbase.mul hsub

end BoundarySmoothBoxRefinement

end SmoothRefinementCoefficientFacts

end Stokes

end
