import Stokes.Global.CoverIndexedLocalizedRefinedRegularity
import Stokes.Global.CoverIndexedZeroCompactFromCollarSmoothness

/-!
# Intrinsic regularity fields for generated refined boundary boxes

This module is a focused bridge for the intrinsic compact-support route.  It
does not introduce a new public certificate.  Instead it shows how the existing
smooth-refinement coefficient lemma supplies the open-box and closed-box
coefficient smoothness hypotheses required by the current
`HalfSpaceBoxInteriorStokesFields` constructors.

The honest remaining inputs are the structural identifications saying that the
box-refined partition really uses the finite pieces and coefficients generated
by the `BoundarySmoothBoxRefinement`.
-/

noncomputable section

set_option linter.unusedSectionVars false
set_option linter.style.longLine false

open Set MeasureTheory Filter
open scoped BigOperators Manifold Topology

namespace Stokes

section IntrinsicRegularityFields

universe u w b

variable {H : Type u} [TopologicalSpace H]
variable {M : Type w} [TopologicalSpace M] [ChartedSpace H M]
variable {BoundaryPiece : Type b} [DecidableEq BoundaryPiece]
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) -> Real) H}
variable {K : Set M}
variable {omega : ManifoldForm I M n}
variable {C : CompactSupportChartCoverSelection I K}
variable {P : SupportControlledSelectedPartition C}

namespace CoverIndexedBoundaryBoxRefinedPartition

variable
  (D :
    CoverIndexedBoundaryBoxRefinedPartition
      (I := I) (K := K) C P omega BoundaryPiece)
  (R : BoundarySmoothBoxRefinement (I := I) (K := K) C P BoundaryPiece)

/--
For a generated smooth refinement, source-chart smoothness of the scalar
coefficient is available on the coordinate open box.

The only structural input is that every piece of the box-refined partition is
also a piece of the smooth refinement, and that the two coefficient functions
agree on those pieces.
-/
theorem contDiffOn_openBox_coefficientInChart_of_smoothRefinement
    [IsManifold I ⊤ M]
    (hpiece :
      forall i q, q ∈ D.boundaryPieces i -> q ∈ R.boundaryPieces i)
    (hcoefficient :
      forall i q, q ∈ D.boundaryPieces i ->
        D.coefficient i q = R.coefficient i q)
    (i : CoverIndexedBoundaryIndex (I := I) C) (q : BoundaryPiece)
    (hq : q ∈ D.boundaryPieces i) :
    ContDiffOn Real ((⊤ : ℕ∞) : WithTop ℕ∞)
      (ManifoldForm.coefficientInChart I
        (D.sourceChart i q) (D.coefficient i q))
      (halfSpaceBoxOpenInterior (D.lower i q) (D.upper i q)) := by
  have htarget :
      halfSpaceBoxOpenInterior (D.lower i q) (D.upper i q) ⊆
        (extChartAt I (D.sourceChart i q)).target := by
    exact
      (pi_Ioo_subset_Icc (D.lower i q) (D.upper i q)).trans
        ((D.Icc_subset_boundaryChartDomain i q hq).trans
          (boundaryChartDomain_subset_target I
            (D.sourceChart i q) (D.targetChart i q)))
  rw [hcoefficient i q hq]
  exact
    R.contDiffOn_infty_coefficientInChart i (hpiece i q hq)
      (D.sourceChart i q) htarget

/--
For a generated smooth refinement, source-chart smoothness of the scalar
coefficient is available on the closed coordinate box as soon as the closed box
lies in the stored boundary chart domain.

This is the key closed-box regularity bridge: it is strong enough to feed
`closedBoxRegularityFields_of_coefficientInChart`, hence the fderiv-continuity
and divergence-integrability fields inside `HalfSpaceBoxInteriorStokesFields`.
-/
theorem contDiffOn_Icc_coefficientInChart_of_smoothRefinement
    [IsManifold I ⊤ M]
    (hpiece :
      forall i q, q ∈ D.boundaryPieces i -> q ∈ R.boundaryPieces i)
    (hcoefficient :
      forall i q, q ∈ D.boundaryPieces i ->
        D.coefficient i q = R.coefficient i q)
    (i : CoverIndexedBoundaryIndex (I := I) C) (q : BoundaryPiece)
    (hq : q ∈ D.boundaryPieces i) :
    ContDiffOn Real ((⊤ : ℕ∞) : WithTop ℕ∞)
      (ManifoldForm.coefficientInChart I
        (D.sourceChart i q) (D.coefficient i q))
      (Icc (D.lower i q) (D.upper i q)) := by
  have htarget :
      Icc (D.lower i q) (D.upper i q) ⊆
        (extChartAt I (D.sourceChart i q)).target := by
    exact
      (D.Icc_subset_boundaryChartDomain i q hq).trans
        (boundaryChartDomain_subset_target I
          (D.sourceChart i q) (D.targetChart i q))
  rw [hcoefficient i q hq]
  exact
    R.contDiffOn_infty_coefficientInChart i (hpiece i q hq)
      (D.sourceChart i q) htarget

/--
Per-refined-box interior Stokes fields generated by chartwise smoothness and a
smooth box refinement.

This theorem is intentionally not a new certificate layer.  It reuses the
existing constructors:

* `BoundarySmoothBoxRefinement.contDiffOn_infty_coefficientInChart` supplies
  coefficient smoothness on both `halfSpaceBoxOpenInterior` and `Icc`;
* `interiorFields_of_chartwiseSmooth_coefficientInChart_closedBox` turns that
  into the `HalfSpaceBoxInteriorStokesFields`, including the closed-box signed
  coefficient continuity and divergence integrability.

The remaining hypotheses are exact structural blockers for full automation:
the refined partition `D` must be known to use the same pieces and coefficients
as the smooth refinement `R`.
-/
def interiorFieldsOnOpenBox_of_smoothRefinement_chartwiseSmooth
    [IsManifold I ⊤ M]
    (homega : ManifoldForm.ChartwiseSmooth I omega)
    (hpiece :
      forall i q, q ∈ D.boundaryPieces i -> q ∈ R.boundaryPieces i)
    (hcoefficient :
      forall i q, q ∈ D.boundaryPieces i ->
        D.coefficient i q = R.coefficient i q) :
    forall i, i ∈ (Finset.univ : Finset (CoverIndexedBoundaryIndex (I := I) C)) ->
      forall q, q ∈ D.boundaryPieces i ->
        HalfSpaceBoxInteriorStokesFields
          (ManifoldForm.transitionPullbackInChart I
            (D.sourceChart i q) (D.targetChart i q) (D.localizedForm i q))
          (D.lower i q) (D.upper i q) := by
  refine
    D.interiorFields_of_chartwiseSmooth_coefficientInChart_closedBox
      (U := fun i q => halfSpaceBoxOpenInterior (D.lower i q) (D.upper i q))
      homega ?_ ?_ ?_ ?_ ?_ ?_
  · intro i _hi q _hq
    exact isOpen_pi_Ioo (D.lower i q) (D.upper i q)
  · intro i _hi q _hq
    exact subset_rfl
  · intro i q hq
    exact
      (pi_Ioo_subset_Icc (D.lower i q) (D.upper i q)).trans
        ((D.Icc_subset_boundaryChartDomain i q hq).trans
          (boundaryChartDomain_subset_target I
            (D.sourceChart i q) (D.targetChart i q)))
  · intro i q hq
    exact
      (pi_Ioo_subset_Icc (D.lower i q) (D.upper i q)).trans
        ((D.Icc_subset_boundaryChartDomain i q hq).trans
          (boundaryChartDomain_subset_overlap I
            (D.sourceChart i q) (D.targetChart i q)))
  · intro i q hq
    exact
      D.contDiffOn_openBox_coefficientInChart_of_smoothRefinement R
        hpiece hcoefficient i q hq
  · intro i q hq
    exact
      D.contDiffOn_Icc_coefficientInChart_of_smoothRefinement R
        hpiece hcoefficient i q hq

end CoverIndexedBoundaryBoxRefinedPartition

end IntrinsicRegularityFields

end Stokes

end
