import Stokes.Global.CoverIndexedZeroCompactRepresentedStokesIntrinsic
import Stokes.Global.CoverIndexedLocalizedRefinedLocalStokes

/-!
# Intrinsic endpoint constructors

This file connects the canonical intrinsic selected boundary finite cover to
the minimal localized endpoint algebra.

The constructor here deliberately stays below the final intrinsic theorem: it
takes a smooth refinement over the canonical finite cover and builds

* the minimal `CoverIndexedBoundaryLocalizedRefinedPartition`, whose local
  terms are the project-local bulk and boundary integrals of the localized
  refined form; and
* the matching `LocalStokesData` package.

The only support facts left as inputs are the per-box ordinary and zero
localized support statements required by the existing `LocalStokesData`
record.  The chart-transition-source field is derived from the selected
boundary closed-box containment.
-/

noncomputable section

set_option linter.unusedSectionVars false
set_option linter.style.longLine false

open Set MeasureTheory Filter
open scoped BigOperators Manifold Topology

namespace Stokes

section IntrinsicEndpointConstructor

universe uH uM

variable {H : Type uH} [TopologicalSpace H]
variable {M : Type uM} [TopologicalSpace M] [ChartedSpace H M]
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) → Real) H}
variable {K : Set M}
variable {ω : ManifoldForm I M n}
variable [FiniteDimensional Real (Fin (n + 1) → Real)]
variable [IsManifold I ⊤ M] [T2Space M] [SigmaCompactSpace M]

namespace CoverIndexedZeroCompactRepresentedStokesIntrinsicInput

variable
    (X :
      CoverIndexedZeroCompactRepresentedStokesIntrinsicInput
        (I := I) (ω := ω) K)

/-- Source/target chart used by the intrinsic self-chart endpoint for a
flattened selected boundary finite-cover piece. -/
def selectedBoundarySelfChart
    (q : X.selectedBoundaryPiece (I := I) (K := K) (ω := ω)) : M :=
  (X.selectedCover (I := I) (K := K) (ω := ω)).boundaryChart q.1.1

/-- Lower corner of a flattened selected boundary finite-cover piece. -/
def selectedBoundaryFiniteCoverLower
    (q : X.selectedBoundaryPiece (I := I) (K := K) (ω := ω)) :
    Fin (n + 1) → Real :=
  (X.selectedBoundaryFiniteCover (I := I) (K := K) (ω := ω)).lowerCorner q.1 q.2

/-- Upper corner of a flattened selected boundary finite-cover piece. -/
def selectedBoundaryFiniteCoverUpper
    (q : X.selectedBoundaryPiece (I := I) (K := K) (ω := ω)) :
    Fin (n + 1) → Real :=
  (X.selectedBoundaryFiniteCover (I := I) (K := K) (ω := ω)).upperCorner q.1 q.2

/-- Localized form attached to a smooth-refined intrinsic boundary box. -/
def selectedBoundaryLocalizedForm
    [DecidableEq (X.selectedBoundaryPiece (I := I) (K := K) (ω := ω))]
    (S :
      BoundarySmoothBoxRefinement
        (I := I) (K := K)
        (X.selectedCover (I := I) (K := K) (ω := ω))
        (X.selectedPartition (I := I) (K := K) (ω := ω))
        (X.selectedBoundaryPiece (I := I) (K := K) (ω := ω)))
    (i :
      CoverIndexedBoundaryIndex
        (I := I) (X.selectedCover (I := I) (K := K) (ω := ω)))
    (q : X.selectedBoundaryPiece (I := I) (K := K) (ω := ω)) :
    ManifoldForm I M n :=
  ManifoldForm.localizedForm I (S.coefficient i q) ω

/-- The minimal endpoint partition generated by the intrinsic selected finite
cover and a smooth refinement.  The target chart is the self/source boundary
chart. -/
def endpointPartitionOfSelectedBoundaryFiniteCover
    [DecidableEq (X.selectedBoundaryPiece (I := I) (K := K) (ω := ω))]
    (S :
      BoundarySmoothBoxRefinement
        (I := I) (K := K)
        (X.selectedCover (I := I) (K := K) (ω := ω))
        (X.selectedPartition (I := I) (K := K) (ω := ω))
        (X.selectedBoundaryPiece (I := I) (K := K) (ω := ω))) :
    CoverIndexedBoundaryLocalizedRefinedPartition
      (I := I) (K := K)
      (X.selectedCover (I := I) (K := K) (ω := ω))
      (X.selectedPartition (I := I) (K := K) (ω := ω)) ω
      (X.selectedBoundaryPiece (I := I) (K := K) (ω := ω)) where
  boundaryPieces :=
    (X.selectedBoundaryFiniteCover (I := I) (K := K) (ω := ω)).sigmaBoundaryPieces
  localBulkTerm := fun i q =>
    projectLocalBulkIntegral I
      (X.selectedBoundarySelfChart (I := I) (K := K) (ω := ω) q)
      (X.selectedBoundarySelfChart (I := I) (K := K) (ω := ω) q)
      (X.selectedBoundaryLocalizedForm (I := I) (K := K) (ω := ω) S i q)
      (X.selectedBoundaryFiniteCoverLower (I := I) (K := K) (ω := ω) q)
      (X.selectedBoundaryFiniteCoverUpper (I := I) (K := K) (ω := ω) q)
  localBoundaryTerm := fun i q =>
    projectLocalBoundaryIntegral I
      (X.selectedBoundarySelfChart (I := I) (K := K) (ω := ω) q)
      (X.selectedBoundarySelfChart (I := I) (K := K) (ω := ω) q)
      (X.selectedBoundaryLocalizedForm (I := I) (K := K) (ω := ω) S i q)
      (X.selectedBoundaryFiniteCoverLower (I := I) (K := K) (ω := ω) q)
      (X.selectedBoundaryFiniteCoverUpper (I := I) (K := K) (ω := ω) q)

/-- Closed boxes selected by the intrinsic finite boundary cover lie in the
self chart-transition source. -/
theorem selectedBoundaryFiniteCover_Icc_subset_chartTransitionSource
    {i :
      CoverIndexedBoundaryIndex
        (I := I) (X.selectedCover (I := I) (K := K) (ω := ω))}
    {q : X.selectedBoundaryPiece (I := I) (K := K) (ω := ω)}
    (hq :
      q ∈
        (X.selectedBoundaryFiniteCover
          (I := I) (K := K) (ω := ω)).sigmaBoundaryPieces i) :
    Icc
        (X.selectedBoundaryFiniteCoverLower (I := I) (K := K) (ω := ω) q)
        (X.selectedBoundaryFiniteCoverUpper (I := I) (K := K) (ω := ω) q) ⊆
      ManifoldForm.chartTransitionSource I
        (X.selectedBoundarySelfChart (I := I) (K := K) (ω := ω) q)
        (X.selectedBoundarySelfChart (I := I) (K := K) (ω := ω) q) := by
  classical
  have hactive :
      q.2 ∈
        (X.selectedBoundaryFiniteCover
          (I := I) (K := K) (ω := ω)).activePieces q.1 :=
    (X.selectedBoundaryFiniteCover
      (I := I) (K := K) (ω := ω)).sigmaBoundaryPieces_active hq
  have hIcc_ambient :
      Icc
          ((X.selectedBoundaryFiniteCover
            (I := I) (K := K) (ω := ω)).lowerCorner q.1 q.2)
          ((X.selectedBoundaryFiniteCover
            (I := I) (K := K) (ω := ω)).upperCorner q.1 q.2) ⊆
        (X.selectedPartition
          (I := I) (K := K) (ω := ω)).boundaryAssignedIccAmbient
            (I := I) q.1 :=
    (X.selectedBoundaryFiniteCover
      (I := I) (K := K) (ω := ω)).Icc_subset_ambient q.1 hactive
  have hIcc_selected :
      Icc
          ((X.selectedBoundaryFiniteCover
            (I := I) (K := K) (ω := ω)).lowerCorner q.1 q.2)
          ((X.selectedBoundaryFiniteCover
            (I := I) (K := K) (ω := ω)).upperCorner q.1 q.2) ⊆
        Icc
          ((X.selectedCover
            (I := I) (K := K) (ω := ω)).boundaryLower q.1.1)
          ((X.selectedCover
            (I := I) (K := K) (ω := ω)).boundaryUpper q.1.1) := by
    simpa [SupportControlledSelectedPartition.boundaryAssignedIccAmbient] using
      hIcc_ambient
  have hdomain :
      Icc
          ((X.selectedBoundaryFiniteCover
            (I := I) (K := K) (ω := ω)).lowerCorner q.1 q.2)
          ((X.selectedBoundaryFiniteCover
            (I := I) (K := K) (ω := ω)).upperCorner q.1 q.2) ⊆
        boundaryChartDomain I
          ((X.selectedCover
            (I := I) (K := K) (ω := ω)).boundaryChart q.1.1)
          ((X.selectedCover
            (I := I) (K := K) (ω := ω)).boundaryChart q.1.1) :=
    hIcc_selected.trans
      ((X.selectedCover
        (I := I) (K := K) (ω := ω)).boundary_Icc_subset_domain q.1.1 q.1.2)
  simpa [selectedBoundarySelfChart, selectedBoundaryFiniteCoverLower,
    selectedBoundaryFiniteCoverUpper, boundaryChartDomain_eq_chartTransitionSource] using
    hdomain

/-- Build the `LocalStokesData` package corresponding to
`endpointPartitionOfSelectedBoundaryFiniteCover`.

The ordinary localized and zero-localized support statements are kept as
explicit arguments.  The endpoint term equalities are definitional, and the
chart-transition-source containment is derived from the selected boundary
closed-box containment. -/
def localStokesDataOfSelectedBoundaryFiniteCover
    [DecidableEq (X.selectedBoundaryPiece (I := I) (K := K) (ω := ω))]
    (S :
      BoundarySmoothBoxRefinement
        (I := I) (K := K)
        (X.selectedCover (I := I) (K := K) (ω := ω))
        (X.selectedPartition (I := I) (K := K) (ω := ω))
        (X.selectedBoundaryPiece (I := I) (K := K) (ω := ω)))
    (hlocalized :
      ∀ i
        (q : X.selectedBoundaryPiece (I := I) (K := K) (ω := ω)),
        q ∈
            (X.selectedBoundaryFiniteCover
              (I := I) (K := K) (ω := ω)).sigmaBoundaryPieces i →
          tsupport
              (ManifoldForm.transitionPullbackInChart I
                (X.selectedBoundarySelfChart (I := I) (K := K) (ω := ω) q)
                (X.selectedBoundarySelfChart (I := I) (K := K) (ω := ω) q)
                (X.selectedBoundaryLocalizedForm
                  (I := I) (K := K) (ω := ω) S i q)) ⊆
            halfSpaceSupportBox
              (X.selectedBoundaryFiniteCoverLower
                (I := I) (K := K) (ω := ω) q)
              (X.selectedBoundaryFiniteCoverUpper
                (I := I) (K := K) (ω := ω) q))
    (hzero :
      ∀ i
        (q : X.selectedBoundaryPiece (I := I) (K := K) (ω := ω)),
        q ∈
            (X.selectedBoundaryFiniteCover
              (I := I) (K := K) (ω := ω)).sigmaBoundaryPieces i →
          tsupport
              (ManifoldForm.transitionPullbackInChartZero I
                (X.selectedBoundarySelfChart (I := I) (K := K) (ω := ω) q)
                (X.selectedBoundarySelfChart (I := I) (K := K) (ω := ω) q)
                (X.selectedBoundaryLocalizedForm
                  (I := I) (K := K) (ω := ω) S i q)) ⊆
            halfSpaceSupportBox
              (X.selectedBoundaryFiniteCoverLower
                (I := I) (K := K) (ω := ω) q)
              (X.selectedBoundaryFiniteCoverUpper
                (I := I) (K := K) (ω := ω) q)) :
    (X.endpointPartitionOfSelectedBoundaryFiniteCover
      (I := I) (K := K) (ω := ω) S).LocalStokesData
      (I := I) (K := K) where
  sourceChart := fun _ q =>
    X.selectedBoundarySelfChart (I := I) (K := K) (ω := ω) q
  targetChart := fun _ q =>
    X.selectedBoundarySelfChart (I := I) (K := K) (ω := ω) q
  localizedForm := fun i q =>
    X.selectedBoundaryLocalizedForm (I := I) (K := K) (ω := ω) S i q
  lower := fun _ q =>
    X.selectedBoundaryFiniteCoverLower (I := I) (K := K) (ω := ω) q
  upper := fun _ q =>
    X.selectedBoundaryFiniteCoverUpper (I := I) (K := K) (ω := ω) q
  localBulkTerm_eq := by
    intro i q hq
    rfl
  localBoundaryTerm_eq := by
    intro i q hq
    rfl
  Icc_subset_chartTransitionSource := by
    intro i q hq
    exact
      X.selectedBoundaryFiniteCover_Icc_subset_chartTransitionSource
        (I := I) (K := K) (ω := ω) hq
  localized_tsupport_subset_halfSpaceSupportBox := by
    intro i q hq
    exact hlocalized i q hq
  zero_tsupport_subset_halfSpaceSupportBox := by
    intro i q hq
    exact hzero i q hq

/--
Build the zero-localized `ZeroLocalStokesData` package corresponding to
`endpointPartitionOfSelectedBoundaryFiniteCover`.

This is the preferred intrinsic-route constructor: it does not ask for support
of the old total `transitionPullbackInChart` representative, only for support
of the zero-extended localized representative that is actually used to kill
the artificial faces in the half-space local Stokes proof.
-/
def zeroLocalStokesDataOfSelectedBoundaryFiniteCover
    [DecidableEq (X.selectedBoundaryPiece (I := I) (K := K) (ω := ω))]
    (S :
      BoundarySmoothBoxRefinement
        (I := I) (K := K)
        (X.selectedCover (I := I) (K := K) (ω := ω))
        (X.selectedPartition (I := I) (K := K) (ω := ω))
        (X.selectedBoundaryPiece (I := I) (K := K) (ω := ω)))
    (hzero :
      ∀ i
        (q : X.selectedBoundaryPiece (I := I) (K := K) (ω := ω)),
        q ∈
            (X.selectedBoundaryFiniteCover
              (I := I) (K := K) (ω := ω)).sigmaBoundaryPieces i →
          tsupport
              (ManifoldForm.transitionPullbackInChartZero I
                (X.selectedBoundarySelfChart (I := I) (K := K) (ω := ω) q)
                (X.selectedBoundarySelfChart (I := I) (K := K) (ω := ω) q)
                (X.selectedBoundaryLocalizedForm
                  (I := I) (K := K) (ω := ω) S i q)) ⊆
            halfSpaceSupportBox
              (X.selectedBoundaryFiniteCoverLower
                (I := I) (K := K) (ω := ω) q)
              (X.selectedBoundaryFiniteCoverUpper
                (I := I) (K := K) (ω := ω) q)) :
    (X.endpointPartitionOfSelectedBoundaryFiniteCover
      (I := I) (K := K) (ω := ω) S).ZeroLocalStokesData
      (I := I) (K := K) where
  sourceChart := fun _ q =>
    X.selectedBoundarySelfChart (I := I) (K := K) (ω := ω) q
  targetChart := fun _ q =>
    X.selectedBoundarySelfChart (I := I) (K := K) (ω := ω) q
  localizedForm := fun i q =>
    X.selectedBoundaryLocalizedForm (I := I) (K := K) (ω := ω) S i q
  lower := fun _ q =>
    X.selectedBoundaryFiniteCoverLower (I := I) (K := K) (ω := ω) q
  upper := fun _ q =>
    X.selectedBoundaryFiniteCoverUpper (I := I) (K := K) (ω := ω) q
  localBulkTerm_eq := by
    intro i q hq
    rfl
  localBoundaryTerm_eq := by
    intro i q hq
    rfl
  Icc_subset_chartTransitionSource := by
    intro i q hq
    exact
      X.selectedBoundaryFiniteCover_Icc_subset_chartTransitionSource
        (I := I) (K := K) (ω := ω) hq
  zero_tsupport_subset_halfSpaceSupportBox := by
    intro i q hq
    exact hzero i q hq

end CoverIndexedZeroCompactRepresentedStokesIntrinsicInput

end IntrinsicEndpointConstructor

end Stokes

end
