import Stokes.Global.PointwiseChartBoxFromHalfSpaceModel
import Stokes.Global.CoverIndexedIntrinsicZeroSupportConstructor

/-!
# First-principles compact-support represented Stokes input

This file exposes the preferred represented Stokes entry point whose public
fields are exactly the analytic hypotheses from the compact-support statement:
chartwise smoothness and compactness of the form support.  The compact carrier
is the closure of the algebraic support, and pointwise chart boxes are generated
from self charts using the half-space model.
-/

noncomputable section

open Set MeasureTheory Filter
open scoped BigOperators Manifold Topology

namespace Stokes

section FirstPrinciplesRepresentedStokes

universe uH uM

variable {H : Type uH} [TopologicalSpace H]
variable {M : Type uM} [TopologicalSpace M] [ChartedSpace H M]
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) → Real) H}
variable {ω : ManifoldForm I M n}
variable [HalfSpaceModel I]
variable [FiniteDimensional Real (Fin (n + 1) → Real)]
variable [IsManifold I ⊤ M] [T2Space M] [SigmaCompactSpace M]

/-- First-principles input for compact-support represented Stokes.

The support carrier and all pointwise chart-box data are generated internally.
-/
structure CoverIndexedZeroCompactRepresentedStokesFirstPrinciplesInput
    (I : ModelWithCorners Real (Fin (n + 1) → Real) H)
    (ω : ManifoldForm I M n) where
  /-- Smoothness of the input form in charts. -/
  chartwiseSmooth : ManifoldForm.ChartwiseSmooth I ω
  /-- Compactness of the closed algebraic support. -/
  compactSupport : IsCompact (closure (ManifoldForm.support I ω))

namespace CoverIndexedZeroCompactRepresentedStokesFirstPrinciplesInput

variable
    (X : CoverIndexedZeroCompactRepresentedStokesFirstPrinciplesInput
      (M := M) I ω)

/-- The canonical compact carrier: the closure of the algebraic support. -/
def supportCarrier : Set M :=
  closure (ManifoldForm.support I ω)

/-- The intrinsic represented-Stokes input generated from first principles. -/
def intrinsicInput :
    CoverIndexedZeroCompactRepresentedStokesIntrinsicInput
      (I := I) (ω := ω) (supportCarrier (I := I) (ω := ω)) where
  pointwise :=
    PointwiseCompactSupportChartBoxData.ofHalfSpaceModelSelfCharts
      (I := I) (supportCarrier (I := I) (ω := ω))
  hK := by
    simpa [supportCarrier] using X.compactSupport
  chartwiseSmooth := X.chartwiseSmooth
  support_subset_K := by
    intro x hx
    exact subset_closure hx

/-- Canonical represented bulk integral generated by the first-principles
route. -/
def canonicalRepresentedBulkIntegral : Real :=
  (X.intrinsicInput (I := I) (ω := ω)).canonicalRepresentedBulkIntegral
    (I := I) (K := supportCarrier (I := I) (ω := ω)) (ω := ω)

/-- Canonical represented boundary integral generated by the first-principles
route. -/
def canonicalRepresentedBoundaryIntegral : Real :=
  (X.intrinsicInput (I := I) (ω := ω)).canonicalRepresentedBoundaryIntegral
    (I := I) (K := supportCarrier (I := I) (ω := ω)) (ω := ω)

/-- First-principles compact-support represented Stokes.

Public form fields are only chartwise smoothness and compact support.  The
finite chart-box cover, partition, local half-space Stokes data, and represented
endpoint are generated internally.
-/
theorem representedStokes :
    X.canonicalRepresentedBulkIntegral (I := I) (ω := ω) =
      X.canonicalRepresentedBoundaryIntegral (I := I) (ω := ω) := by
  simpa [canonicalRepresentedBulkIntegral, canonicalRepresentedBoundaryIntegral] using
    (X.intrinsicInput (I := I) (ω := ω)).representedStokes
      (I := I) (K := supportCarrier (I := I) (ω := ω)) (ω := ω)

end CoverIndexedZeroCompactRepresentedStokesFirstPrinciplesInput

end FirstPrinciplesRepresentedStokes

end Stokes

end
