import Stokes.Global.EndToEndRemainingInput

/-!
# Current global endpoint gap-reduction audit

This file is intentionally not imported by a public facade.  It records the
current theorem-facing endpoint inputs in small theorem-shaped packages, and
adds one low-risk constructor for callers that already have the strict-buffer
alignment package.

The audit is structural only: no new analytic, orientation, inverse-function,
or measure-localization theorem is proved here.
-/

noncomputable section

set_option linter.unusedSectionVars false

open MeasureTheory
open scoped BigOperators Manifold Topology

namespace Stokes

section CurrentGapReductionAudit

universe u w b a

variable {H : Type u} [TopologicalSpace H]
variable {M : Type w} [TopologicalSpace M] [ChartedSpace H M]
variable {BoundaryPiece : Type b}
variable {α : Type a} [TopologicalSpace α] [MeasurableSpace α]
variable [OpensMeasurableSpace α] [T2Space α]
variable {μ : Measure α} [IsFiniteMeasureOnCompacts μ]
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) -> Real) H}
variable {omega : ManifoldForm I M n}

/--
Endpoint fields that are already generated automatically once the current
end-to-end input exists.
-/
structure CurrentEndpointAutomatedFields
    (D :
      NaturalCompactSupportEndToEndInput
        (α := α) I omega BoundaryPiece μ) where
  /-- The compact-support measure builder generated from bulk and boundary data. -/
  measureBuilder :
    CompactSupportMeasureToM8BuilderData
      (α := α) I omega D.selectedPartition D.targetImageInput.targetImages μ
      D.globalBulkIntegral D.boundaryTarget.globalBoundaryIntegral
  /-- The strict-builder alignment generated by the endpoint record. -/
  strictAlignment :
    NaturalMeasureStrictBuilderAlignment D.targetImageInput D.measureBuilder
      D.compactActiveBoxes
  /-- The natural compact-support theorem input generated from the endpoint record. -/
  naturalInput :
    NaturalCompactSupportStokesInput
      (α := α) I omega BoundaryPiece μ

/--
Endpoint fields that still represent genuine mathematical work in the current
shortest global route.
-/
structure CurrentEndpointMathematicalFields
    (D :
      NaturalCompactSupportEndToEndInput
        (α := α) I omega BoundaryPiece μ) where
  /-- Bulk measure localization for the selected partition. -/
  bulk :
    BulkMeasureFromPartitionData
      (α := α) (μ := μ) D.selectedPartition
      D.targetImageInput.targetImages D.globalBulkIntegral
  /-- Boundary target/measure route, including chart-change content. -/
  boundaryTarget :
    CanonicalBoundaryTargetCompactSupportInput
      (α := α) D.targetImageInput μ
  /-- Alignment between compact active boxes and selected chart boxes. -/
  selectedPartitionAlignment :
    CompactActiveSelectedPartitionAlignment D.compactActiveBoxes
      D.selectedPartition
  /-- Alignment between selected labels and localized M8 pieces. -/
  localizedPieceAlignment :
    LocalizedInteriorPieceAlignment D.selectedPartition
      D.targetImageInput.targetImages D.measureBuilder.toM8MeasureLocalizationData
  /-- Strict lower margin putting compact boxes inside localized pieces. -/
  outer_lower_lt_selectedLower :
    ∀ x, x ∈ D.selectedPartition.active → ∀ j : Fin (n + 1),
      (D.measureBuilder.toM8MeasureLocalizationData.localizedInterior.piece x).lowerCorner j <
        D.selectedPartition.lower x j
  /-- Strict upper margin putting compact boxes inside localized pieces. -/
  selectedUpper_lt_outer_upper :
    ∀ x, x ∈ D.selectedPartition.active → ∀ j : Fin (n + 1),
      D.selectedPartition.upper x j <
        (D.measureBuilder.toM8MeasureLocalizationData.localizedInterior.piece x).upperCorner j

/--
Endpoint fields that are primarily engineering glue: they choose the concrete
objects that the mathematical packages talk about.
-/
structure CurrentEndpointGlueFields
    (I : ModelWithCorners Real (Fin (n + 1) -> Real) H)
    (omega : ManifoldForm I M n)
    (BoundaryPiece : Type b)
    (μ : Measure α) [IsFiniteMeasureOnCompacts μ] where
  /-- Compactly supported form data. -/
  formData : CompactlySupportedSmoothFormData I omega
  /-- Explicit oriented boundary atlas used by target-image data. -/
  orientedBoundaryAtlas : BoundaryChartOrientedAtlas I M
  /-- Selected partition and chart boxes. -/
  selectedPartition : SelectedBoxPartitionOfUnity I omega
  /-- The selected support set is the compact support set from `formData`. -/
  selectedPartition_supportSet :
    selectedPartition.K = formData.supportSet
  /-- Target-image input over the selected partition. -/
  targetImageInput :
    M8TargetImageInput I omega selectedPartition orientedBoundaryAtlas
      BoundaryPiece
  /-- Represented global bulk integral value. -/
  globalBulkIntegral : Real
  /-- Compact active boxes used by the strict-buffer route. -/
  compactActiveBoxes : CompactActiveBoxData I omega

namespace NaturalCompactSupportEndToEndInput

variable
    (D :
      NaturalCompactSupportEndToEndInput
        (α := α) I omega BoundaryPiece μ)

/-- Project the already-automated package from the current endpoint input. -/
def currentAutomatedFields :
    CurrentEndpointAutomatedFields D where
  measureBuilder := D.measureBuilder
  strictAlignment := D.naturalMeasureStrictBuilderAlignment
  naturalInput := D.toNaturalCompactSupportStokesInput

@[simp]
theorem currentAutomatedFields_measureBuilder :
    D.currentAutomatedFields.measureBuilder = D.measureBuilder :=
  rfl

@[simp]
theorem currentAutomatedFields_strictAlignment :
    D.currentAutomatedFields.strictAlignment =
      D.naturalMeasureStrictBuilderAlignment :=
  rfl

@[simp]
theorem currentAutomatedFields_naturalInput :
    D.currentAutomatedFields.naturalInput =
      D.toNaturalCompactSupportStokesInput :=
  rfl

/-- Project the genuine mathematical obligations from the endpoint input. -/
def currentMathematicalFields :
    CurrentEndpointMathematicalFields D where
  bulk := D.bulk
  boundaryTarget := D.boundaryTarget
  selectedPartitionAlignment := D.selectedPartitionAlignment
  localizedPieceAlignment := D.localizedPieceAlignment
  outer_lower_lt_selectedLower := D.outer_lower_lt_selectedLower
  selectedUpper_lt_outer_upper := D.selectedUpper_lt_outer_upper

@[simp]
theorem currentMathematicalFields_bulk :
    D.currentMathematicalFields.bulk = D.bulk :=
  rfl

@[simp]
theorem currentMathematicalFields_boundaryTarget :
    D.currentMathematicalFields.boundaryTarget = D.boundaryTarget :=
  rfl

@[simp]
theorem currentMathematicalFields_selectedPartitionAlignment :
    D.currentMathematicalFields.selectedPartitionAlignment =
      D.selectedPartitionAlignment :=
  rfl

@[simp]
theorem currentMathematicalFields_localizedPieceAlignment :
    D.currentMathematicalFields.localizedPieceAlignment =
      D.localizedPieceAlignment :=
  rfl

/-- Project the object-selection/glue fields from the endpoint input. -/
def currentGlueFields :
    CurrentEndpointGlueFields I omega BoundaryPiece μ where
  formData := D.formData
  orientedBoundaryAtlas := D.orientedBoundaryAtlas
  selectedPartition := D.selectedPartition
  selectedPartition_supportSet := D.selectedPartition_supportSet
  targetImageInput := D.targetImageInput
  globalBulkIntegral := D.globalBulkIntegral
  compactActiveBoxes := D.compactActiveBoxes

@[simp]
theorem currentGlueFields_formData :
    D.currentGlueFields.formData = D.formData :=
  rfl

@[simp]
theorem currentGlueFields_selectedPartition :
    D.currentGlueFields.selectedPartition = D.selectedPartition :=
  rfl

@[simp]
theorem currentGlueFields_targetImageInput :
    D.currentGlueFields.targetImageInput = D.targetImageInput :=
  rfl

end NaturalCompactSupportEndToEndInput

namespace CurrentEndpointGlueFields

variable
    (G : CurrentEndpointGlueFields I omega BoundaryPiece μ)

/--
Low-risk constructor: build the current end-to-end endpoint input from the
glue fields, the two measure-route fields, and one already packaged strict
alignment.

This removes four separate endpoint fields for callers that already constructed
`NaturalMeasureStrictBuilderAlignment`.
-/
def toEndToEndInputOfStrictAlignment
    (bulk :
      BulkMeasureFromPartitionData
        (α := α) (μ := μ) G.selectedPartition
        G.targetImageInput.targetImages G.globalBulkIntegral)
    (boundaryTarget :
      CanonicalBoundaryTargetCompactSupportInput
        (α := α) G.targetImageInput μ)
    (alignment :
      NaturalMeasureStrictBuilderAlignment G.targetImageInput
        (boundaryTarget.toMeasureBuilderData bulk) G.compactActiveBoxes) :
    NaturalCompactSupportEndToEndInput
      (α := α) I omega BoundaryPiece μ where
  formData := G.formData
  orientedBoundaryAtlas := G.orientedBoundaryAtlas
  selectedPartition := G.selectedPartition
  selectedPartition_supportSet := G.selectedPartition_supportSet
  targetImageInput := G.targetImageInput
  globalBulkIntegral := G.globalBulkIntegral
  bulk := bulk
  boundaryTarget := boundaryTarget
  compactActiveBoxes := G.compactActiveBoxes
  selectedPartitionAlignment := alignment.selectedPartitionAlignment
  localizedPieceAlignment := alignment.localizedPieceAlignment
  outer_lower_lt_selectedLower := alignment.outer_lower_lt_selectedLower
  selectedUpper_lt_outer_upper := alignment.selectedUpper_lt_outer_upper

@[simp]
theorem toEndToEndInputOfStrictAlignment_selectedPartition
    (bulk :
      BulkMeasureFromPartitionData
        (α := α) (μ := μ) G.selectedPartition
        G.targetImageInput.targetImages G.globalBulkIntegral)
    (boundaryTarget :
      CanonicalBoundaryTargetCompactSupportInput
        (α := α) G.targetImageInput μ)
    (alignment :
      NaturalMeasureStrictBuilderAlignment G.targetImageInput
        (boundaryTarget.toMeasureBuilderData bulk) G.compactActiveBoxes) :
    (G.toEndToEndInputOfStrictAlignment bulk boundaryTarget alignment).selectedPartition =
      G.selectedPartition :=
  rfl

@[simp]
theorem toEndToEndInputOfStrictAlignment_bulk
    (bulk :
      BulkMeasureFromPartitionData
        (α := α) (μ := μ) G.selectedPartition
        G.targetImageInput.targetImages G.globalBulkIntegral)
    (boundaryTarget :
      CanonicalBoundaryTargetCompactSupportInput
        (α := α) G.targetImageInput μ)
    (alignment :
      NaturalMeasureStrictBuilderAlignment G.targetImageInput
        (boundaryTarget.toMeasureBuilderData bulk) G.compactActiveBoxes) :
    (G.toEndToEndInputOfStrictAlignment bulk boundaryTarget alignment).bulk =
      bulk :=
  rfl

@[simp]
theorem toEndToEndInputOfStrictAlignment_boundaryTarget
    (bulk :
      BulkMeasureFromPartitionData
        (α := α) (μ := μ) G.selectedPartition
        G.targetImageInput.targetImages G.globalBulkIntegral)
    (boundaryTarget :
      CanonicalBoundaryTargetCompactSupportInput
        (α := α) G.targetImageInput μ)
    (alignment :
      NaturalMeasureStrictBuilderAlignment G.targetImageInput
        (boundaryTarget.toMeasureBuilderData bulk) G.compactActiveBoxes) :
    (G.toEndToEndInputOfStrictAlignment bulk boundaryTarget alignment).boundaryTarget =
      boundaryTarget :=
  rfl

@[simp]
theorem toEndToEndInputOfStrictAlignment_selectedPartitionAlignment
    (bulk :
      BulkMeasureFromPartitionData
        (α := α) (μ := μ) G.selectedPartition
        G.targetImageInput.targetImages G.globalBulkIntegral)
    (boundaryTarget :
      CanonicalBoundaryTargetCompactSupportInput
        (α := α) G.targetImageInput μ)
    (alignment :
      NaturalMeasureStrictBuilderAlignment G.targetImageInput
        (boundaryTarget.toMeasureBuilderData bulk) G.compactActiveBoxes) :
    (G.toEndToEndInputOfStrictAlignment bulk boundaryTarget alignment).selectedPartitionAlignment =
      alignment.selectedPartitionAlignment :=
  rfl

end CurrentEndpointGlueFields

end CurrentGapReductionAudit

end Stokes

end
