import Stokes.Global.RemainingInputScoreboard
import Stokes.Global.LocalizedChartAlignmentFromNaturalSelectionAuto

/-!
# Endpoint geometry from localized-piece equality data

This module removes one raw `RemainingEndpointGeometryPackage` input.  Once the
localized pieces are known to agree with the natural selected-partition
constructor, chart alignment is generated by
`NaturalFiniteActiveLocalizedPieceEqData`; chart-box strict containment remains
the genuine geometric input.
-/

noncomputable section

set_option linter.style.longLine false
set_option linter.unusedSectionVars false

open Set MeasureTheory
open scoped BigOperators Manifold Topology

namespace Stokes

section EndpointGeometryFromLocalizedPiecesAuto

universe u w b ei eb

variable {H : Type u} [TopologicalSpace H]
variable {M : Type w} [TopologicalSpace M] [ChartedSpace H M]
variable {BoundaryPiece : Type b}
variable {ExtInteriorPiece : Type ei} {ExtBoundaryPiece : Type eb}
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) -> Real) H}
variable {omega : ManifoldForm I M n}
variable {rho : SmoothPartitionOfUnity M I M univ}
variable {mu : Measure (Fin (n + 1) -> Real)}
variable [IsFiniteMeasureOnCompacts mu]
variable [IsManifold I 1 M]

namespace RemainingEndpointGeometryPackage

variable {C : RemainingChartBoxSelectionPackage I omega rho}
variable
    (B :
      RemainingBulkBoundaryRoutePackage
        C ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu)

/--
Endpoint geometry generated from natural localized-piece equality data and the
remaining strict chart-box containment fact.
-/
def ofLocalizedPieces
    (localizedPieces :
      NaturalFiniteActiveLocalizedPieceEqData C.chartBoxes
        B.boundaryMeasure.toSelectedReconstructionEndpointSource.localized)
    (strictContainment : B.boundaryMeasure.StrictAlignmentChartBoxContainmentData) :
    RemainingEndpointGeometryPackage B where
  chartAlignment := localizedPieces.toLocalizedInteriorM8ChartAlignment
  strictContainment := strictContainment

@[simp]
theorem ofLocalizedPieces_chartAlignment
    (localizedPieces :
      NaturalFiniteActiveLocalizedPieceEqData C.chartBoxes
        B.boundaryMeasure.toSelectedReconstructionEndpointSource.localized)
    (strictContainment : B.boundaryMeasure.StrictAlignmentChartBoxContainmentData) :
    (ofLocalizedPieces B localizedPieces strictContainment).chartAlignment =
      localizedPieces.toLocalizedInteriorM8ChartAlignment := by
  rfl

@[simp]
theorem ofLocalizedPieces_strictContainment
    (localizedPieces :
      NaturalFiniteActiveLocalizedPieceEqData C.chartBoxes
        B.boundaryMeasure.toSelectedReconstructionEndpointSource.localized)
    (strictContainment : B.boundaryMeasure.StrictAlignmentChartBoxContainmentData) :
    (ofLocalizedPieces B localizedPieces strictContainment).strictContainment =
      strictContainment := by
  rfl

end RemainingEndpointGeometryPackage

namespace RemainingOnePackageConstructionScoreboard

/--
Build the current compact-support one-package scoreboard once localized pieces
generate chart alignment and strict chart-box containment is supplied.
-/
def ofLocalizedPieces
    (C : RemainingChartBoxSelectionPackage I omega rho)
    (B :
      RemainingBulkBoundaryRoutePackage
        C ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu)
    (localizedPieces :
      NaturalFiniteActiveLocalizedPieceEqData C.chartBoxes
        B.boundaryMeasure.toSelectedReconstructionEndpointSource.localized)
    (strictContainment : B.boundaryMeasure.StrictAlignmentChartBoxContainmentData) :
    RemainingOnePackageConstructionScoreboard
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu where
  chartBoxSelection := C
  bulkBoundary := B
  endpointGeometry :=
    RemainingEndpointGeometryPackage.ofLocalizedPieces
      B localizedPieces strictContainment

@[simp]
theorem ofLocalizedPieces_chartBoxSelection
    (C : RemainingChartBoxSelectionPackage I omega rho)
    (B :
      RemainingBulkBoundaryRoutePackage
        C ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu)
    (localizedPieces :
      NaturalFiniteActiveLocalizedPieceEqData C.chartBoxes
        B.boundaryMeasure.toSelectedReconstructionEndpointSource.localized)
    (strictContainment : B.boundaryMeasure.StrictAlignmentChartBoxContainmentData) :
    (ofLocalizedPieces C B localizedPieces strictContainment).chartBoxSelection = C := by
  rfl

@[simp]
theorem ofLocalizedPieces_bulkBoundary
    (C : RemainingChartBoxSelectionPackage I omega rho)
    (B :
      RemainingBulkBoundaryRoutePackage
        C ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu)
    (localizedPieces :
      NaturalFiniteActiveLocalizedPieceEqData C.chartBoxes
        B.boundaryMeasure.toSelectedReconstructionEndpointSource.localized)
    (strictContainment : B.boundaryMeasure.StrictAlignmentChartBoxContainmentData) :
    (ofLocalizedPieces C B localizedPieces strictContainment).bulkBoundary = B := by
  rfl

/-- One-package chart-box input generated by localized-piece equality data. -/
abbrev toOnePackageChartBoxInputOfLocalizedPieces
    (C : RemainingChartBoxSelectionPackage I omega rho)
    (B :
      RemainingBulkBoundaryRoutePackage
        C ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu)
    (localizedPieces :
      NaturalFiniteActiveLocalizedPieceEqData C.chartBoxes
        B.boundaryMeasure.toSelectedReconstructionEndpointSource.localized)
    (strictContainment : B.boundaryMeasure.StrictAlignmentChartBoxContainmentData) :
    NaturalCompactSupportOnePackageChartBoxStokesInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  (ofLocalizedPieces C B localizedPieces strictContainment).toOnePackageChartBoxInput

/--
Represented compact-support Stokes directly from localized-piece equality data
and strict chart-box containment.
-/
theorem represented_stokes_ofLocalizedPieces
    (C : RemainingChartBoxSelectionPackage I omega rho)
    (B :
      RemainingBulkBoundaryRoutePackage
        C ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu)
    (localizedPieces :
      NaturalFiniteActiveLocalizedPieceEqData C.chartBoxes
        B.boundaryMeasure.toSelectedReconstructionEndpointSource.localized)
    (strictContainment : B.boundaryMeasure.StrictAlignmentChartBoxContainmentData) :
    (ofLocalizedPieces C B localizedPieces strictContainment).representedStokesStatement :=
  (ofLocalizedPieces C B localizedPieces strictContainment).represented_stokes

/--
The same result expressed through the generated one-package chart-box input.
-/
theorem canonical_stokes_ofLocalizedPieces
    (C : RemainingChartBoxSelectionPackage I omega rho)
    (B :
      RemainingBulkBoundaryRoutePackage
        C ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu)
    (localizedPieces :
      NaturalFiniteActiveLocalizedPieceEqData C.chartBoxes
        B.boundaryMeasure.toSelectedReconstructionEndpointSource.localized)
    (strictContainment : B.boundaryMeasure.StrictAlignmentChartBoxContainmentData) :
    (toOnePackageChartBoxInputOfLocalizedPieces
      C B localizedPieces strictContainment)
      |>.canonicalIntegralInterface
      |>.stokesStatement :=
  (toOnePackageChartBoxInputOfLocalizedPieces
    C B localizedPieces strictContainment)
    |>.canonical_stokes

end RemainingOnePackageConstructionScoreboard

end EndpointGeometryFromLocalizedPiecesAuto

end Stokes

end
