import Stokes.Global.CompactActiveStrictOuterBoxFromLocalizedPiecesAuto

/-!
# Localized-piece strict margins from selected compact boxes

`CompactActiveStrictOuterBoxFromLocalizedPiecesAuto` consumes strict margins in
the compact-active box coordinates:

* the localized-piece lower corner is below `D.lower`;
* `D.upper` is below the localized-piece upper corner.

The common compact-support endpoint route often has the same facts in the
selected-partition coordinates instead.  This file packages the harmless
rewrite through `CompactActiveSelectedPartitionAlignment`, then exposes direct
constructors for the localized-piece outer-box data and strict-buffer data.
-/

noncomputable section

set_option linter.unusedSectionVars false

open Set MeasureTheory
open scoped BigOperators Manifold Topology

namespace Stokes

section LocalizedPieceStrictMarginsAuto

universe u w b a ei eb

variable {H : Type u} [TopologicalSpace H]
variable {M : Type w} [TopologicalSpace M] [ChartedSpace H M]
variable {BoundaryPiece : Type b}
variable {ExtInteriorPiece : Type ei} {ExtBoundaryPiece : Type eb}
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) -> Real) H}
variable {omega : ManifoldForm I M n}
variable {selectedPartition : SelectedBoxPartitionOfUnity I omega}
variable {targetImages : BoundaryPieceFamilyInput I omega M BoundaryPiece}
variable {measureLocalization :
  M8MeasureLocalizationData I omega selectedPartition targetImages}
variable {D : CompactActiveBoxData I omega}

/--
Strict localized-piece margins in compact-active coordinates, together with
the active-set and chart-label alignments needed to feed the strict outer-box
constructor.
-/
structure CompactActiveLocalizedPieceStrictMargins
    (D : CompactActiveBoxData I omega)
    (selectedPartition : SelectedBoxPartitionOfUnity I omega)
    (targetImages : BoundaryPieceFamilyInput I omega M BoundaryPiece)
    (measureLocalization :
      M8MeasureLocalizationData I omega selectedPartition targetImages) where
  selectedPartitionAlignment :
    CompactActiveSelectedPartitionAlignment D selectedPartition
  localizedPieceAlignment :
    LocalizedInteriorPieceAlignment selectedPartition targetImages
      measureLocalization
  compactActive_subset_selected :
    forall x, x ∈ D.finiteActive.active -> x ∈ selectedPartition.active
  pieceLower_lt_compactLower :
    forall x, x ∈ selectedPartition.active -> forall j : Fin (n + 1),
      (measureLocalization.localizedInterior.piece x).lowerCorner j <
        D.lower x j
  compactUpper_lt_pieceUpper :
    forall x, x ∈ selectedPartition.active -> forall j : Fin (n + 1),
      D.upper x j <
        (measureLocalization.localizedInterior.piece x).upperCorner j

namespace CompactActiveLocalizedPieceStrictMargins

variable
    (A :
      CompactActiveLocalizedPieceStrictMargins D selectedPartition targetImages
        measureLocalization)

/-- Forget compact-active strict margins to localized-piece outer-box data. -/
def toLocalizedPieceOuterBoxData :
    CompactActiveLocalizedPieceOuterBoxData D selectedPartition targetImages
      measureLocalization :=
  CompactActiveLocalizedPieceOuterBoxData.ofPieceStrictMargins
    A.selectedPartitionAlignment
    A.localizedPieceAlignment
    A.compactActive_subset_selected
    A.pieceLower_lt_compactLower
    A.compactUpper_lt_pieceUpper

/-- The single-source strict-buffer constructor generated by the margins. -/
def toStrictBufferConstructorData :
    CompactActiveStrictBufferConstructorData D selectedPartition targetImages
      measureLocalization :=
  A.toLocalizedPieceOuterBoxData.toStrictBufferConstructorData

/-- Direct strict-buffer alignment generated by the margins. -/
def toCompactActiveBoxStrictBufferAlignment :
    CompactActiveBoxStrictBufferAlignment D selectedPartition targetImages
      measureLocalization :=
  A.toLocalizedPieceOuterBoxData.toCompactActiveBoxStrictBufferAlignment

@[simp]
theorem toLocalizedPieceOuterBoxData_selectedPartitionAlignment :
    A.toLocalizedPieceOuterBoxData.selectedPartitionAlignment =
      A.selectedPartitionAlignment := by
  rfl

@[simp]
theorem toLocalizedPieceOuterBoxData_localizedPieceAlignment :
    A.toLocalizedPieceOuterBoxData.localizedPieceAlignment =
      A.localizedPieceAlignment := by
  rfl

end CompactActiveLocalizedPieceStrictMargins

namespace SelectedBoxStrictMarginData

/-- Selected-box lower margins rewritten to compact-active lower margins. -/
theorem pieceLower_lt_compactLower
    (margins :
      SelectedBoxStrictMarginData selectedPartition targetImages
        measureLocalization)
    (alignment : CompactActiveSelectedPartitionAlignment D selectedPartition) :
    forall x, x ∈ selectedPartition.active -> forall j : Fin (n + 1),
      (measureLocalization.localizedInterior.piece x).lowerCorner j <
        D.lower x j := by
  intro x hx j
  simpa [alignment.lower_eq] using
    margins.outer_lower_lt_selectedLower x hx j

/-- Selected-box upper margins rewritten to compact-active upper margins. -/
theorem compactUpper_lt_pieceUpper
    (margins :
      SelectedBoxStrictMarginData selectedPartition targetImages
        measureLocalization)
    (alignment : CompactActiveSelectedPartitionAlignment D selectedPartition) :
    forall x, x ∈ selectedPartition.active -> forall j : Fin (n + 1),
      D.upper x j <
        (measureLocalization.localizedInterior.piece x).upperCorner j := by
  intro x hx j
  simpa [alignment.upper_eq] using
    margins.selectedUpper_lt_outer_upper x hx j

/--
Package selected-box strict margins in the compact-active localized-piece
strict-margin shape.
-/
def toCompactActiveLocalizedPieceStrictMargins
    (margins :
      SelectedBoxStrictMarginData selectedPartition targetImages
        measureLocalization)
    (alignment : CompactActiveSelectedPartitionAlignment D selectedPartition)
    (localizedPieceAlignment :
      LocalizedInteriorPieceAlignment selectedPartition targetImages
        measureLocalization)
    (compactActive_subset_selected :
      forall x, x ∈ D.finiteActive.active -> x ∈ selectedPartition.active) :
    CompactActiveLocalizedPieceStrictMargins D selectedPartition targetImages
      measureLocalization where
  selectedPartitionAlignment := alignment
  localizedPieceAlignment := localizedPieceAlignment
  compactActive_subset_selected := compactActive_subset_selected
  pieceLower_lt_compactLower :=
    pieceLower_lt_compactLower margins alignment
  compactUpper_lt_pieceUpper :=
    compactUpper_lt_pieceUpper margins alignment

/-- Selected-box margins directly generate localized-piece outer-box data. -/
def toCompactActiveLocalizedPieceOuterBoxData
    (margins :
      SelectedBoxStrictMarginData selectedPartition targetImages
        measureLocalization)
    (alignment : CompactActiveSelectedPartitionAlignment D selectedPartition)
    (localizedPieceAlignment :
      LocalizedInteriorPieceAlignment selectedPartition targetImages
        measureLocalization)
    (compactActive_subset_selected :
      forall x, x ∈ D.finiteActive.active -> x ∈ selectedPartition.active) :
    CompactActiveLocalizedPieceOuterBoxData D selectedPartition targetImages
      measureLocalization :=
  (toCompactActiveLocalizedPieceStrictMargins margins alignment
    localizedPieceAlignment compactActive_subset_selected)
      |>.toLocalizedPieceOuterBoxData

/-- Selected-box margins directly generate strict-buffer constructor data. -/
def toCompactActiveStrictBufferConstructorData
    (margins :
      SelectedBoxStrictMarginData selectedPartition targetImages
        measureLocalization)
    (alignment : CompactActiveSelectedPartitionAlignment D selectedPartition)
    (localizedPieceAlignment :
      LocalizedInteriorPieceAlignment selectedPartition targetImages
        measureLocalization)
    (compactActive_subset_selected :
      forall x, x ∈ D.finiteActive.active -> x ∈ selectedPartition.active) :
    CompactActiveStrictBufferConstructorData D selectedPartition targetImages
      measureLocalization :=
  (toCompactActiveLocalizedPieceStrictMargins margins alignment
    localizedPieceAlignment compactActive_subset_selected)
      |>.toStrictBufferConstructorData

end SelectedBoxStrictMarginData

namespace CompactSupportFiniteActiveSelection

variable {rho : SmoothPartitionOfUnity M I M univ}
variable {K : Set M} {hK : IsCompact K}
variable
    (S : CompactSupportFiniteActiveSelection (I := I) rho K hK omega)
    (smoothness :
      ActiveCompactBoxSmoothness S.finiteActive S.supportData.box omega)
variable {targetImages :
    BoundaryPieceFamilyInput I omega M BoundaryPiece}
variable {measureLocalization :
    M8MeasureLocalizationData I omega
      (S.selectedBoxPartitionOfUnity smoothness) targetImages}

/--
The compact-support selection identifies compact-active and selected active
sets, so selected-box strict margins are enough to build the compact-active
localized-piece margin package.
-/
def toLocalizedPieceStrictMarginsOfSelectedStrictMargins
    (localizedPieceAlignment :
      LocalizedInteriorPieceAlignment (S.selectedBoxPartitionOfUnity smoothness)
        targetImages measureLocalization)
    (margins :
      SelectedBoxStrictMarginData (S.selectedBoxPartitionOfUnity smoothness)
        targetImages measureLocalization) :
    CompactActiveLocalizedPieceStrictMargins S.compactActiveBoxData
      (S.selectedBoxPartitionOfUnity smoothness) targetImages
      measureLocalization :=
  SelectedBoxStrictMarginData.toCompactActiveLocalizedPieceStrictMargins
    margins
    (S.toCompactActiveSelectedPartitionAlignment smoothness)
    localizedPieceAlignment
    (by intro x hx; simpa using hx)

/-- Compact-support route from selected-box margins to localized outer boxes. -/
def toLocalizedPieceOuterBoxDataOfSelectedStrictMargins
    (localizedPieceAlignment :
      LocalizedInteriorPieceAlignment (S.selectedBoxPartitionOfUnity smoothness)
        targetImages measureLocalization)
    (margins :
      SelectedBoxStrictMarginData (S.selectedBoxPartitionOfUnity smoothness)
        targetImages measureLocalization) :
    CompactActiveLocalizedPieceOuterBoxData S.compactActiveBoxData
      (S.selectedBoxPartitionOfUnity smoothness) targetImages
      measureLocalization :=
  (S.toLocalizedPieceStrictMarginsOfSelectedStrictMargins smoothness
    localizedPieceAlignment margins).toLocalizedPieceOuterBoxData

/-- Compact-support route from selected-box margins to strict-buffer data. -/
def toStrictBufferConstructorDataOfSelectedStrictMargins
    (localizedPieceAlignment :
      LocalizedInteriorPieceAlignment (S.selectedBoxPartitionOfUnity smoothness)
        targetImages measureLocalization)
    (margins :
      SelectedBoxStrictMarginData (S.selectedBoxPartitionOfUnity smoothness)
        targetImages measureLocalization) :
    CompactActiveStrictBufferConstructorData S.compactActiveBoxData
      (S.selectedBoxPartitionOfUnity smoothness) targetImages
      measureLocalization :=
  (S.toLocalizedPieceStrictMarginsOfSelectedStrictMargins smoothness
    localizedPieceAlignment margins).toStrictBufferConstructorData

/-- Compact-support route from selected-box margins to strict-buffer alignment. -/
def toCompactActiveBoxStrictBufferAlignmentOfSelectedStrictMargins
    (localizedPieceAlignment :
      LocalizedInteriorPieceAlignment (S.selectedBoxPartitionOfUnity smoothness)
        targetImages measureLocalization)
    (margins :
      SelectedBoxStrictMarginData (S.selectedBoxPartitionOfUnity smoothness)
        targetImages measureLocalization) :
    CompactActiveBoxStrictBufferAlignment S.compactActiveBoxData
      (S.selectedBoxPartitionOfUnity smoothness) targetImages
      measureLocalization :=
  (S.toLocalizedPieceStrictMarginsOfSelectedStrictMargins smoothness
    localizedPieceAlignment margins).toCompactActiveBoxStrictBufferAlignment

end CompactSupportFiniteActiveSelection

section SelectedBoxEndToEnd

variable {alpha : Type a} [TopologicalSpace alpha] [MeasurableSpace alpha]
variable [OpensMeasurableSpace alpha] [T2Space alpha]
variable {muAlpha : Measure alpha} [IsFiniteMeasureOnCompacts muAlpha]
variable {rho : SmoothPartitionOfUnity M I M univ}
variable {K : Set M} {hK : IsCompact K}

namespace CompactSupportSelectedBoxEndToEndData

variable
    (S :
      CompactSupportSelectedBoxEndToEndData
        (α := alpha) (μ := muAlpha) I omega BoundaryPiece rho K hK)

/--
End-to-end selected-box data already carries selected strict margins and the
localized chart alignment, so it can produce compact-active localized-piece
strict margins without extra endpoint fields.
-/
def localizedPieceStrictMargins :
    CompactActiveLocalizedPieceStrictMargins S.compactActiveBoxes
      S.selectedPartition S.targetImageInput.targetImages
      S.measureBuilder.toM8MeasureLocalizationData :=
  SelectedBoxStrictMarginData.toCompactActiveLocalizedPieceStrictMargins
    S.strictMargins
    S.selectedPartitionAlignment
    S.localizedPieceAlignment
    (by
      intro x hx
      simpa [CompactSupportSelectedBoxEndToEndData.selectedPartition,
        CompactSupportSelectedBoxEndToEndData.compactActiveBoxes] using hx)

/-- End-to-end selected-box data as localized-piece outer-box data. -/
def localizedPieceOuterBoxData :
    CompactActiveLocalizedPieceOuterBoxData S.compactActiveBoxes
      S.selectedPartition S.targetImageInput.targetImages
      S.measureBuilder.toM8MeasureLocalizationData :=
  S.localizedPieceStrictMargins.toLocalizedPieceOuterBoxData

/-- End-to-end selected-box data as strict-buffer constructor data. -/
def strictBufferConstructorDataOfSelectedStrictMargins :
    CompactActiveStrictBufferConstructorData S.compactActiveBoxes
      S.selectedPartition S.targetImageInput.targetImages
      S.measureBuilder.toM8MeasureLocalizationData :=
  S.localizedPieceStrictMargins.toStrictBufferConstructorData

end CompactSupportSelectedBoxEndToEndData

end SelectedBoxEndToEnd

section EndpointSources

variable {rho : SmoothPartitionOfUnity M I M univ}
variable {mu : Measure (Fin (n + 1) -> Real)}
variable [IsFiniteMeasureOnCompacts mu]
variable [IsManifold I 1 M]

namespace NaturalCompactSupportEndpointSelectedReconstructionSourceBaseSources

variable
    (S :
      NaturalCompactSupportEndpointSelectedReconstructionSourceBaseSources
        ExtInteriorPiece ExtBoundaryPiece I omega BoundaryPiece rho mu)

/--
Source-packaged endpoint route from selected-box strict margins to compact
active localized-piece strict margins.
-/
def endpointLocalizedPieceStrictMarginsOfSelectedStrictMargins
    (localizedPieceAlignment :
      LocalizedInteriorPieceAlignment
        S.endpointAutoBase.toBaseInput.selectedPartition
        S.endpointAutoBase.toBaseInput.targetImageInput.targetImages
        S.endpointMeasureLocalization)
    (margins : S.EndpointSelectedBoxStrictMargins) :
    CompactActiveLocalizedPieceStrictMargins S.selection.compactActiveBoxData
      S.endpointAutoBase.toBaseInput.selectedPartition
      S.endpointAutoBase.toBaseInput.targetImageInput.targetImages
      S.endpointMeasureLocalization :=
  SelectedBoxStrictMarginData.toCompactActiveLocalizedPieceStrictMargins
    margins
    (by
      change
        CompactActiveSelectedPartitionAlignment S.selection.compactActiveBoxData
          (S.selection.selectedBoxPartitionOfUnity S.smoothness)
      exact S.selection.toCompactActiveSelectedPartitionAlignment S.smoothness)
    localizedPieceAlignment
    (by
      intro x hx
      simpa
        [NaturalCompactSupportEndpointSelectedReconstructionSourceBaseSources.endpointAutoBase]
        using hx)

/-- Source-packaged endpoint route from selected margins to outer-box data. -/
def endpointLocalizedPieceOuterBoxDataOfSelectedStrictMargins
    (localizedPieceAlignment :
      LocalizedInteriorPieceAlignment
        S.endpointAutoBase.toBaseInput.selectedPartition
        S.endpointAutoBase.toBaseInput.targetImageInput.targetImages
        S.endpointMeasureLocalization)
    (margins : S.EndpointSelectedBoxStrictMargins) :
    CompactActiveLocalizedPieceOuterBoxData S.selection.compactActiveBoxData
      S.endpointAutoBase.toBaseInput.selectedPartition
      S.endpointAutoBase.toBaseInput.targetImageInput.targetImages
      S.endpointMeasureLocalization :=
  (S.endpointLocalizedPieceStrictMarginsOfSelectedStrictMargins
    localizedPieceAlignment margins).toLocalizedPieceOuterBoxData

/-- Source-packaged endpoint route from selected margins to strict-buffer data. -/
def endpointStrictBufferConstructorDataOfSelectedStrictMargins
    (localizedPieceAlignment :
      LocalizedInteriorPieceAlignment
        S.endpointAutoBase.toBaseInput.selectedPartition
        S.endpointAutoBase.toBaseInput.targetImageInput.targetImages
        S.endpointMeasureLocalization)
    (margins : S.EndpointSelectedBoxStrictMargins) :
    CompactActiveStrictBufferConstructorData S.selection.compactActiveBoxData
      S.endpointAutoBase.toBaseInput.selectedPartition
      S.endpointAutoBase.toBaseInput.targetImageInput.targetImages
      S.endpointMeasureLocalization :=
  (S.endpointLocalizedPieceStrictMarginsOfSelectedStrictMargins
    localizedPieceAlignment margins).toStrictBufferConstructorData

end NaturalCompactSupportEndpointSelectedReconstructionSourceBaseSources

namespace NaturalCompactSupportEndpointExtDerivBaseSources

variable
    (S :
      NaturalCompactSupportEndpointExtDerivBaseSources
        ExtInteriorPiece ExtBoundaryPiece I omega BoundaryPiece rho mu)

/-- Ext-deriv endpoint route from selected margins to strict-buffer data. -/
def endpointStrictBufferConstructorDataOfSelectedStrictMargins
    (localizedPieceAlignment :
      LocalizedInteriorPieceAlignment
        S.compactSupportEndpointSource.endpointAutoBase.toBaseInput.selectedPartition
        S.compactSupportEndpointSource.endpointAutoBase.toBaseInput.targetImageInput.targetImages
        S.endpointMeasureLocalization)
    (margins :
      SelectedBoxStrictMarginData
        S.compactSupportEndpointSource.endpointAutoBase.toBaseInput.selectedPartition
        S.compactSupportEndpointSource.endpointAutoBase.toBaseInput.targetImageInput.targetImages
        S.endpointMeasureLocalization) :
    CompactActiveStrictBufferConstructorData S.selection.compactActiveBoxData
      S.compactSupportEndpointSource.endpointAutoBase.toBaseInput.selectedPartition
      S.compactSupportEndpointSource.endpointAutoBase.toBaseInput.targetImageInput.targetImages
      S.endpointMeasureLocalization :=
  S.compactSupportEndpointSource
    |>.endpointStrictBufferConstructorDataOfSelectedStrictMargins
      localizedPieceAlignment margins

end NaturalCompactSupportEndpointExtDerivBaseSources

end EndpointSources

end LocalizedPieceStrictMarginsAuto

end Stokes

end
