import Stokes.Global.NaturalFiniteActiveChartBoxSelectionAuto
import Stokes.Global.LocalizedPieceStrictMarginsAuto
import Stokes.Global.CurrentGapReductionAudit

/-!
# Strict alignment from natural finite-active chart-box selections

This module connects the finite-active chart-box selection layer to the current
strict-buffer endpoint input.

Once a `NaturalFiniteActiveChartBoxSelectionData` has chosen the compact
support, active charts, selected boxes, and smoothness neighborhoods, the
selected partition and compact-active boxes are fixed.  The declarations below
project the remaining strict/alignment packages from the still-genuine
measure-side data:

* boundary target and selected bulk measure data;
* chart-label alignment for the localized M8 pieces;
* selected-box strict margins.

No new analytic theorem is hidden here.  The point is to remove repeated
manual passing of `selectedPartitionAlignment`, localized-piece alignment, and
strict-margin projections at endpoint call sites.
-/

noncomputable section

set_option linter.unusedSectionVars false

open Set MeasureTheory
open scoped BigOperators Manifold Topology

namespace Stokes

section NaturalStrictAlignmentFromFiniteSelectionAuto

universe u w b a

variable {H : Type u} [TopologicalSpace H]
variable {M : Type w} [TopologicalSpace M] [ChartedSpace H M]
variable {BoundaryPiece : Type b}
variable {alpha : Type a} [TopologicalSpace alpha] [MeasurableSpace alpha]
variable [OpensMeasurableSpace alpha] [T2Space alpha]
variable {mu : Measure alpha} [IsFiniteMeasureOnCompacts mu]
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) -> Real) H}
variable {omega : ManifoldForm I M n}
variable {rho : SmoothPartitionOfUnity M I M univ}
variable [IsManifold I 1 M]

/--
Finite-active chart-box data plus the remaining measure/strict information
needed to build the current strict-buffer alignment package.

The fields `finiteSelection.formData`, `finiteSelection.selection`, and
`finiteSelection.smoothness` determine the selected partition and compact
active boxes.  Thus callers no longer pass the selected/compact-active
alignment separately.
-/
structure NaturalFiniteActiveStrictAlignmentData
    (I : ModelWithCorners Real (Fin (n + 1) -> Real) H)
    (omega : ManifoldForm I M n)
    (BoundaryPiece : Type b)
    (rho : SmoothPartitionOfUnity M I M univ)
    (mu : Measure alpha) [IsFiniteMeasureOnCompacts mu]
    [IsManifold I 1 M] where
  finiteSelection : NaturalFiniteActiveChartBoxSelectionData I omega rho
  orientedBoundaryAtlas : BoundaryChartOrientedAtlas I M
  targetImageInput :
    M8TargetImageInput I omega
      finiteSelection.selectedPartition orientedBoundaryAtlas BoundaryPiece
  globalBulkIntegral : Real
  bulk :
    BulkMeasureFromPartitionData
      (α := alpha) (μ := mu)
      finiteSelection.selectedPartition targetImageInput.targetImages
      globalBulkIntegral
  boundaryTarget :
    CanonicalBoundaryTargetCompactSupportInput
      (α := alpha) targetImageInput mu
  localizedChartAlignment :
    LocalizedInteriorM8ChartAlignment bulk.localized
  strictMargins :
    SelectedBoxStrictMarginData
      finiteSelection.selectedPartition targetImageInput.targetImages
      (boundaryTarget.toMeasureBuilderData bulk).toM8MeasureLocalizationData

namespace NaturalFiniteActiveStrictAlignmentData

variable
    (D :
      NaturalFiniteActiveStrictAlignmentData
        (alpha := alpha) I omega BoundaryPiece rho mu)

/-- The compactly supported form data fixed by the finite-active selection. -/
abbrev formData : CompactlySupportedSmoothFormData I omega :=
  D.finiteSelection.formData

/-- The selected partition generated by the finite-active chart boxes. -/
abbrev selectedPartition : SelectedBoxPartitionOfUnity I omega :=
  D.finiteSelection.selectedPartition

/-- Compact-active boxes generated by the finite-active selection. -/
abbrev compactActiveBoxes : CompactActiveBoxData I omega :=
  D.finiteSelection.compactActiveBoxData

/-- The measure builder induced by the selected bulk and boundary target data. -/
abbrev measureBuilder :
    CompactSupportMeasureToM8BuilderData
      (α := alpha) I omega D.selectedPartition
      D.targetImageInput.targetImages mu
      D.globalBulkIntegral D.boundaryTarget.globalBoundaryIntegral :=
  D.boundaryTarget.toMeasureBuilderData D.bulk

/--
The selected-partition/compact-active alignment is generated by the finite
selection, so it is no longer a caller-supplied endpoint field.
-/
def selectedPartitionAlignment :
    CompactActiveSelectedPartitionAlignment D.compactActiveBoxes
      D.selectedPartition :=
  D.finiteSelection.selection.toCompactActiveSelectedPartitionAlignment
    D.finiteSelection.smoothness

@[simp]
theorem selectedPartitionAlignment_active_subset :
    D.selectedPartitionAlignment.active_subset =
      (D.finiteSelection.selection.toCompactActiveSelectedPartitionAlignment
        D.finiteSelection.smoothness).active_subset := by
  rfl

/-- Chart-label alignment transported to the M8 measure-localization package. -/
def localizedPieceAlignment :
    LocalizedInteriorPieceAlignment D.selectedPartition
      D.targetImageInput.targetImages D.measureBuilder.toM8MeasureLocalizationData :=
  D.localizedChartAlignment.toPieceAlignment rfl

@[simp]
theorem localizedPieceAlignment_sourceChart_eq :
    D.localizedPieceAlignment.sourceChart_eq =
      (D.localizedChartAlignment.toPieceAlignment
        (measureLocalization := D.measureBuilder.toM8MeasureLocalizationData)
        rfl).sourceChart_eq := by
  rfl

/--
The strict-builder alignment generated from finite-active selected boxes,
localized chart-label alignment, and the packaged selected-box margins.
-/
def toNaturalMeasureStrictBuilderAlignment :
    NaturalMeasureStrictBuilderAlignment D.targetImageInput D.measureBuilder
      D.compactActiveBoxes where
  selectedPartitionAlignment := D.selectedPartitionAlignment
  localizedPieceAlignment := D.localizedPieceAlignment
  outer_lower_lt_selectedLower :=
    D.strictMargins.outer_lower_lt_selectedLower
  selectedUpper_lt_outer_upper :=
    D.strictMargins.selectedUpper_lt_outer_upper
  target_boundaryPartitionTerm_eq_measureBuilder :=
    D.boundaryTarget.target_boundaryPartitionTerm_forMeasureBuilder D.bulk

@[simp]
theorem toNaturalMeasureStrictBuilderAlignment_selectedPartitionAlignment :
    D.toNaturalMeasureStrictBuilderAlignment.selectedPartitionAlignment =
      D.selectedPartitionAlignment := by
  rfl

@[simp]
theorem toNaturalMeasureStrictBuilderAlignment_localizedPieceAlignment :
    D.toNaturalMeasureStrictBuilderAlignment.localizedPieceAlignment =
      D.localizedPieceAlignment := by
  rfl

/--
The localized-piece strict-margin package generated from the same selected-box
margins.  This is the shape consumed by localized outer-box and strict-buffer
constructor routes.
-/
def toCompactActiveLocalizedPieceStrictMargins :
    CompactActiveLocalizedPieceStrictMargins D.compactActiveBoxes
      D.selectedPartition D.targetImageInput.targetImages
      D.measureBuilder.toM8MeasureLocalizationData :=
  D.finiteSelection.selection.toLocalizedPieceStrictMarginsOfSelectedStrictMargins
    D.finiteSelection.smoothness D.localizedPieceAlignment D.strictMargins

/-- Localized outer-box data generated by the finite-selection strict package. -/
def toLocalizedPieceOuterBoxData :
    CompactActiveLocalizedPieceOuterBoxData D.compactActiveBoxes
      D.selectedPartition D.targetImageInput.targetImages
      D.measureBuilder.toM8MeasureLocalizationData :=
  D.toCompactActiveLocalizedPieceStrictMargins.toLocalizedPieceOuterBoxData

/-- Strict-buffer constructor data generated by the finite-selection package. -/
def toStrictBufferConstructorData :
    CompactActiveStrictBufferConstructorData D.compactActiveBoxes
      D.selectedPartition D.targetImageInput.targetImages
      D.measureBuilder.toM8MeasureLocalizationData :=
  D.toCompactActiveLocalizedPieceStrictMargins.toStrictBufferConstructorData

/-- Direct strict-buffer alignment generated by the finite-selection package. -/
def toCompactActiveBoxStrictBufferAlignment :
    CompactActiveBoxStrictBufferAlignment D.compactActiveBoxes
      D.selectedPartition D.targetImageInput.targetImages
      D.measureBuilder.toM8MeasureLocalizationData :=
  D.toCompactActiveLocalizedPieceStrictMargins
    |>.toCompactActiveBoxStrictBufferAlignment

@[simp]
theorem toCompactActiveLocalizedPieceStrictMargins_selectedPartitionAlignment :
    D.toCompactActiveLocalizedPieceStrictMargins.selectedPartitionAlignment =
      D.selectedPartitionAlignment := by
  rfl

@[simp]
theorem toCompactActiveLocalizedPieceStrictMargins_localizedPieceAlignment :
    D.toCompactActiveLocalizedPieceStrictMargins.localizedPieceAlignment =
      D.localizedPieceAlignment := by
  rfl

/-- Glue fields in the audit shape, generated from the finite-active selection. -/
def currentEndpointGlueFields :
    CurrentEndpointGlueFields I omega BoundaryPiece mu where
  formData := D.formData
  orientedBoundaryAtlas := D.orientedBoundaryAtlas
  selectedPartition := D.selectedPartition
  selectedPartition_supportSet := D.finiteSelection.selectedPartition_K
  targetImageInput := D.targetImageInput
  globalBulkIntegral := D.globalBulkIntegral
  compactActiveBoxes := D.compactActiveBoxes

@[simp]
theorem currentEndpointGlueFields_selectedPartition :
    D.currentEndpointGlueFields.selectedPartition = D.selectedPartition := by
  rfl

@[simp]
theorem currentEndpointGlueFields_compactActiveBoxes :
    D.currentEndpointGlueFields.compactActiveBoxes =
      D.compactActiveBoxes := by
  rfl

/--
Current end-to-end input generated from finite-active chart-box selection and
the strict alignment package above.
-/
def toNaturalCompactSupportEndToEndInput :
    NaturalCompactSupportEndToEndInput
      (α := alpha) I omega BoundaryPiece mu :=
  D.currentEndpointGlueFields.toEndToEndInputOfStrictAlignment
    D.bulk D.boundaryTarget D.toNaturalMeasureStrictBuilderAlignment

@[simp]
theorem toNaturalCompactSupportEndToEndInput_selectedPartition :
    D.toNaturalCompactSupportEndToEndInput.selectedPartition =
      D.selectedPartition := by
  rfl

@[simp]
theorem toNaturalCompactSupportEndToEndInput_bulk :
    D.toNaturalCompactSupportEndToEndInput.bulk = D.bulk := by
  rfl

@[simp]
theorem toNaturalCompactSupportEndToEndInput_boundaryTarget :
    D.toNaturalCompactSupportEndToEndInput.boundaryTarget =
      D.boundaryTarget := by
  rfl

@[simp]
theorem toNaturalCompactSupportEndToEndInput_alignment :
    D.toNaturalCompactSupportEndToEndInput.naturalMeasureStrictBuilderAlignment =
      D.toNaturalMeasureStrictBuilderAlignment := by
  rfl

/-- The final natural compact-support input produced by the finite-selection route. -/
def toNaturalCompactSupportStokesInput :
    NaturalCompactSupportStokesInput
      (α := alpha) I omega BoundaryPiece mu :=
  D.toNaturalCompactSupportEndToEndInput.toNaturalCompactSupportStokesInput

@[simp]
theorem toNaturalCompactSupportStokesInput_selectedPartition :
    D.toNaturalCompactSupportStokesInput.selectedPartition =
      D.selectedPartition := by
  rfl

@[simp]
theorem toNaturalCompactSupportStokesInput_measure :
    D.toNaturalCompactSupportStokesInput.measure =
      D.measureBuilder.toCompactSupportToM8MeasureData := by
  rfl

/-- Canonical compact-support Stokes from the finite-selection strict package. -/
theorem canonical_stokes :
    D.toNaturalCompactSupportStokesInput
      |>.canonicalIntegralInterface
      |>.stokesStatement :=
  D.toNaturalCompactSupportEndToEndInput.canonical_stokes

end NaturalFiniteActiveStrictAlignmentData

namespace NaturalFiniteActiveChartBoxSelectionData

variable
    (D : NaturalFiniteActiveChartBoxSelectionData I omega rho)
variable
    (orientedBoundaryAtlas : BoundaryChartOrientedAtlas I M)
    (targetImageInput :
      M8TargetImageInput I omega D.selectedPartition orientedBoundaryAtlas
        BoundaryPiece)
    {globalBulkIntegral : Real}
    (bulk :
      BulkMeasureFromPartitionData
        (α := alpha) (μ := mu)
        D.selectedPartition targetImageInput.targetImages globalBulkIntegral)
    (boundaryTarget :
      CanonicalBoundaryTargetCompactSupportInput
        (α := alpha) targetImageInput mu)

/--
Constructor from finite-active chart boxes plus the remaining strict data.
This is the intended theorem-facing entry point for callers that already built
the selected bulk and boundary-target packages.
-/
def toStrictAlignmentData
    (localizedChartAlignment :
      LocalizedInteriorM8ChartAlignment bulk.localized)
    (strictMargins :
      SelectedBoxStrictMarginData D.selectedPartition
        targetImageInput.targetImages
        (boundaryTarget.toMeasureBuilderData bulk).toM8MeasureLocalizationData) :
    NaturalFiniteActiveStrictAlignmentData
      (alpha := alpha) I omega BoundaryPiece rho mu where
  finiteSelection := D
  orientedBoundaryAtlas := orientedBoundaryAtlas
  targetImageInput := targetImageInput
  globalBulkIntegral := globalBulkIntegral
  bulk := bulk
  boundaryTarget := boundaryTarget
  localizedChartAlignment := localizedChartAlignment
  strictMargins := strictMargins

/--
Finite-active chart boxes generate the natural strict-builder alignment once
the remaining measure route, localized chart-label alignment, and strict
selected-box margins are supplied.
-/
def toNaturalMeasureStrictBuilderAlignment
    (localizedChartAlignment :
      LocalizedInteriorM8ChartAlignment bulk.localized)
    (strictMargins :
      SelectedBoxStrictMarginData D.selectedPartition
        targetImageInput.targetImages
        (boundaryTarget.toMeasureBuilderData bulk).toM8MeasureLocalizationData) :
    NaturalMeasureStrictBuilderAlignment targetImageInput
      (boundaryTarget.toMeasureBuilderData bulk) D.compactActiveBoxData :=
  (D.toStrictAlignmentData
    orientedBoundaryAtlas targetImageInput bulk boundaryTarget
    localizedChartAlignment strictMargins)
    |>.toNaturalMeasureStrictBuilderAlignment

/--
Variant where the selected-box strict margins are generated from an active
inner/outer box selection and the four corner-identification facts.
-/
def toNaturalMeasureStrictBuilderAlignmentOfActiveStrictInnerOuter
    (localizedChartAlignment :
      LocalizedInteriorM8ChartAlignment bulk.localized)
    {coordSupport : M -> Set (Fin (n + 1) -> Real)}
    (boxes :
      ActiveStrictInnerOuterBoxSelections
        D.selectedPartition.active coordSupport)
    (innerLower_eq_selectedLower :
      forall x, x ∈ D.selectedPartition.active ->
        boxes.innerLower x = D.selectedPartition.lower x)
    (innerUpper_eq_selectedUpper :
      forall x, x ∈ D.selectedPartition.active ->
        boxes.innerUpper x = D.selectedPartition.upper x)
    (outerLower_eq_pieceLower :
      forall x, x ∈ D.selectedPartition.active ->
        boxes.outerLower x =
          ((boundaryTarget.toMeasureBuilderData bulk).toM8MeasureLocalizationData
            |>.localizedInterior.piece x).lowerCorner)
    (outerUpper_eq_pieceUpper :
      forall x, x ∈ D.selectedPartition.active ->
        boxes.outerUpper x =
          ((boundaryTarget.toMeasureBuilderData bulk).toM8MeasureLocalizationData
            |>.localizedInterior.piece x).upperCorner) :
    NaturalMeasureStrictBuilderAlignment targetImageInput
      (boundaryTarget.toMeasureBuilderData bulk) D.compactActiveBoxData :=
  D.toNaturalMeasureStrictBuilderAlignment
    orientedBoundaryAtlas targetImageInput bulk boundaryTarget
    localizedChartAlignment
    (SelectedBoxStrictMarginData.ofActiveStrictInnerOuter
      (selectedPartition := D.selectedPartition)
      (targetImages := targetImageInput.targetImages)
      (measureLocalization :=
        (boundaryTarget.toMeasureBuilderData bulk).toM8MeasureLocalizationData)
      boxes innerLower_eq_selectedLower innerUpper_eq_selectedUpper
      outerLower_eq_pieceLower outerUpper_eq_pieceUpper)

/--
Direct end-to-end input constructor from the finite-active chart boxes and the
remaining strict data.
-/
def toNaturalCompactSupportEndToEndInput
    (localizedChartAlignment :
      LocalizedInteriorM8ChartAlignment bulk.localized)
    (strictMargins :
      SelectedBoxStrictMarginData D.selectedPartition
        targetImageInput.targetImages
        (boundaryTarget.toMeasureBuilderData bulk).toM8MeasureLocalizationData) :
    NaturalCompactSupportEndToEndInput
      (α := alpha) I omega BoundaryPiece mu :=
  (D.toStrictAlignmentData
    orientedBoundaryAtlas targetImageInput bulk boundaryTarget
    localizedChartAlignment strictMargins)
    |>.toNaturalCompactSupportEndToEndInput

/--
Canonical compact-support Stokes from natural finite-active chart-box selection
plus the remaining measure/localized-margin data.
-/
theorem canonical_stokes_ofStrictAlignmentData
    (localizedChartAlignment :
      LocalizedInteriorM8ChartAlignment bulk.localized)
    (strictMargins :
      SelectedBoxStrictMarginData D.selectedPartition
        targetImageInput.targetImages
        (boundaryTarget.toMeasureBuilderData bulk).toM8MeasureLocalizationData) :
    ((D.toNaturalCompactSupportEndToEndInput
        orientedBoundaryAtlas targetImageInput bulk boundaryTarget
        localizedChartAlignment strictMargins)
        |>.toNaturalCompactSupportStokesInput
        |>.canonicalIntegralInterface
        |>.stokesStatement) :=
  (D.toStrictAlignmentData
    orientedBoundaryAtlas targetImageInput bulk boundaryTarget
    localizedChartAlignment strictMargins)
    |>.canonical_stokes

end NaturalFiniteActiveChartBoxSelectionData

end NaturalStrictAlignmentFromFiniteSelectionAuto

end Stokes

end
