import Stokes.Global.NaturalBulkFromExtDerivRouteAuto
import Stokes.Global.BulkBoundaryActiveAlignmentAuto
import Stokes.Global.BoundaryUnifiedCanonicalTargetRouteAuto
import Stokes.Global.NaturalCompactSupportOnePackageStokesAuto

/-!
# Natural one-package Stokes inputs from synchronized routes

This module is a thin theorem-facing composition layer.  It starts from the
compact-source chart-box package, the non-bulk endpoint data, and one of the
synchronized bulk routes from `NaturalBulkFromExtDerivRouteAuto`.  The bulk
route supplies the endpoint `boundaryMeasure`; the remaining genuine geometric
inputs are still exposed explicitly as chart alignment plus either selected
strict margins or chart-box containment.

No new analytic or geometric facts are proved here.  The purpose is to remove
manual endpoint assembly while making the remaining assumptions visible.
-/

noncomputable section

set_option linter.style.longLine false
set_option linter.unusedSectionVars false

open Set MeasureTheory
open scoped BigOperators Manifold Topology

namespace Stokes

section NaturalOnePackageFromRoutesAuto

universe u w b ei eb

variable {H : Type u} [TopologicalSpace H]
variable {M : Type w} [TopologicalSpace M] [ChartedSpace H M]
variable {BoundaryPiece : Type b}
variable {ExtInteriorPiece : Type ei} {ExtBoundaryPiece : Type eb}
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) -> Real) H}
variable {omega : ManifoldForm I M n}
variable {rho : SmoothPartitionOfUnity M I M univ}
variable {mu : Measure (Fin (n + 1) -> Real)}
variable [IsFiniteMeasureOnCompacts mu]
variable [IsManifold I 1 M]

/--
Route-packaged one-package input with selected strict margins.

The route supplies the synchronized bulk reconstruction, local facts, and
exterior-derivative measure.  The remaining fields are still the real endpoint
geometry: constructor chart alignment and selected-box strict margins.
-/
structure NaturalOnePackageExtDerivRouteSelectedMarginInput
    (I : ModelWithCorners Real (Fin (n + 1) -> Real) H)
    (omega : ManifoldForm I M n)
    (rho : SmoothPartitionOfUnity M I M univ)
    (ExtInteriorPiece : Type ei)
    (ExtBoundaryPiece : Type eb)
    (BoundaryPiece : Type b)
    (mu : Measure (Fin (n + 1) -> Real))
    [IsFiniteMeasureOnCompacts mu]
    [IsManifold I 1 M] where
  /-- The compactly supported smooth form data. -/
  formData : CompactlySupportedSmoothFormData I omega
  /-- Compact source supports and generated natural chart-box selection. -/
  compactSource :
    CompactlySupportedSmoothFormData.NaturalFiniteActiveFromCompactSupportData
      (rho := rho) formData
  /-- Endpoint data common to the ext-deriv and reconstruction bulk routes. -/
  common :
    NaturalBulkEndpointCommonData
      (I := I) (omega := omega) (rho := rho)
      compactSource.toNaturalFiniteActiveChartBoxSelectionData
      BoundaryPiece mu
  /-- Synchronized ext-deriv constructor route. -/
  route :
    common.ExtDerivConstructorRoute
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
  /-- Constructor chart alignment for the endpoint generated by `route`. -/
  chartAlignment :
    LocalizedInteriorM8ChartAlignment
      ((common.toBoundaryMeasureInputOfExtDerivConstructorRoute route)
        |>.toSelectedReconstructionEndpointSource
        |>.localized)
  /-- Selected-box strict margins for the endpoint generated by `route`. -/
  strictMargins :
    ((common.toBoundaryMeasureInputOfExtDerivConstructorRoute route)
      |>.toSelectedReconstructionEndpointSource
      |>.EndpointSelectedBoxStrictMargins)

namespace NaturalOnePackageExtDerivRouteSelectedMarginInput

variable
    (D :
      NaturalOnePackageExtDerivRouteSelectedMarginInput
        I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu)

/-- Natural chart-box data generated by the compact-source package. -/
abbrev chartBoxes : NaturalFiniteActiveChartBoxSelectionData I omega rho :=
  D.compactSource.toNaturalFiniteActiveChartBoxSelectionData

/-- Endpoint boundary/measure data generated by the synchronized ext-deriv route. -/
def boundaryMeasure :
    NaturalCompactSupportEndpointNaturalBoundaryMeasureInput
      (I := I) (omega := omega) (rho := rho)
      D.chartBoxes ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  D.common.toBoundaryMeasureInputOfExtDerivConstructorRoute
    (ExtInteriorPiece := ExtInteriorPiece)
    (ExtBoundaryPiece := ExtBoundaryPiece)
    D.route

/-- Forget the route wrapper to the current one-package Stokes input. -/
def toOnePackageStokesInput :
    NaturalCompactSupportOnePackageStokesInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu where
  formData := D.formData
  compactSource := D.compactSource
  boundaryMeasure := D.boundaryMeasure
  chartAlignment := D.chartAlignment
  strictMargins := D.strictMargins

@[simp]
theorem toOnePackageStokesInput_boundaryMeasure :
    D.toOnePackageStokesInput.boundaryMeasure = D.boundaryMeasure := by
  rfl

/-- Canonical compact-support Stokes from the route-packaged selected-margin input. -/
theorem canonical_stokes :
    D.toOnePackageStokesInput.canonicalIntegralInterface.stokesStatement :=
  NaturalCompactSupportOnePackageStokesInput.canonical_stokes
    D.toOnePackageStokesInput

/-- Equality form of compact-support Stokes from the route-packaged input. -/
theorem manifoldExtDerivIntegral_eq_boundaryFormIntegral :
    D.toOnePackageStokesInput.canonicalIntegralInterface.manifoldExtDerivIntegral =
      D.toOnePackageStokesInput.canonicalIntegralInterface.boundaryFormIntegral :=
  NaturalCompactSupportOnePackageStokesInput.manifoldExtDerivIntegral_eq_boundaryFormIntegral
    D.toOnePackageStokesInput

end NaturalOnePackageExtDerivRouteSelectedMarginInput

/--
Route-packaged one-package input with chart-box containment.

This is the preferred shape when strict margins are generated from selected
chart boxes rather than supplied directly.
-/
structure NaturalOnePackageExtDerivRouteChartBoxInput
    (I : ModelWithCorners Real (Fin (n + 1) -> Real) H)
    (omega : ManifoldForm I M n)
    (rho : SmoothPartitionOfUnity M I M univ)
    (ExtInteriorPiece : Type ei)
    (ExtBoundaryPiece : Type eb)
    (BoundaryPiece : Type b)
    (mu : Measure (Fin (n + 1) -> Real))
    [IsFiniteMeasureOnCompacts mu]
    [IsManifold I 1 M] where
  /-- The compactly supported smooth form data. -/
  formData : CompactlySupportedSmoothFormData I omega
  /-- Compact source supports and generated natural chart-box selection. -/
  compactSource :
    CompactlySupportedSmoothFormData.NaturalFiniteActiveFromCompactSupportData
      (rho := rho) formData
  /-- Endpoint data common to the ext-deriv and reconstruction bulk routes. -/
  common :
    NaturalBulkEndpointCommonData
      (I := I) (omega := omega) (rho := rho)
      compactSource.toNaturalFiniteActiveChartBoxSelectionData
      BoundaryPiece mu
  /-- Synchronized ext-deriv constructor route. -/
  route :
    common.ExtDerivConstructorRoute
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
  /-- Constructor chart alignment for the endpoint generated by `route`. -/
  chartAlignment :
    LocalizedInteriorM8ChartAlignment
      ((common.toBoundaryMeasureInputOfExtDerivConstructorRoute route)
        |>.toSelectedReconstructionEndpointSource
        |>.localized)
  /-- Chart-box containment that generates selected strict margins. -/
  containment :
    ((common.toBoundaryMeasureInputOfExtDerivConstructorRoute route)
      |>.StrictAlignmentChartBoxContainmentData)

namespace NaturalOnePackageExtDerivRouteChartBoxInput

variable
    (D :
      NaturalOnePackageExtDerivRouteChartBoxInput
        I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu)

/-- Natural chart-box data generated by the compact-source package. -/
abbrev chartBoxes : NaturalFiniteActiveChartBoxSelectionData I omega rho :=
  D.compactSource.toNaturalFiniteActiveChartBoxSelectionData

/-- Endpoint boundary/measure data generated by the synchronized ext-deriv route. -/
def boundaryMeasure :
    NaturalCompactSupportEndpointNaturalBoundaryMeasureInput
      (I := I) (omega := omega) (rho := rho)
      D.chartBoxes ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  D.common.toBoundaryMeasureInputOfExtDerivConstructorRoute
    (ExtInteriorPiece := ExtInteriorPiece)
    (ExtBoundaryPiece := ExtBoundaryPiece)
    D.route

/-- Forget the route wrapper to the chart-box one-package Stokes input. -/
def toOnePackageChartBoxStokesInput :
    NaturalCompactSupportOnePackageChartBoxStokesInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu where
  formData := D.formData
  compactSource := D.compactSource
  boundaryMeasure := D.boundaryMeasure
  chartAlignment := D.chartAlignment
  containment := D.containment

/-- Selected-margin input obtained from the chart-box route wrapper. -/
def toOnePackageStokesInput :
    NaturalCompactSupportOnePackageStokesInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  D.toOnePackageChartBoxStokesInput.toSelectedMarginInput

@[simp]
theorem toOnePackageChartBoxStokesInput_boundaryMeasure :
    D.toOnePackageChartBoxStokesInput.boundaryMeasure = D.boundaryMeasure := by
  rfl

/-- Canonical compact-support Stokes from the route-packaged chart-box input. -/
theorem canonical_stokes :
    D.toOnePackageChartBoxStokesInput.canonicalIntegralInterface.stokesStatement :=
  NaturalCompactSupportOnePackageChartBoxStokesInput.canonical_stokes
    D.toOnePackageChartBoxStokesInput

/-- Equality form of compact-support Stokes from the route-packaged chart-box input. -/
theorem manifoldExtDerivIntegral_eq_boundaryFormIntegral :
    D.toOnePackageChartBoxStokesInput.canonicalIntegralInterface.manifoldExtDerivIntegral =
      D.toOnePackageChartBoxStokesInput.canonicalIntegralInterface.boundaryFormIntegral :=
  NaturalCompactSupportOnePackageChartBoxStokesInput.manifoldExtDerivIntegral_eq_boundaryFormIntegral
    D.toOnePackageChartBoxStokesInput

end NaturalOnePackageExtDerivRouteChartBoxInput

/-- Route-packaged reconstruction input with selected strict margins. -/
structure NaturalOnePackageReconstructionRouteSelectedMarginInput
    (I : ModelWithCorners Real (Fin (n + 1) -> Real) H)
    (omega : ManifoldForm I M n)
    (rho : SmoothPartitionOfUnity M I M univ)
    (ExtInteriorPiece : Type ei)
    (ExtBoundaryPiece : Type eb)
    (BoundaryPiece : Type b)
    (mu : Measure (Fin (n + 1) -> Real))
    [IsFiniteMeasureOnCompacts mu]
    [IsManifold I 1 M] where
  /-- The compactly supported smooth form data. -/
  formData : CompactlySupportedSmoothFormData I omega
  /-- Compact source supports and generated natural chart-box selection. -/
  compactSource :
    CompactlySupportedSmoothFormData.NaturalFiniteActiveFromCompactSupportData
      (rho := rho) formData
  /-- Endpoint data common to the ext-deriv and reconstruction bulk routes. -/
  common :
    NaturalBulkEndpointCommonData
      (I := I) (omega := omega) (rho := rho)
      compactSource.toNaturalFiniteActiveChartBoxSelectionData
      BoundaryPiece mu
  /-- Synchronized reconstruction route. -/
  route :
    common.ReconstructionRoute
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
  /-- Constructor chart alignment for the endpoint generated by `route`. -/
  chartAlignment :
    LocalizedInteriorM8ChartAlignment
      ((common.toBoundaryMeasureInputOfReconstructionRoute route)
        |>.toSelectedReconstructionEndpointSource
        |>.localized)
  /-- Selected-box strict margins for the endpoint generated by `route`. -/
  strictMargins :
    ((common.toBoundaryMeasureInputOfReconstructionRoute route)
      |>.toSelectedReconstructionEndpointSource
      |>.EndpointSelectedBoxStrictMargins)

namespace NaturalOnePackageReconstructionRouteSelectedMarginInput

variable
    (D :
      NaturalOnePackageReconstructionRouteSelectedMarginInput
        I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu)

/-- Natural chart-box data generated by the compact-source package. -/
abbrev chartBoxes : NaturalFiniteActiveChartBoxSelectionData I omega rho :=
  D.compactSource.toNaturalFiniteActiveChartBoxSelectionData

/-- Endpoint boundary/measure data generated by the synchronized reconstruction route. -/
def boundaryMeasure :
    NaturalCompactSupportEndpointNaturalBoundaryMeasureInput
      (I := I) (omega := omega) (rho := rho)
      D.chartBoxes ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  D.common.toBoundaryMeasureInputOfReconstructionRoute
    (ExtInteriorPiece := ExtInteriorPiece)
    (ExtBoundaryPiece := ExtBoundaryPiece)
    D.route

/-- Forget the route wrapper to the current one-package Stokes input. -/
def toOnePackageStokesInput :
    NaturalCompactSupportOnePackageStokesInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu where
  formData := D.formData
  compactSource := D.compactSource
  boundaryMeasure := D.boundaryMeasure
  chartAlignment := D.chartAlignment
  strictMargins := D.strictMargins

@[simp]
theorem toOnePackageStokesInput_boundaryMeasure :
    D.toOnePackageStokesInput.boundaryMeasure = D.boundaryMeasure := by
  rfl

/-- Canonical compact-support Stokes from the reconstruction selected-margin input. -/
theorem canonical_stokes :
    D.toOnePackageStokesInput.canonicalIntegralInterface.stokesStatement :=
  NaturalCompactSupportOnePackageStokesInput.canonical_stokes
    D.toOnePackageStokesInput

/-- Equality form of compact-support Stokes from the reconstruction selected-margin input. -/
theorem manifoldExtDerivIntegral_eq_boundaryFormIntegral :
    D.toOnePackageStokesInput.canonicalIntegralInterface.manifoldExtDerivIntegral =
      D.toOnePackageStokesInput.canonicalIntegralInterface.boundaryFormIntegral :=
  NaturalCompactSupportOnePackageStokesInput.manifoldExtDerivIntegral_eq_boundaryFormIntegral
    D.toOnePackageStokesInput

end NaturalOnePackageReconstructionRouteSelectedMarginInput

/-- Route-packaged reconstruction input with chart-box containment. -/
structure NaturalOnePackageReconstructionRouteChartBoxInput
    (I : ModelWithCorners Real (Fin (n + 1) -> Real) H)
    (omega : ManifoldForm I M n)
    (rho : SmoothPartitionOfUnity M I M univ)
    (ExtInteriorPiece : Type ei)
    (ExtBoundaryPiece : Type eb)
    (BoundaryPiece : Type b)
    (mu : Measure (Fin (n + 1) -> Real))
    [IsFiniteMeasureOnCompacts mu]
    [IsManifold I 1 M] where
  /-- The compactly supported smooth form data. -/
  formData : CompactlySupportedSmoothFormData I omega
  /-- Compact source supports and generated natural chart-box selection. -/
  compactSource :
    CompactlySupportedSmoothFormData.NaturalFiniteActiveFromCompactSupportData
      (rho := rho) formData
  /-- Endpoint data common to the ext-deriv and reconstruction bulk routes. -/
  common :
    NaturalBulkEndpointCommonData
      (I := I) (omega := omega) (rho := rho)
      compactSource.toNaturalFiniteActiveChartBoxSelectionData
      BoundaryPiece mu
  /-- Synchronized reconstruction route. -/
  route :
    common.ReconstructionRoute
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
  /-- Constructor chart alignment for the endpoint generated by `route`. -/
  chartAlignment :
    LocalizedInteriorM8ChartAlignment
      ((common.toBoundaryMeasureInputOfReconstructionRoute route)
        |>.toSelectedReconstructionEndpointSource
        |>.localized)
  /-- Chart-box containment that generates selected strict margins. -/
  containment :
    ((common.toBoundaryMeasureInputOfReconstructionRoute route)
      |>.StrictAlignmentChartBoxContainmentData)

namespace NaturalOnePackageReconstructionRouteChartBoxInput

variable
    (D :
      NaturalOnePackageReconstructionRouteChartBoxInput
        I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu)

/-- Natural chart-box data generated by the compact-source package. -/
abbrev chartBoxes : NaturalFiniteActiveChartBoxSelectionData I omega rho :=
  D.compactSource.toNaturalFiniteActiveChartBoxSelectionData

/-- Endpoint boundary/measure data generated by the synchronized reconstruction route. -/
def boundaryMeasure :
    NaturalCompactSupportEndpointNaturalBoundaryMeasureInput
      (I := I) (omega := omega) (rho := rho)
      D.chartBoxes ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  D.common.toBoundaryMeasureInputOfReconstructionRoute
    (ExtInteriorPiece := ExtInteriorPiece)
    (ExtBoundaryPiece := ExtBoundaryPiece)
    D.route

/-- Forget the route wrapper to the chart-box one-package Stokes input. -/
def toOnePackageChartBoxStokesInput :
    NaturalCompactSupportOnePackageChartBoxStokesInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu where
  formData := D.formData
  compactSource := D.compactSource
  boundaryMeasure := D.boundaryMeasure
  chartAlignment := D.chartAlignment
  containment := D.containment

/-- Selected-margin input obtained from the chart-box route wrapper. -/
def toOnePackageStokesInput :
    NaturalCompactSupportOnePackageStokesInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  D.toOnePackageChartBoxStokesInput.toSelectedMarginInput

@[simp]
theorem toOnePackageChartBoxStokesInput_boundaryMeasure :
    D.toOnePackageChartBoxStokesInput.boundaryMeasure = D.boundaryMeasure := by
  rfl

/-- Canonical compact-support Stokes from the reconstruction chart-box input. -/
theorem canonical_stokes :
    D.toOnePackageChartBoxStokesInput.canonicalIntegralInterface.stokesStatement :=
  NaturalCompactSupportOnePackageChartBoxStokesInput.canonical_stokes
    D.toOnePackageChartBoxStokesInput

/-- Equality form of compact-support Stokes from the reconstruction chart-box input. -/
theorem manifoldExtDerivIntegral_eq_boundaryFormIntegral :
    D.toOnePackageChartBoxStokesInput.canonicalIntegralInterface.manifoldExtDerivIntegral =
      D.toOnePackageChartBoxStokesInput.canonicalIntegralInterface.boundaryFormIntegral :=
  NaturalCompactSupportOnePackageChartBoxStokesInput.manifoldExtDerivIntegral_eq_boundaryFormIntegral
    D.toOnePackageChartBoxStokesInput

end NaturalOnePackageReconstructionRouteChartBoxInput

end NaturalOnePackageFromRoutesAuto

end Stokes

end
