import Stokes.Global.NaturalFiniteActiveFromCompactSupportAuto
import Stokes.Global.NaturalEndpointStrictAlignmentRouteAuto

/-!
# One-package compact-support Stokes inputs

This module is a theorem-facing wrapper around the natural compact-support
endpoint route.

The point is not to discharge the remaining geometric hypotheses.  Instead we
name the next main entry shape: a compactly supported smooth form, its
compact-source/finite-active chart-box data, the boundary/measure package over
the generated selected partition, and the remaining strict-alignment input.

The file deliberately avoids depending on later experimental modules whose
names are still moving; it only uses the stable natural finite-active and
strict-alignment routes.
-/

noncomputable section

set_option linter.style.longLine false
set_option linter.unusedSectionVars false

open Set MeasureTheory
open scoped BigOperators Manifold Topology

namespace Stokes

section NaturalCompactSupportOnePackageStokesAuto

universe u w b ei eb

variable {H : Type u} [TopologicalSpace H]
variable {M : Type w} [TopologicalSpace M] [ChartedSpace H M]
variable {BoundaryPiece : Type b}
variable {ExtInteriorPiece : Type ei} {ExtBoundaryPiece : Type eb}
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) -> Real) H}
variable {omega : ManifoldForm I M n}
variable {rho : SmoothPartitionOfUnity M I M univ}
variable {mu : Measure (Fin (n + 1) -> Real)}
variable [IsFiniteMeasureOnCompacts mu]
variable [IsManifold I 1 M]

/--
One theorem-facing package for the current natural compact-support endpoint.

`compactSource` packages the finite-active chart-box construction from compact
source supports.  `boundaryMeasure` contains the remaining bulk and boundary
measure data over the selected partition generated from `compactSource`.
`chartAlignment` and `strictMargins` are the remaining strict-alignment
geometry consumed by the endpoint theorem.
-/
structure NaturalCompactSupportOnePackageStokesInput
    (I : ModelWithCorners Real (Fin (n + 1) -> Real) H)
    (omega : ManifoldForm I M n)
    (rho : SmoothPartitionOfUnity M I M univ)
    (ExtInteriorPiece : Type ei)
    (ExtBoundaryPiece : Type eb)
    (BoundaryPiece : Type b)
    (mu : Measure (Fin (n + 1) -> Real))
    [IsFiniteMeasureOnCompacts mu]
    [IsManifold I 1 M] where
  /-- The compactly supported smooth form data. -/
  formData : CompactlySupportedSmoothFormData I omega
  /-- Compact source supports, selected boxes, and chart-box smoothness data. -/
  compactSource :
    CompactlySupportedSmoothFormData.NaturalFiniteActiveFromCompactSupportData
      (rho := rho) formData
  /-- Boundary and measure data over the selected partition generated above. -/
  boundaryMeasure :
    NaturalCompactSupportEndpointNaturalBoundaryMeasureInput
      (I := I) (omega := omega) (rho := rho)
      compactSource.toNaturalFiniteActiveChartBoxSelectionData
      ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu
  /-- Localized interior chart alignment for the endpoint M8 route. -/
  chartAlignment :
    LocalizedInteriorM8ChartAlignment
      boundaryMeasure.toSelectedReconstructionEndpointSource.localized
  /-- Strict selected-box margins for the endpoint theorem. -/
  strictMargins :
    boundaryMeasure.toSelectedReconstructionEndpointSource.EndpointSelectedBoxStrictMargins

namespace NaturalCompactSupportOnePackageStokesInput

variable
    (D :
      NaturalCompactSupportOnePackageStokesInput
        I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu)

/-- The finite-active set induced by the packaged compact support. -/
abbrev finiteActive : FiniteActiveOnCompact (M := M) I :=
  D.formData.finiteActiveOnSupport (rho := rho)

/-- Natural finite-active chart-box data generated by the compact-source package. -/
abbrev chartBoxes : NaturalFiniteActiveChartBoxSelectionData I omega rho :=
  D.compactSource.toNaturalFiniteActiveChartBoxSelectionData

/-- The selected partition generated by the one-package input. -/
abbrev selectedPartition : SelectedBoxPartitionOfUnity I omega :=
  D.chartBoxes.selectedPartition

/-- The ordinary natural endpoint input obtained by forgetting the one-package wrapper. -/
def toNaturalEndpointInput :
    NaturalCompactSupportEndpointNaturalInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu where
  chartBoxes := D.chartBoxes
  boundaryMeasure := D.boundaryMeasure

@[simp]
theorem toNaturalEndpointInput_chartBoxes :
    D.toNaturalEndpointInput.chartBoxes = D.chartBoxes := by
  rfl

@[simp]
theorem toNaturalEndpointInput_boundaryMeasure :
    D.toNaturalEndpointInput.boundaryMeasure = D.boundaryMeasure := by
  rfl

/-- Canonical integral interface exposed by the one-package input. -/
abbrev canonicalIntegralInterface : CanonicalIntegralInterface I omega :=
  D.boundaryMeasure.canonicalIntegralInterface

/-- Compact-support Stokes in canonical statement form from the one-package input. -/
theorem canonical_stokes :
    D.canonicalIntegralInterface.stokesStatement :=
  D.boundaryMeasure.canonical_stokes_ofM8ChartAlignmentAndStrictMargins
    D.chartAlignment D.strictMargins

/-- Compact-support Stokes displayed as the canonical equality. -/
theorem manifoldExtDerivIntegral_eq_boundaryFormIntegral :
    D.canonicalIntegralInterface.manifoldExtDerivIntegral =
      D.canonicalIntegralInterface.boundaryFormIntegral :=
  D.boundaryMeasure.manifoldExtDerivIntegral_eq_boundaryFormIntegral_ofM8ChartAlignmentAndStrictMargins
    D.chartAlignment D.strictMargins

end NaturalCompactSupportOnePackageStokesInput

/--
Variant whose last strict-margin input is supplied by chart-box containment.

This is the higher-level shape expected from actual chart-box selection:
containment is converted to selected strict margins by
`NaturalEndpointStrictAlignmentRouteAuto`.
-/
structure NaturalCompactSupportOnePackageChartBoxStokesInput
    (I : ModelWithCorners Real (Fin (n + 1) -> Real) H)
    (omega : ManifoldForm I M n)
    (rho : SmoothPartitionOfUnity M I M univ)
    (ExtInteriorPiece : Type ei)
    (ExtBoundaryPiece : Type eb)
    (BoundaryPiece : Type b)
    (mu : Measure (Fin (n + 1) -> Real))
    [IsFiniteMeasureOnCompacts mu]
    [IsManifold I 1 M] where
  /-- The compactly supported smooth form data. -/
  formData : CompactlySupportedSmoothFormData I omega
  /-- Compact source supports, selected boxes, and chart-box smoothness data. -/
  compactSource :
    CompactlySupportedSmoothFormData.NaturalFiniteActiveFromCompactSupportData
      (rho := rho) formData
  /-- Boundary and measure data over the selected partition generated above. -/
  boundaryMeasure :
    NaturalCompactSupportEndpointNaturalBoundaryMeasureInput
      (I := I) (omega := omega) (rho := rho)
      compactSource.toNaturalFiniteActiveChartBoxSelectionData
      ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu
  /-- Localized interior chart alignment for the endpoint M8 route. -/
  chartAlignment :
    LocalizedInteriorM8ChartAlignment
      boundaryMeasure.toSelectedReconstructionEndpointSource.localized
  /-- Chart-box containment that generates the selected strict margins. -/
  containment : boundaryMeasure.StrictAlignmentChartBoxContainmentData

namespace NaturalCompactSupportOnePackageChartBoxStokesInput

variable
    (D :
      NaturalCompactSupportOnePackageChartBoxStokesInput
        I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu)

/-- Natural finite-active chart-box data generated by the compact-source package. -/
abbrev chartBoxes : NaturalFiniteActiveChartBoxSelectionData I omega rho :=
  D.compactSource.toNaturalFiniteActiveChartBoxSelectionData

/-- Selected strict margins generated from chart-box containment. -/
def strictMargins :
    D.boundaryMeasure.toSelectedReconstructionEndpointSource.EndpointSelectedBoxStrictMargins :=
  D.boundaryMeasure.selectedStrictMarginsOfChartBoxContainment D.containment

/-- Forget chart-box containment to the selected-margin one-package input. -/
def toSelectedMarginInput :
    NaturalCompactSupportOnePackageStokesInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu where
  formData := D.formData
  compactSource := D.compactSource
  boundaryMeasure := D.boundaryMeasure
  chartAlignment := D.chartAlignment
  strictMargins := D.strictMargins

/-- Canonical integral interface exposed by the chart-box one-package input. -/
abbrev canonicalIntegralInterface : CanonicalIntegralInterface I omega :=
  D.boundaryMeasure.canonicalIntegralInterface

/-- Compact-support Stokes in canonical statement form from chart-box containment. -/
theorem canonical_stokes :
    D.canonicalIntegralInterface.stokesStatement :=
  D.boundaryMeasure
    |>.canonical_stokes_ofM8ChartAlignmentAndChartBoxContainmentStrictAlignment
      D.chartAlignment D.containment

/-- Compact-support Stokes displayed as the canonical equality. -/
theorem manifoldExtDerivIntegral_eq_boundaryFormIntegral :
    D.canonicalIntegralInterface.manifoldExtDerivIntegral =
      D.canonicalIntegralInterface.boundaryFormIntegral :=
  D.boundaryMeasure
    |>.manifoldExtDerivIntegral_eq_boundaryFormIntegral_ofM8ChartAlignmentAndChartBoxContainmentStrictAlignment
      D.chartAlignment D.containment

end NaturalCompactSupportOnePackageChartBoxStokesInput

end NaturalCompactSupportOnePackageStokesAuto

end Stokes

end
