import Stokes.Global.NaturalBulkEndpointCommonFromUnifiedAuto
import Stokes.Global.OnePackageRouteFromLocalizedPiecesAuto
import Stokes.Global.CompactSourceStrictContainmentRouteAuto
import Stokes.Global.BoundaryCanonicalRouteFromUnifiedSupportFiniteAuto

/-!
# Mega route for natural compact-support Stokes

This module is a theorem-facing composition layer for the current natural
compact-support route.

The input shape is intentionally close to the mathematical data now left on the
critical path:

* a compactly supported smooth form;
* compact-source finite-active chart-box data;
* unified boundary data, used both as `NaturalBulkEndpointCommonData` and as a
  support-finite canonical boundary route;
* a synchronized bulk route, either through the exterior-derivative constructor
  or through reconstruction;
* localized-piece equalities and chart-box containment, which generate the
  remaining chart alignment and strict margins.

No new analytic or geometric hypothesis is invented here.  Every theorem below
is obtained by routing the existing API through these larger packages.
-/

noncomputable section

set_option linter.style.longLine false
set_option linter.unusedSectionVars false

open Set MeasureTheory
open scoped BigOperators Manifold Topology

namespace Stokes

section NaturalCompactSupportRouteMegaAuto

universe u w b ei eb

variable {H : Type u} [TopologicalSpace H]
variable {M : Type w} [TopologicalSpace M] [ChartedSpace H M]
variable {BoundaryPiece : Type b}
variable {ExtInteriorPiece : Type ei} {ExtBoundaryPiece : Type eb}
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) -> Real) H}
variable {omega : ManifoldForm I M n}
variable {rho : SmoothPartitionOfUnity M I M univ}
variable {mu : Measure (Fin (n + 1) -> Real)}
variable [IsFiniteMeasureOnCompacts mu]
variable [IsManifold I 1 M]

/--
Common compact-support route data shared by the ext-deriv and reconstruction
mega inputs.

`unified` is the endpoint-facing unified boundary package; it projects to
`NaturalBulkEndpointCommonData` for the synchronized bulk route.  The additional
`supportFinite` field records the stronger support-finite boundary route facts
over the same unified project-local boundary data.
-/
structure NaturalCompactSupportRouteMegaBase
    (I : ModelWithCorners Real (Fin (n + 1) -> Real) H)
    (omega : ManifoldForm I M n)
    (rho : SmoothPartitionOfUnity M I M univ)
    (BoundaryPiece : Type b)
    (mu : Measure (Fin (n + 1) -> Real))
    [IsFiniteMeasureOnCompacts mu]
    [IsManifold I 1 M] where
  /-- Compactly supported smooth form data. -/
  formData : CompactlySupportedSmoothFormData I omega
  /-- Compact support, finite active charts, and selected chart boxes. -/
  compactSource :
    CompactlySupportedSmoothFormData.NaturalFiniteActiveFromCompactSupportData
      (I := I) (omega := omega) (rho := rho) formData
  /-- Unified boundary package over the selected partition generated above. -/
  unified :
    NaturalBulkEndpointUnifiedInput
      (I := I) (omega := omega) (rho := rho)
      compactSource.toNaturalFiniteActiveChartBoxSelectionData
      BoundaryPiece mu
  /-- Support-finite boundary reconstruction facts for the same unified route. -/
  supportFinite :
    ProjectLocalBoundarySupportFiniteMeasureFacts
      unified.boundaryUnified.toProjectLocalGlobalStokesData

namespace NaturalCompactSupportRouteMegaBase

variable
    (B :
      NaturalCompactSupportRouteMegaBase
        I omega rho BoundaryPiece mu)

/-- The finite-active chart-box package generated by the compact source. -/
abbrev chartBoxes : NaturalFiniteActiveChartBoxSelectionData I omega rho :=
  B.compactSource.toNaturalFiniteActiveChartBoxSelectionData

/-- The selected partition generated by the compact-source data. -/
abbrev selectedPartition : SelectedBoxPartitionOfUnity I omega :=
  B.chartBoxes.selectedPartition

/-- The oriented boundary atlas carried by the unified input. -/
abbrev orientedBoundaryAtlas : BoundaryChartOrientedAtlas I M :=
  B.unified.orientedBoundaryAtlas

/-- The unified boundary source package carried by the base input. -/
abbrev boundaryUnified :
    BoundarySourceAlignmentUnifiedData
      (I := I) (omega := omega)
      (selectedPartition := B.selectedPartition)
      (orientedBoundaryAtlas := B.orientedBoundaryAtlas)
      (BoundaryPiece := BoundaryPiece) :=
  B.unified.boundaryUnified

/-- The endpoint common data consumed by synchronized bulk routes. -/
def common :
    NaturalBulkEndpointCommonData
      (I := I) (omega := omega) (rho := rho)
      B.chartBoxes BoundaryPiece mu :=
  B.unified.toCommonData

/-- Localized interior M8 data carried by the unified endpoint input. -/
abbrev localized :
    LocalizedInteriorM8Fields I omega B.selectedPartition :=
  B.unified.localized

/-- Boundary face-continuity facts carried by the unified endpoint input. -/
abbrev boundaryFaceContinuity :
    ProjectLocalBoundaryCanonicalFaceContinuityData
      B.boundaryUnified.toProjectLocalGlobalStokesData :=
  B.unified.boundaryFaceContinuity

/-- Boundary chart-change data carried by the unified endpoint input. -/
abbrev boundaryChartChange :
    BoundaryChartChangeSelectedFamilyData
      B.boundaryUnified.toProjectLocalGlobalStokesData :=
  B.unified.boundaryChartChange

/-- Support-finite canonical boundary route data over the same unified package. -/
def supportFiniteRouteData :
    BoundarySourceAlignmentUnifiedData.BoundaryCanonicalRouteFromUnifiedSupportFiniteData
      B.boundaryUnified where
  supportFinite := B.supportFinite
  faceContinuity := B.boundaryFaceContinuity

/-- Natural support-finite controlled-target input for the boundary side. -/
def boundaryNaturalSupportFiniteInput :
    BoundaryCanonicalTargetNaturalSupportFiniteInput
      B.boundaryUnified.toM8BoundaryControlledTargetInput
      B.boundaryUnified.toProjectLocalGlobalStokesData :=
  B.supportFiniteRouteData.toNaturalSupportFiniteInput

/-- Canonical boundary route generated by the support-finite unified data. -/
def boundaryCanonicalRouteMeasureInput :
    BoundaryCanonicalRouteMeasureInput
      B.boundaryUnified.toM8BoundaryControlledTargetInput.toM8TargetImageInput
      B.boundaryUnified.toProjectLocalGlobalStokesData :=
  B.supportFiniteRouteData.toBoundaryCanonicalRouteMeasureInput

/-- Global-measure view of the same canonical boundary route. -/
def globalBoundaryCanonicalRouteMeasureInput :
    BoundaryCanonicalRouteMeasureInput
      B.boundaryUnified.toM8BoundaryControlledTargetInput.toM8TargetImageInput
      B.boundaryUnified.toProjectLocalGlobalStokesData :=
  B.supportFiniteRouteData.toGlobalBoundaryCanonicalRouteMeasureInput

/-- Compact-support canonical boundary target package generated by the base input. -/
def canonicalBoundaryTargetCompactSupportInput :
    CanonicalBoundaryTargetCompactSupportInput
      (α := Fin n -> Real)
      B.boundaryUnified.toM8BoundaryControlledTargetInput.toM8TargetImageInput
      (volume : Measure (Fin n -> Real)) :=
  B.supportFiniteRouteData.toCanonicalBoundaryTargetCompactSupportInput

/-- Boundary-only M8 measure data generated by the support-finite route. -/
def m8BoundaryMeasureData :
    M8BoundaryMeasureData I omega B.selectedPartition
      B.boundaryUnified.toM8BoundaryControlledTargetInput.toM8TargetImageInput.targetImages :=
  B.supportFiniteRouteData.toM8BoundaryMeasureData

@[simp]
theorem common_boundaryUnified :
    B.common.boundaryUnified = B.boundaryUnified := by
  rfl

@[simp]
theorem common_localized :
    B.common.localized = B.localized := by
  rfl

@[simp]
theorem common_measure_eq_volume :
    B.common.measure_eq_volume = B.unified.measure_eq_volume := by
  rfl

@[simp]
theorem common_boundaryFaceContinuity :
    B.common.boundaryFaceContinuity = B.boundaryFaceContinuity := by
  rfl

@[simp]
theorem common_boundaryChartChange :
    B.common.boundaryChartChange = B.boundaryChartChange := by
  rfl

@[simp]
theorem supportFiniteRouteData_supportFinite :
    B.supportFiniteRouteData.supportFinite = B.supportFinite := by
  rfl

@[simp]
theorem supportFiniteRouteData_faceContinuity :
    B.supportFiniteRouteData.faceContinuity = B.boundaryFaceContinuity := by
  rfl

@[simp]
theorem boundaryNaturalSupportFiniteInput_supportFinite :
    B.boundaryNaturalSupportFiniteInput.supportFinite = B.supportFinite := by
  rfl

@[simp]
theorem boundaryNaturalSupportFiniteInput_faceContinuity :
    B.boundaryNaturalSupportFiniteInput.faceContinuity =
      B.boundaryFaceContinuity := by
  rfl

@[simp]
theorem boundaryCanonicalRouteMeasureInput_sourceAlignment :
    B.boundaryCanonicalRouteMeasureInput.sourceAlignment =
      B.boundaryUnified.toControlledBoundaryCanonicalProjectLocalFields.sourceAlignment := by
  rfl

@[simp]
theorem globalBoundaryCanonicalRouteMeasureInput_sourceAlignment :
    B.globalBoundaryCanonicalRouteMeasureInput.sourceAlignment =
      B.boundaryUnified.toControlledBoundaryCanonicalProjectLocalFields.sourceAlignment := by
  rfl

@[simp]
theorem m8BoundaryMeasureData_boundaryPartitionTerm :
    B.m8BoundaryMeasureData.boundaryPartitionTerm =
      B.boundaryUnified.toM8BoundaryControlledTargetInput.toM8TargetImageInput.assembly.boundaryPartitionTerm := by
  rfl

@[simp]
theorem m8BoundaryMeasureData_boundaryMeasureIntegral :
    B.m8BoundaryMeasureData.boundaryMeasureIntegral =
      B.boundaryCanonicalRouteMeasureInput.projectLocal.boundaryMeasureIntegral := by
  rfl

end NaturalCompactSupportRouteMegaBase

/--
Mega compact-support input for the exterior-derivative constructor route.

The raw common data, chart alignment, selected strict margins, and one-package
Stokes input are all generated from the fields below.
-/
structure NaturalCompactSupportExtDerivRouteMegaInput
    (I : ModelWithCorners Real (Fin (n + 1) -> Real) H)
    (omega : ManifoldForm I M n)
    (rho : SmoothPartitionOfUnity M I M univ)
    (ExtInteriorPiece : Type ei)
    (ExtBoundaryPiece : Type eb)
    (BoundaryPiece : Type b)
    (mu : Measure (Fin (n + 1) -> Real))
    [IsFiniteMeasureOnCompacts mu]
    [IsManifold I 1 M] where
  /-- Shared compact-support and unified-boundary data. -/
  base : NaturalCompactSupportRouteMegaBase I omega rho BoundaryPiece mu
  /-- Synchronized exterior-derivative constructor route. -/
  route :
    base.common.ExtDerivConstructorRoute
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
  /-- Equality between natural localized pieces and the route-localized M8 pieces. -/
  localizedPieces :
    NaturalFiniteActiveLocalizedPieceEqData
      base.chartBoxes
      (((base.common.toBoundaryMeasureInputOfExtDerivConstructorRoute
            (ExtInteriorPiece := ExtInteriorPiece)
            (ExtBoundaryPiece := ExtBoundaryPiece)
            route)
          |>.toSelectedReconstructionEndpointSource)
        |>.localized)
  /-- Chart-box containment that generates selected strict margins. -/
  containment :
    ((base.common.toBoundaryMeasureInputOfExtDerivConstructorRoute
        (ExtInteriorPiece := ExtInteriorPiece)
        (ExtBoundaryPiece := ExtBoundaryPiece)
        route)
      |>.StrictAlignmentChartBoxContainmentData)

namespace NaturalCompactSupportExtDerivRouteMegaInput

variable
    (D :
      NaturalCompactSupportExtDerivRouteMegaInput
        I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu)

/-- Compactly supported smooth form data. -/
abbrev formData : CompactlySupportedSmoothFormData I omega :=
  D.base.formData

/-- Compact-source finite-active chart-box data. -/
abbrev compactSource :
    CompactlySupportedSmoothFormData.NaturalFiniteActiveFromCompactSupportData
      (I := I) (omega := omega) (rho := rho) D.formData :=
  D.base.compactSource

/-- Natural chart-box selection generated by the compact source. -/
abbrev chartBoxes : NaturalFiniteActiveChartBoxSelectionData I omega rho :=
  D.base.chartBoxes

/-- Selected partition generated by the compact source. -/
abbrev selectedPartition : SelectedBoxPartitionOfUnity I omega :=
  D.base.selectedPartition

/-- Unified endpoint input carried by the base package. -/
abbrev unified :
    NaturalBulkEndpointUnifiedInput
      (I := I) (omega := omega) (rho := rho)
      D.chartBoxes BoundaryPiece mu :=
  D.base.unified

/-- Common endpoint data consumed by the ext-deriv route. -/
def common :
    NaturalBulkEndpointCommonData
      (I := I) (omega := omega) (rho := rho)
      D.chartBoxes BoundaryPiece mu :=
  D.base.common

/-- Boundary/measure package generated by the synchronized ext-deriv route. -/
def boundaryMeasure :
    NaturalCompactSupportEndpointNaturalBoundaryMeasureInput
      (I := I) (omega := omega) (rho := rho)
      D.chartBoxes ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  D.common.toBoundaryMeasureInputOfExtDerivConstructorRoute
    (ExtInteriorPiece := ExtInteriorPiece)
    (ExtBoundaryPiece := ExtBoundaryPiece)
    D.route

/-- Full natural endpoint input generated by the route. -/
def naturalEndpointInput :
    NaturalCompactSupportEndpointNaturalInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  D.chartBoxes.toNaturalEndpointInputOfExtDerivConstructorRoute D.common D.route

/-- Localized chart alignment generated from localized-piece equality data. -/
def chartAlignment :
    LocalizedInteriorM8ChartAlignment
      D.boundaryMeasure.toSelectedReconstructionEndpointSource.localized :=
  D.localizedPieces.toLocalizedInteriorM8ChartAlignment

/-- Strict margins generated by chart-box containment. -/
def strictMargins :
    D.boundaryMeasure.toSelectedReconstructionEndpointSource.EndpointSelectedBoxStrictMargins :=
  D.boundaryMeasure.selectedStrictMarginsOfChartBoxContainment D.containment

/-- Route-packaged chart-box input generated from the mega package. -/
def toNaturalOnePackageRouteChartBoxInput :
    NaturalOnePackageExtDerivRouteChartBoxInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  NaturalOnePackageExtDerivRouteChartBoxInput.ofLocalizedPieces
    (I := I) (omega := omega) (rho := rho)
    (ExtInteriorPiece := ExtInteriorPiece)
    (ExtBoundaryPiece := ExtBoundaryPiece)
    (BoundaryPiece := BoundaryPiece) (mu := mu)
    D.formData D.compactSource D.common D.route
    D.localizedPieces D.containment

/-- Route-packaged selected-margin input generated from chart-box containment. -/
def toNaturalOnePackageRouteSelectedMarginInput :
    NaturalOnePackageExtDerivRouteSelectedMarginInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  NaturalOnePackageExtDerivRouteSelectedMarginInput.ofLocalizedPieces
    (I := I) (omega := omega) (rho := rho)
    (ExtInteriorPiece := ExtInteriorPiece)
    (ExtBoundaryPiece := ExtBoundaryPiece)
    (BoundaryPiece := BoundaryPiece) (mu := mu)
    D.formData D.compactSource D.common D.route
    D.localizedPieces D.strictMargins

/-- One-package chart-box Stokes input generated by the ext-deriv route. -/
def toOnePackageChartBoxStokesInput :
    NaturalCompactSupportOnePackageChartBoxStokesInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  D.toNaturalOnePackageRouteChartBoxInput.toOnePackageChartBoxStokesInput

/-- Same one-package chart-box input, routed through the compact-source containment API. -/
def toCompactSourceOnePackageChartBoxStokesInput :
    NaturalCompactSupportOnePackageChartBoxStokesInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  D.compactSource.toOnePackageChartBoxStokesInputOfStrictContainment
    D.boundaryMeasure D.chartAlignment D.containment

/-- One-package selected-margin Stokes input generated from chart-box containment. -/
def toOnePackageStokesInput :
    NaturalCompactSupportOnePackageStokesInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  D.toOnePackageChartBoxStokesInput.toSelectedMarginInput

/-- Canonical integral interface exposed by the generated endpoint. -/
abbrev canonicalIntegralInterface : CanonicalIntegralInterface I omega :=
  D.boundaryMeasure.canonicalIntegralInterface

@[simp]
theorem common_boundaryUnified :
    D.common.boundaryUnified = D.unified.boundaryUnified := by
  rfl

@[simp]
theorem common_localized :
    D.common.localized = D.unified.localized := by
  rfl

@[simp]
theorem boundaryMeasure_reconstructionSource :
    D.boundaryMeasure.reconstructionSource =
      D.route.selectedReconstructionSource := by
  rfl

@[simp]
theorem boundaryMeasure_extDerivMeasure :
    D.boundaryMeasure.extDerivMeasure = D.route.measure := by
  rfl

@[simp]
theorem boundaryMeasure_bulkLocalFacts :
    D.boundaryMeasure.bulkLocalFacts = D.route.localFacts := by
  rfl

@[simp]
theorem naturalEndpointInput_chartBoxes :
    D.naturalEndpointInput.chartBoxes = D.chartBoxes := by
  rfl

@[simp]
theorem naturalEndpointInput_boundaryMeasure :
    D.naturalEndpointInput.boundaryMeasure = D.boundaryMeasure := by
  rfl

@[simp]
theorem toNaturalOnePackageRouteChartBoxInput_formData :
    D.toNaturalOnePackageRouteChartBoxInput.formData = D.formData := by
  rfl

@[simp]
theorem toNaturalOnePackageRouteChartBoxInput_compactSource :
    D.toNaturalOnePackageRouteChartBoxInput.compactSource =
      D.compactSource := by
  rfl

@[simp]
theorem toNaturalOnePackageRouteChartBoxInput_common :
    D.toNaturalOnePackageRouteChartBoxInput.common = D.common := by
  rfl

@[simp]
theorem toNaturalOnePackageRouteChartBoxInput_route :
    D.toNaturalOnePackageRouteChartBoxInput.route = D.route := by
  rfl

@[simp]
theorem toNaturalOnePackageRouteChartBoxInput_chartAlignment :
    D.toNaturalOnePackageRouteChartBoxInput.chartAlignment =
      D.chartAlignment := by
  rfl

@[simp]
theorem toNaturalOnePackageRouteChartBoxInput_containment :
    D.toNaturalOnePackageRouteChartBoxInput.containment =
      D.containment := by
  rfl

@[simp]
theorem toNaturalOnePackageRouteSelectedMarginInput_strictMargins :
    D.toNaturalOnePackageRouteSelectedMarginInput.strictMargins =
      D.strictMargins := by
  rfl

@[simp]
theorem toOnePackageChartBoxStokesInput_boundaryMeasure :
    D.toOnePackageChartBoxStokesInput.boundaryMeasure =
      D.boundaryMeasure := by
  rfl

@[simp]
theorem toOnePackageChartBoxStokesInput_chartAlignment :
    D.toOnePackageChartBoxStokesInput.chartAlignment =
      D.chartAlignment := by
  rfl

@[simp]
theorem toOnePackageChartBoxStokesInput_containment :
    D.toOnePackageChartBoxStokesInput.containment =
      D.containment := by
  rfl

@[simp]
theorem toOnePackageStokesInput_strictMargins :
    D.toOnePackageStokesInput.strictMargins = D.strictMargins := by
  rfl

@[simp]
theorem toCompactSourceOnePackageChartBoxStokesInput_boundaryMeasure :
    D.toCompactSourceOnePackageChartBoxStokesInput.boundaryMeasure =
      D.boundaryMeasure := by
  rfl

@[simp]
theorem toCompactSourceOnePackageChartBoxStokesInput_containment :
    D.toCompactSourceOnePackageChartBoxStokesInput.containment =
      D.containment := by
  rfl

/-- Canonical compact-support Stokes from the ext-deriv mega route. -/
theorem canonical_stokes :
    D.canonicalIntegralInterface.stokesStatement :=
  NaturalCompactSupportOnePackageChartBoxStokesInput.canonical_stokes
    D.toOnePackageChartBoxStokesInput

/-- Equality form of compact-support Stokes from the ext-deriv mega route. -/
theorem manifoldExtDerivIntegral_eq_boundaryFormIntegral :
    D.canonicalIntegralInterface.manifoldExtDerivIntegral =
      D.canonicalIntegralInterface.boundaryFormIntegral :=
  NaturalCompactSupportOnePackageChartBoxStokesInput.manifoldExtDerivIntegral_eq_boundaryFormIntegral
    D.toOnePackageChartBoxStokesInput

/-- Canonical compact-support Stokes using the compact-source containment route. -/
theorem canonical_stokes_viaCompactSource :
    D.boundaryMeasure.canonicalIntegralInterface.stokesStatement :=
  D.compactSource.canonical_stokes_ofStrictContainment
    D.boundaryMeasure D.chartAlignment D.containment

/-- Equality form using the compact-source containment route. -/
theorem manifoldExtDerivIntegral_eq_boundaryFormIntegral_viaCompactSource :
    D.boundaryMeasure.canonicalIntegralInterface.manifoldExtDerivIntegral =
      D.boundaryMeasure.canonicalIntegralInterface.boundaryFormIntegral :=
  D.compactSource.manifoldExtDerivIntegral_eq_boundaryFormIntegral_ofStrictContainment
    D.boundaryMeasure D.chartAlignment D.containment

end NaturalCompactSupportExtDerivRouteMegaInput

/--
Mega compact-support input for the reconstruction route.

This has the same surface as `NaturalCompactSupportExtDerivRouteMegaInput`, but
the synchronized bulk route is supplied by reconstruction and then projected to
the ext-deriv constructor route internally by the existing API.
-/
structure NaturalCompactSupportReconstructionRouteMegaInput
    (I : ModelWithCorners Real (Fin (n + 1) -> Real) H)
    (omega : ManifoldForm I M n)
    (rho : SmoothPartitionOfUnity M I M univ)
    (ExtInteriorPiece : Type ei)
    (ExtBoundaryPiece : Type eb)
    (BoundaryPiece : Type b)
    (mu : Measure (Fin (n + 1) -> Real))
    [IsFiniteMeasureOnCompacts mu]
    [IsManifold I 1 M] where
  /-- Shared compact-support and unified-boundary data. -/
  base : NaturalCompactSupportRouteMegaBase I omega rho BoundaryPiece mu
  /-- Synchronized reconstruction route. -/
  route :
    base.common.ReconstructionRoute
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
  /-- Equality between natural localized pieces and the route-localized M8 pieces. -/
  localizedPieces :
    NaturalFiniteActiveLocalizedPieceEqData
      base.chartBoxes
      (((base.common.toBoundaryMeasureInputOfReconstructionRoute
            (ExtInteriorPiece := ExtInteriorPiece)
            (ExtBoundaryPiece := ExtBoundaryPiece)
            route)
          |>.toSelectedReconstructionEndpointSource)
        |>.localized)
  /-- Chart-box containment that generates selected strict margins. -/
  containment :
    ((base.common.toBoundaryMeasureInputOfReconstructionRoute
        (ExtInteriorPiece := ExtInteriorPiece)
        (ExtBoundaryPiece := ExtBoundaryPiece)
        route)
      |>.StrictAlignmentChartBoxContainmentData)

namespace NaturalCompactSupportReconstructionRouteMegaInput

variable
    (D :
      NaturalCompactSupportReconstructionRouteMegaInput
        I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu)

/-- Compactly supported smooth form data. -/
abbrev formData : CompactlySupportedSmoothFormData I omega :=
  D.base.formData

/-- Compact-source finite-active chart-box data. -/
abbrev compactSource :
    CompactlySupportedSmoothFormData.NaturalFiniteActiveFromCompactSupportData
      (I := I) (omega := omega) (rho := rho) D.formData :=
  D.base.compactSource

/-- Natural chart-box selection generated by the compact source. -/
abbrev chartBoxes : NaturalFiniteActiveChartBoxSelectionData I omega rho :=
  D.base.chartBoxes

/-- Selected partition generated by the compact source. -/
abbrev selectedPartition : SelectedBoxPartitionOfUnity I omega :=
  D.base.selectedPartition

/-- Unified endpoint input carried by the base package. -/
abbrev unified :
    NaturalBulkEndpointUnifiedInput
      (I := I) (omega := omega) (rho := rho)
      D.chartBoxes BoundaryPiece mu :=
  D.base.unified

/-- Common endpoint data consumed by the reconstruction route. -/
def common :
    NaturalBulkEndpointCommonData
      (I := I) (omega := omega) (rho := rho)
      D.chartBoxes BoundaryPiece mu :=
  D.base.common

/-- Boundary/measure package generated by the synchronized reconstruction route. -/
def boundaryMeasure :
    NaturalCompactSupportEndpointNaturalBoundaryMeasureInput
      (I := I) (omega := omega) (rho := rho)
      D.chartBoxes ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  D.common.toBoundaryMeasureInputOfReconstructionRoute
    (ExtInteriorPiece := ExtInteriorPiece)
    (ExtBoundaryPiece := ExtBoundaryPiece)
    D.route

/-- Full natural endpoint input generated by the reconstruction route. -/
def naturalEndpointInput :
    NaturalCompactSupportEndpointNaturalInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  D.chartBoxes.toNaturalEndpointInputOfReconstructionRoute D.common D.route

/-- Localized chart alignment generated from localized-piece equality data. -/
def chartAlignment :
    LocalizedInteriorM8ChartAlignment
      D.boundaryMeasure.toSelectedReconstructionEndpointSource.localized :=
  D.localizedPieces.toLocalizedInteriorM8ChartAlignment

/-- Strict margins generated by chart-box containment. -/
def strictMargins :
    D.boundaryMeasure.toSelectedReconstructionEndpointSource.EndpointSelectedBoxStrictMargins :=
  D.boundaryMeasure.selectedStrictMarginsOfChartBoxContainment D.containment

/-- Route-packaged chart-box input generated from the reconstruction mega package. -/
def toNaturalOnePackageRouteChartBoxInput :
    NaturalOnePackageReconstructionRouteChartBoxInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  NaturalOnePackageReconstructionRouteChartBoxInput.ofLocalizedPieces
    (I := I) (omega := omega) (rho := rho)
    (ExtInteriorPiece := ExtInteriorPiece)
    (ExtBoundaryPiece := ExtBoundaryPiece)
    (BoundaryPiece := BoundaryPiece) (mu := mu)
    D.formData D.compactSource D.common D.route
    D.localizedPieces D.containment

/-- Route-packaged selected-margin input generated from chart-box containment. -/
def toNaturalOnePackageRouteSelectedMarginInput :
    NaturalOnePackageReconstructionRouteSelectedMarginInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  NaturalOnePackageReconstructionRouteSelectedMarginInput.ofLocalizedPieces
    (I := I) (omega := omega) (rho := rho)
    (ExtInteriorPiece := ExtInteriorPiece)
    (ExtBoundaryPiece := ExtBoundaryPiece)
    (BoundaryPiece := BoundaryPiece) (mu := mu)
    D.formData D.compactSource D.common D.route
    D.localizedPieces D.strictMargins

/-- One-package chart-box Stokes input generated by the reconstruction route. -/
def toOnePackageChartBoxStokesInput :
    NaturalCompactSupportOnePackageChartBoxStokesInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  D.toNaturalOnePackageRouteChartBoxInput.toOnePackageChartBoxStokesInput

/-- Same one-package chart-box input, routed through the compact-source containment API. -/
def toCompactSourceOnePackageChartBoxStokesInput :
    NaturalCompactSupportOnePackageChartBoxStokesInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  D.compactSource.toOnePackageChartBoxStokesInputOfStrictContainment
    D.boundaryMeasure D.chartAlignment D.containment

/-- One-package selected-margin Stokes input generated from chart-box containment. -/
def toOnePackageStokesInput :
    NaturalCompactSupportOnePackageStokesInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  D.toOnePackageChartBoxStokesInput.toSelectedMarginInput

/-- Canonical integral interface exposed by the generated endpoint. -/
abbrev canonicalIntegralInterface : CanonicalIntegralInterface I omega :=
  D.boundaryMeasure.canonicalIntegralInterface

@[simp]
theorem common_boundaryUnified :
    D.common.boundaryUnified = D.unified.boundaryUnified := by
  rfl

@[simp]
theorem common_localized :
    D.common.localized = D.unified.localized := by
  rfl

@[simp]
theorem boundaryMeasure_reconstructionSource :
    D.boundaryMeasure.reconstructionSource =
      D.route.selectedReconstructionSource := by
  rfl

@[simp]
theorem boundaryMeasure_extDerivMeasure :
    D.boundaryMeasure.extDerivMeasure = D.route.measure := by
  rfl

@[simp]
theorem boundaryMeasure_bulkLocalFacts :
    D.boundaryMeasure.bulkLocalFacts = D.route.localFacts := by
  rfl

@[simp]
theorem naturalEndpointInput_chartBoxes :
    D.naturalEndpointInput.chartBoxes = D.chartBoxes := by
  rfl

@[simp]
theorem naturalEndpointInput_boundaryMeasure :
    D.naturalEndpointInput.boundaryMeasure = D.boundaryMeasure := by
  rfl

@[simp]
theorem toNaturalOnePackageRouteChartBoxInput_formData :
    D.toNaturalOnePackageRouteChartBoxInput.formData = D.formData := by
  rfl

@[simp]
theorem toNaturalOnePackageRouteChartBoxInput_compactSource :
    D.toNaturalOnePackageRouteChartBoxInput.compactSource =
      D.compactSource := by
  rfl

@[simp]
theorem toNaturalOnePackageRouteChartBoxInput_common :
    D.toNaturalOnePackageRouteChartBoxInput.common = D.common := by
  rfl

@[simp]
theorem toNaturalOnePackageRouteChartBoxInput_route :
    D.toNaturalOnePackageRouteChartBoxInput.route = D.route := by
  rfl

@[simp]
theorem toNaturalOnePackageRouteChartBoxInput_chartAlignment :
    D.toNaturalOnePackageRouteChartBoxInput.chartAlignment =
      D.chartAlignment := by
  rfl

@[simp]
theorem toNaturalOnePackageRouteChartBoxInput_containment :
    D.toNaturalOnePackageRouteChartBoxInput.containment =
      D.containment := by
  rfl

@[simp]
theorem toNaturalOnePackageRouteSelectedMarginInput_strictMargins :
    D.toNaturalOnePackageRouteSelectedMarginInput.strictMargins =
      D.strictMargins := by
  rfl

@[simp]
theorem toOnePackageChartBoxStokesInput_boundaryMeasure :
    D.toOnePackageChartBoxStokesInput.boundaryMeasure =
      D.boundaryMeasure := by
  rfl

@[simp]
theorem toOnePackageChartBoxStokesInput_chartAlignment :
    D.toOnePackageChartBoxStokesInput.chartAlignment =
      D.chartAlignment := by
  rfl

@[simp]
theorem toOnePackageChartBoxStokesInput_containment :
    D.toOnePackageChartBoxStokesInput.containment =
      D.containment := by
  rfl

@[simp]
theorem toOnePackageStokesInput_strictMargins :
    D.toOnePackageStokesInput.strictMargins = D.strictMargins := by
  rfl

@[simp]
theorem toCompactSourceOnePackageChartBoxStokesInput_boundaryMeasure :
    D.toCompactSourceOnePackageChartBoxStokesInput.boundaryMeasure =
      D.boundaryMeasure := by
  rfl

@[simp]
theorem toCompactSourceOnePackageChartBoxStokesInput_containment :
    D.toCompactSourceOnePackageChartBoxStokesInput.containment =
      D.containment := by
  rfl

/-- Canonical compact-support Stokes from the reconstruction mega route. -/
theorem canonical_stokes :
    D.canonicalIntegralInterface.stokesStatement :=
  NaturalCompactSupportOnePackageChartBoxStokesInput.canonical_stokes
    D.toOnePackageChartBoxStokesInput

/-- Equality form of compact-support Stokes from the reconstruction mega route. -/
theorem manifoldExtDerivIntegral_eq_boundaryFormIntegral :
    D.canonicalIntegralInterface.manifoldExtDerivIntegral =
      D.canonicalIntegralInterface.boundaryFormIntegral :=
  NaturalCompactSupportOnePackageChartBoxStokesInput.manifoldExtDerivIntegral_eq_boundaryFormIntegral
    D.toOnePackageChartBoxStokesInput

/-- Canonical compact-support Stokes using the compact-source containment route. -/
theorem canonical_stokes_viaCompactSource :
    D.boundaryMeasure.canonicalIntegralInterface.stokesStatement :=
  D.compactSource.canonical_stokes_ofStrictContainment
    D.boundaryMeasure D.chartAlignment D.containment

/-- Equality form using the compact-source containment route. -/
theorem manifoldExtDerivIntegral_eq_boundaryFormIntegral_viaCompactSource :
    D.boundaryMeasure.canonicalIntegralInterface.manifoldExtDerivIntegral =
      D.boundaryMeasure.canonicalIntegralInterface.boundaryFormIntegral :=
  D.compactSource.manifoldExtDerivIntegral_eq_boundaryFormIntegral_ofStrictContainment
    D.boundaryMeasure D.chartAlignment D.containment

end NaturalCompactSupportReconstructionRouteMegaInput

end NaturalCompactSupportRouteMegaAuto

end Stokes

end
