import Stokes.Global.CompactSupportEndpointFacade
import Stokes.Global.NaturalCompactSupportInputCollapse

/-!
# Natural compact-support selected-partition constructors

This module is the compact-support/partition counterpart of the endpoint
facades.  It packages the natural input layer

* compactly supported smooth form data,
* a smooth partition of unity,
* the finite-active compact chart-box selection, and
* smoothness for the selected boxes,

and derives the routine selected-partition fields consumed by the current
global endpoint route.

The point is not to choose endpoint margins or strict outer boxes.  Instead the
constructors below remove repeated theorem-facing support bookkeeping:
`selectedPartition.K = formData.supportSet`,
`ManifoldForm.support I omega ⊆ selectedPartition.K`, and the selected
partition-local eventual/ext-derivative packages are all generated from the
same compact-support selection.
-/

noncomputable section

set_option linter.unusedSectionVars false

open Set MeasureTheory
open scoped BigOperators Manifold Topology

namespace Stokes

section NaturalCompactSupportPartitionConstructorAuto

universe u w cb pb ei eb b

variable {H : Type u} [TopologicalSpace H]
variable {M : Type w} [TopologicalSpace M] [ChartedSpace H M]
variable {BoundaryChart : Type cb} {BoundaryPiece : Type pb}
variable {ExtInteriorPiece : Type ei} {ExtBoundaryPiece : Type eb}
variable {BoundaryPiece' : Type b}
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) -> Real) H}
variable {omega : ManifoldForm I M n}
variable {rho : SmoothPartitionOfUnity M I M univ}
variable {mu : Measure (Fin (n + 1) -> Real)}
variable [IsFiniteMeasureOnCompacts mu]
variable [IsManifold I 1 M]

/--
Natural constructor data for the selected partition attached to a compactly
supported form.

The selected partition is always built over `formData.supportSet`, so support
compatibility is definitional after projection.  This record intentionally
stops before endpoint margin/outer-box data.
-/
structure NaturalCompactSupportPartitionConstructorData
    (I : ModelWithCorners Real (Fin (n + 1) -> Real) H)
    (omega : ManifoldForm I M n)
    (rho : SmoothPartitionOfUnity M I M univ) where
  /-- Compactly supported smooth input form. -/
  formData : CompactlySupportedSmoothFormData I omega
  /-- Finite active compact chart-box selection over the form support. -/
  selection :
    CompactSupportFiniteActiveSelection
      (I := I) rho formData.supportSet formData.isCompact_supportSet omega
  /-- Smoothness data upgrading selected compact boxes to extended boxes. -/
  smoothness :
    ActiveCompactBoxSmoothness selection.finiteActive
      selection.supportData.box omega

namespace NaturalCompactSupportPartitionConstructorData

variable
    (D : NaturalCompactSupportPartitionConstructorData I omega rho)

/-- The canonical compact support set selected from the input form data. -/
abbrev supportSet : Set M :=
  D.formData.supportSet

/-- Compactness of the canonical compact support set. -/
abbrev isCompact_supportSet : IsCompact D.supportSet :=
  D.formData.isCompact_supportSet

/-- The finite-active package generated by the selected compact support data. -/
abbrev finiteActive : FiniteActiveOnCompact (M := M) I :=
  D.selection.finiteActive

/-- Compact active boxes generated by the compact-support selection. -/
abbrev compactActiveBoxData : CompactActiveBoxData I omega :=
  D.selection.compactActiveBoxData

/-- Extended compact active boxes after adding smoothness. -/
abbrev compactActiveExtendedBoxData : CompactActiveExtendedBoxData I omega :=
  D.selection.compactActiveExtendedBoxData D.smoothness

/-- The selected partition of unity and selected boxes generated by the data. -/
abbrev selectedPartition : SelectedBoxPartitionOfUnity I omega :=
  D.selection.selectedBoxPartitionOfUnity D.smoothness

@[simp]
theorem selectedPartition_eq :
    D.selectedPartition =
      D.selection.selectedBoxPartitionOfUnity D.smoothness := by
  rfl

/--
The selected partition is controlled by the compact support set carried by the
input form data.  This is the support-set equality that many downstream M8
constructors ask for explicitly.
-/
@[simp]
theorem selectedPartition_supportSet :
    D.selectedPartition.K = D.formData.supportSet := by
  rfl

/-- The selected partition active set is the canonical finite-active set. -/
@[simp]
theorem selectedPartition_active :
    D.selectedPartition.active =
      (FiniteActiveOnCompact.ofCompact rho D.formData.supportSet
        D.formData.isCompact_supportSet).active := by
  rfl

/-- The selected partition uses the input smooth partition of unity. -/
@[simp]
theorem selectedPartition_partition :
    D.selectedPartition.partition = rho := by
  rfl

/--
The original form support is contained in the selected partition support set.
This is the main support-containment field repeatedly consumed downstream.
-/
theorem omegaSupport_subset_selected :
    ManifoldForm.support I omega ⊆ D.selectedPartition.K := by
  simpa [D.selectedPartition_supportSet] using
    D.formData.support_subset_supportSet

/-- The compact-active boxes and selected partition are definitionally aligned. -/
def compactActiveSelectedPartitionAlignment :
    CompactActiveSelectedPartitionAlignment D.compactActiveBoxData
      D.selectedPartition :=
  D.selection.toCompactActiveSelectedPartitionAlignment D.smoothness

/-- Localized compact boxes induced by the selected compact active boxes. -/
abbrev activeLocalizedCompactBoxData :
    ActiveLocalizedCompactBoxData D.finiteActive omega :=
  D.compactActiveBoxData.toActiveLocalizedCompactBoxData

/-- Active localized chart representatives are supported in the selected boxes. -/
theorem localized_tsupport_subset_selectedBox
    {i : M} (hi : i ∈ D.selectedPartition.active) :
    tsupport
        (ManifoldForm.transitionPullbackInChart I i i
          (ManifoldForm.localizedForm I (D.selectedPartition.partition i) omega)) ⊆
      Set.Icc (D.selectedPartition.lower i) (D.selectedPartition.upper i) :=
  D.selectedPartition.localized_tsupport_subset_Icc hi

/--
Eventually-local reconstruction data generated from the selected partition and
the compact support of `omega`.
-/
def localizedEventually :
    LocalizedFormEventuallyEqData I omega M :=
  D.selectedPartition.toLocalizedFormEventuallyEqData
    D.omegaSupport_subset_selected

@[simp]
theorem localizedEventually_activeCharts :
    D.localizedEventually.activeCharts = D.selectedPartition.active := by
  rfl

@[simp]
theorem localizedEventually_supportSet :
    D.localizedEventually.supportSet = D.selectedPartition.K := by
  rfl

/--
The selected combined interior/boundary localized-eventual package, with the
support containment supplied by the constructor data.
-/
def bulkSelectedLocalizedEventually
    (boundary : BoundaryPieceFamilyInput I omega BoundaryChart BoundaryPiece) :
    PartitionLocalizedEventuallyFields I omega (M ⊕ BoundaryChart) :=
  D.selectedPartition.bulkSelectedLocalizedEventually
    (BoundaryChart := BoundaryChart) boundary D.omegaSupport_subset_selected

@[simp]
theorem bulkSelectedLocalizedEventually_activeCharts
    (boundary : BoundaryPieceFamilyInput I omega BoundaryChart BoundaryPiece) :
    (D.bulkSelectedLocalizedEventually boundary).activeCharts =
      selectedPartitionBulkActive D.selectedPartition boundary := by
  rfl

@[simp]
theorem bulkSelectedLocalizedEventually_coefficient
    (boundary : BoundaryPieceFamilyInput I omega BoundaryChart BoundaryPiece) :
    (D.bulkSelectedLocalizedEventually boundary).coefficient =
      selectedPartitionBulkCoefficient
        (BoundaryChart := BoundaryChart) D.selectedPartition := by
  rfl

/--
Support-local exterior-derivative data from selected reconstruction data, with
the selected support containment generated by `D`.
-/
def extDerivOnSupportOfReconstruction
    (boundary : BoundaryPieceFamilyInput I omega BoundaryChart BoundaryPiece)
    (R :
      PartitionReconstructionData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (hactive :
      selectedPartitionBulkActive D.selectedPartition boundary =
        R.activeCharts) :
    ExtDerivOnSupportData I omega (M ⊕ BoundaryChart)
      ExtInteriorPiece ExtBoundaryPiece :=
  ExtDerivOnSupportData.ofSelectedPartitionReconstructionData
    (P := D.selectedPartition) (boundary := boundary)
    (ExtInteriorPiece := ExtInteriorPiece)
    (ExtBoundaryPiece := ExtBoundaryPiece)
    R hactive D.omegaSupport_subset_selected

/--
Selected exterior-derivative constructor data from selected reconstruction
data, again without asking callers to pass the support containment separately.
-/
def extDerivConstructorOfReconstruction
    (boundary : BoundaryPieceFamilyInput I omega BoundaryChart BoundaryPiece)
    (R :
      PartitionReconstructionData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (hactive :
      selectedPartitionBulkActive D.selectedPartition boundary =
        R.activeCharts) :
    PartitionExtDerivConstructorData I omega (M ⊕ BoundaryChart)
      ExtInteriorPiece ExtBoundaryPiece :=
  PartitionExtDerivConstructorData.ofSelectedPartitionReconstructionData
    (P := D.selectedPartition) (boundary := boundary)
    (ExtInteriorPiece := ExtInteriorPiece)
    (ExtBoundaryPiece := ExtBoundaryPiece)
    R hactive D.omegaSupport_subset_selected

@[simp]
theorem extDerivConstructorOfReconstruction_localizedEventually
    (boundary : BoundaryPieceFamilyInput I omega BoundaryChart BoundaryPiece)
    (R :
      PartitionReconstructionData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (hactive :
      selectedPartitionBulkActive D.selectedPartition boundary =
        R.activeCharts) :
    (D.extDerivConstructorOfReconstruction
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      boundary R hactive).localizedEventually =
      D.bulkSelectedLocalizedEventually boundary := by
  rfl

/--
Selected reconstruction source from reconstruction data and the selected
partition constructor.
-/
def selectedReconstructionSourceOfReconstruction
    (boundary : BoundaryPieceFamilyInput I omega BoundaryChart BoundaryPiece)
    (R :
      PartitionReconstructionData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (hactive :
      selectedPartitionBulkActive D.selectedPartition boundary =
        R.activeCharts) :
    SelectedPartitionReconstructionSource I omega D.selectedPartition boundary
      ExtInteriorPiece ExtBoundaryPiece :=
  SelectedPartitionReconstructionSource.ofGeneratedSelectedPartitionExtDerivConstructor
    (P := D.selectedPartition) (boundary := boundary)
    (ExtInteriorPiece := ExtInteriorPiece)
    (ExtBoundaryPiece := ExtBoundaryPiece)
    R hactive D.omegaSupport_subset_selected

end NaturalCompactSupportPartitionConstructorData

namespace CompactlySupportedSmoothFormData

variable
    (formData : CompactlySupportedSmoothFormData I omega)

/--
Build the finite-active compact-support selection over the canonical support
set carried by `formData`, using explicit compact coordinate supports.
-/
def finiteActiveSelectionOfCoordSupport
    (coordSupport : M -> Set (Fin (n + 1) -> Real))
    (hcompact :
      forall i,
        i ∈ (FiniteActiveOnCompact.ofCompact rho formData.supportSet
          formData.isCompact_supportSet).active ->
          IsCompact (coordSupport i))
    (hsupp :
      forall i,
        i ∈ (FiniteActiveOnCompact.ofCompact rho formData.supportSet
          formData.isCompact_supportSet).active ->
          tsupport (ManifoldForm.transitionPullbackInChart I i i omega) ⊆
            coordSupport i)
    (hcontain :
      ActiveCompactBoxChartContainment
        (FiniteActiveOnCompact.ofCompact rho formData.supportSet
          formData.isCompact_supportSet)
        (FiniteActiveOnCompact.activeChartCompactSupportDataOfCompactSupport
          rho formData.supportSet formData.isCompact_supportSet omega
          coordSupport hcompact hsupp).box) :
    CompactSupportFiniteActiveSelection
      (I := I) rho formData.supportSet formData.isCompact_supportSet omega :=
  CompactSupportFiniteActiveSelection.ofCoordSupport
    rho formData.supportSet formData.isCompact_supportSet omega
    coordSupport hcompact hsupp hcontain

@[simp]
theorem finiteActiveSelectionOfCoordSupport_supportData
    (coordSupport : M -> Set (Fin (n + 1) -> Real))
    (hcompact :
      forall i,
        i ∈ (FiniteActiveOnCompact.ofCompact rho formData.supportSet
          formData.isCompact_supportSet).active ->
          IsCompact (coordSupport i))
    (hsupp :
      forall i,
        i ∈ (FiniteActiveOnCompact.ofCompact rho formData.supportSet
          formData.isCompact_supportSet).active ->
          tsupport (ManifoldForm.transitionPullbackInChart I i i omega) ⊆
            coordSupport i)
    (hcontain :
      ActiveCompactBoxChartContainment
        (FiniteActiveOnCompact.ofCompact rho formData.supportSet
          formData.isCompact_supportSet)
        (FiniteActiveOnCompact.activeChartCompactSupportDataOfCompactSupport
          rho formData.supportSet formData.isCompact_supportSet omega
          coordSupport hcompact hsupp).box) :
    (formData.finiteActiveSelectionOfCoordSupport
      (I := I) (rho := rho) (omega := omega)
      coordSupport hcompact hsupp hcontain).supportData =
      FiniteActiveOnCompact.activeChartCompactSupportDataOfCompactSupport
        rho formData.supportSet formData.isCompact_supportSet omega
        coordSupport hcompact hsupp := by
  rfl

end CompactlySupportedSmoothFormData

namespace NaturalCompactSupportEndpointSelectedReconstructionSourceBaseSources

/--
Build source-packaged endpoint base sources from natural selected-partition
constructor data.

Compared with the raw endpoint record, callers no longer provide
`formData`, `selection`, `smoothness`, or
`omegaSupport_subset_selected` as unrelated fields.
-/
def ofPartitionConstructorData
    (D : NaturalCompactSupportPartitionConstructorData I omega rho)
    (orientedBoundaryAtlas : BoundaryChartOrientedAtlas I M)
    (boundaryUnified :
      BoundarySourceAlignmentUnifiedData
        (I := I) (omega := omega)
        (selectedPartition := D.selectedPartition)
        (orientedBoundaryAtlas := orientedBoundaryAtlas)
        (BoundaryPiece := BoundaryPiece'))
    (localized : LocalizedInteriorM8Fields I omega D.selectedPartition)
    (reconstructionSource :
      SelectedPartitionReconstructionSource I omega D.selectedPartition
        boundaryUnified.toM8TargetImageInput.targetImages
        ExtInteriorPiece ExtBoundaryPiece)
    (extDerivMeasure : M -> M -> Measure (Fin (n + 1) -> Real))
    (bulkLocalFacts :
      SelectedPartitionBulkCanonicalLocalFacts D.selectedPartition
        boundaryUnified.toM8TargetImageInput.targetImages localized)
    (measure_eq_volume : mu = volume)
    (boundaryFaceContinuity :
      ProjectLocalBoundaryCanonicalFaceContinuityData
        boundaryUnified.toProjectLocalGlobalStokesData)
    (boundaryChartChange :
      BoundaryChartChangeSelectedFamilyData
        boundaryUnified.toProjectLocalGlobalStokesData) :
    NaturalCompactSupportEndpointSelectedReconstructionSourceBaseSources
      ExtInteriorPiece ExtBoundaryPiece I omega BoundaryPiece' rho mu where
  formData := D.formData
  selection := D.selection
  smoothness := D.smoothness
  orientedBoundaryAtlas := orientedBoundaryAtlas
  boundaryUnified := boundaryUnified
  localized := localized
  reconstructionSource := reconstructionSource
  extDerivMeasure := extDerivMeasure
  omegaSupport_subset_selected := D.omegaSupport_subset_selected
  bulkLocalFacts := bulkLocalFacts
  measure_eq_volume := measure_eq_volume
  boundaryFaceContinuity := boundaryFaceContinuity
  boundaryChartChange := boundaryChartChange

@[simp]
theorem ofPartitionConstructorData_selectedPartition
    (D : NaturalCompactSupportPartitionConstructorData I omega rho)
    (orientedBoundaryAtlas : BoundaryChartOrientedAtlas I M)
    (boundaryUnified :
      BoundarySourceAlignmentUnifiedData
        (I := I) (omega := omega)
        (selectedPartition := D.selectedPartition)
        (orientedBoundaryAtlas := orientedBoundaryAtlas)
        (BoundaryPiece := BoundaryPiece'))
    (localized : LocalizedInteriorM8Fields I omega D.selectedPartition)
    (reconstructionSource :
      SelectedPartitionReconstructionSource I omega D.selectedPartition
        boundaryUnified.toM8TargetImageInput.targetImages
        ExtInteriorPiece ExtBoundaryPiece)
    (extDerivMeasure : M -> M -> Measure (Fin (n + 1) -> Real))
    (bulkLocalFacts :
      SelectedPartitionBulkCanonicalLocalFacts D.selectedPartition
        boundaryUnified.toM8TargetImageInput.targetImages localized)
    (measure_eq_volume : mu = volume)
    (boundaryFaceContinuity :
      ProjectLocalBoundaryCanonicalFaceContinuityData
        boundaryUnified.toProjectLocalGlobalStokesData)
    (boundaryChartChange :
      BoundaryChartChangeSelectedFamilyData
        boundaryUnified.toProjectLocalGlobalStokesData) :
    (ofPartitionConstructorData
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      (BoundaryPiece' := BoundaryPiece')
      (mu := mu)
      D orientedBoundaryAtlas boundaryUnified localized reconstructionSource
      extDerivMeasure bulkLocalFacts measure_eq_volume boundaryFaceContinuity
      boundaryChartChange).selectedPartition = D.selectedPartition := by
  rfl

end NaturalCompactSupportEndpointSelectedReconstructionSourceBaseSources

namespace NaturalCompactSupportEndpointExtDerivBaseSources

/--
Build ext-deriv endpoint base sources from natural selected-partition
constructor data.  The compact support containment of `omega` is projected
from the constructor data.
-/
def ofPartitionConstructorData
    (D : NaturalCompactSupportPartitionConstructorData I omega rho)
    (orientedBoundaryAtlas : BoundaryChartOrientedAtlas I M)
    (boundaryUnified :
      BoundarySourceAlignmentUnifiedData
        (I := I) (omega := omega)
        (selectedPartition := D.selectedPartition)
        (orientedBoundaryAtlas := orientedBoundaryAtlas)
        (BoundaryPiece := BoundaryPiece'))
    (localized : LocalizedInteriorM8Fields I omega D.selectedPartition)
    (extDerivOnSupport :
      ExtDerivOnSupportData I omega (M ⊕ M)
        ExtInteriorPiece ExtBoundaryPiece)
    (extDerivActive :
      selectedPartitionBulkActive D.selectedPartition
          boundaryUnified.toM8TargetImageInput.targetImages =
        extDerivOnSupport.activeCharts)
    (extDerivMeasure : M -> M -> Measure (Fin (n + 1) -> Real))
    (bulkLocalFacts :
      SelectedPartitionBulkCanonicalLocalFacts D.selectedPartition
        boundaryUnified.toM8TargetImageInput.targetImages localized)
    (measure_eq_volume : mu = volume)
    (boundaryFaceContinuity :
      ProjectLocalBoundaryCanonicalFaceContinuityData
        boundaryUnified.toProjectLocalGlobalStokesData)
    (boundaryChartChange :
      BoundaryChartChangeSelectedFamilyData
        boundaryUnified.toProjectLocalGlobalStokesData) :
    NaturalCompactSupportEndpointExtDerivBaseSources
      ExtInteriorPiece ExtBoundaryPiece I omega BoundaryPiece' rho mu where
  formData := D.formData
  selection := D.selection
  smoothness := D.smoothness
  orientedBoundaryAtlas := orientedBoundaryAtlas
  boundaryUnified := boundaryUnified
  localized := localized
  extDerivOnSupport := extDerivOnSupport
  extDerivActive := extDerivActive
  extDerivMeasure := extDerivMeasure
  omegaSupport_subset_selected := D.omegaSupport_subset_selected
  bulkLocalFacts := bulkLocalFacts
  measure_eq_volume := measure_eq_volume
  boundaryFaceContinuity := boundaryFaceContinuity
  boundaryChartChange := boundaryChartChange

@[simp]
theorem ofPartitionConstructorData_selectedPartition
    (D : NaturalCompactSupportPartitionConstructorData I omega rho)
    (orientedBoundaryAtlas : BoundaryChartOrientedAtlas I M)
    (boundaryUnified :
      BoundarySourceAlignmentUnifiedData
        (I := I) (omega := omega)
        (selectedPartition := D.selectedPartition)
        (orientedBoundaryAtlas := orientedBoundaryAtlas)
        (BoundaryPiece := BoundaryPiece'))
    (localized : LocalizedInteriorM8Fields I omega D.selectedPartition)
    (extDerivOnSupport :
      ExtDerivOnSupportData I omega (M ⊕ M)
        ExtInteriorPiece ExtBoundaryPiece)
    (extDerivActive :
      selectedPartitionBulkActive D.selectedPartition
          boundaryUnified.toM8TargetImageInput.targetImages =
        extDerivOnSupport.activeCharts)
    (extDerivMeasure : M -> M -> Measure (Fin (n + 1) -> Real))
    (bulkLocalFacts :
      SelectedPartitionBulkCanonicalLocalFacts D.selectedPartition
        boundaryUnified.toM8TargetImageInput.targetImages localized)
    (measure_eq_volume : mu = volume)
    (boundaryFaceContinuity :
      ProjectLocalBoundaryCanonicalFaceContinuityData
        boundaryUnified.toProjectLocalGlobalStokesData)
    (boundaryChartChange :
      BoundaryChartChangeSelectedFamilyData
        boundaryUnified.toProjectLocalGlobalStokesData) :
    (ofPartitionConstructorData
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      (BoundaryPiece' := BoundaryPiece')
      (mu := mu)
      D orientedBoundaryAtlas boundaryUnified localized extDerivOnSupport
      extDerivActive extDerivMeasure bulkLocalFacts measure_eq_volume
      boundaryFaceContinuity boundaryChartChange).selectedPartition =
        D.selectedPartition := by
  rfl

end NaturalCompactSupportEndpointExtDerivBaseSources

end NaturalCompactSupportPartitionConstructorAuto

end Stokes

end
