import Stokes.Global.NaturalCompactSupportOnePackageStokesAuto
import Stokes.Global.NaturalBulkFromExtDerivRouteAuto

/-!
# Remaining input scoreboard for the natural compact-support route

This module is an audit layer.  It does not prove new analysis, orientation,
or change-of-variables facts.  Instead it names the current theorem-facing
packages that still have to be constructed before the compact-support
one-package theorem becomes a natural smooth-manifold Stokes theorem.

The important point is that every listed gap is typed by an existing structure,
abbreviation, or theorem-facing statement from the current development.
-/

noncomputable section

set_option linter.style.longLine false
set_option linter.unusedSectionVars false

open Set MeasureTheory
open scoped BigOperators Manifold Topology

namespace Stokes

section RemainingInputScoreboard

universe u w b ei eb

variable {H : Type u} [TopologicalSpace H]
variable {M : Type w} [TopologicalSpace M] [ChartedSpace H M]
variable {BoundaryPiece : Type b}
variable {ExtInteriorPiece : Type ei} {ExtBoundaryPiece : Type eb}
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) -> Real) H}
variable {omega : ManifoldForm I M n}
variable {rho : SmoothPartitionOfUnity M I M univ}
variable {mu : Measure (Fin (n + 1) -> Real)}
variable [IsFiniteMeasureOnCompacts mu]
variable [IsManifold I 1 M]

/--
The chart-box selection gap.

Instantiating this record means the compactly supported form has been turned
into the current natural finite-active chart-box package, including compact
source images, support containment, chart containment, and smoothness
neighborhoods.
-/
structure RemainingChartBoxSelectionPackage
    (I : ModelWithCorners Real (Fin (n + 1) -> Real) H)
    (omega : ManifoldForm I M n)
    (rho : SmoothPartitionOfUnity M I M univ) where
  /-- Compactly supported smooth form data. -/
  formData : CompactlySupportedSmoothFormData I omega
  /-- Natural finite-active chart-box data generated from compact support. -/
  compactSource :
    CompactlySupportedSmoothFormData.NaturalFiniteActiveFromCompactSupportData
      (rho := rho) formData

namespace RemainingChartBoxSelectionPackage

variable
    (C : RemainingChartBoxSelectionPackage I omega rho)

/-- The natural finite-active chart boxes generated by the chart-box package. -/
abbrev chartBoxes : NaturalFiniteActiveChartBoxSelectionData I omega rho :=
  C.compactSource.toNaturalFiniteActiveChartBoxSelectionData

/-- The selected partition generated by the chart-box package. -/
abbrev selectedPartition : SelectedBoxPartitionOfUnity I omega :=
  C.chartBoxes.selectedPartition

end RemainingChartBoxSelectionPackage

/--
The bulk and boundary route gap after the chart boxes have been selected.

The common endpoint package records the oriented boundary atlas, unified
boundary source data, localized interior fields, face-continuity facts, and
chart-change data.  The bulk route records the synchronized exterior-derivative
constructor, local bulk facts, selected reconstruction source, and chartwise
measure.
-/
structure RemainingBulkBoundaryRoutePackage
    (C : RemainingChartBoxSelectionPackage I omega rho)
    (ExtInteriorPiece : Type ei)
    (ExtBoundaryPiece : Type eb)
    (BoundaryPiece : Type b)
    (mu : Measure (Fin (n + 1) -> Real))
    [IsFiniteMeasureOnCompacts mu]
    [IsManifold I 1 M] where
  /-- The non-bulk endpoint data over the selected chart boxes. -/
  endpointCommon :
    NaturalBulkEndpointCommonData
      (I := I) (omega := omega) (rho := rho)
      C.chartBoxes BoundaryPiece mu
  /-- Synchronized bulk route from an exterior-derivative constructor. -/
  bulkRoute :
    endpointCommon.ExtDerivConstructorRoute
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)

namespace RemainingBulkBoundaryRoutePackage

variable {C : RemainingChartBoxSelectionPackage I omega rho}
variable
    (B :
      RemainingBulkBoundaryRoutePackage
        C ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu)

/-- Boundary and measure endpoint input generated by the bulk/boundary route. -/
def boundaryMeasure :
    NaturalCompactSupportEndpointNaturalBoundaryMeasureInput
      (I := I) (omega := omega) (rho := rho)
      C.chartBoxes ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu :=
  B.endpointCommon.toBoundaryMeasureInputOfExtDerivConstructorRoute
    (ExtInteriorPiece := ExtInteriorPiece)
    (ExtBoundaryPiece := ExtBoundaryPiece)
    B.bulkRoute

@[simp]
theorem boundaryMeasure_reconstructionSource :
    B.boundaryMeasure.reconstructionSource =
      B.bulkRoute.selectedReconstructionSource := by
  rfl

@[simp]
theorem boundaryMeasure_bulkLocalFacts :
    B.boundaryMeasure.bulkLocalFacts =
      B.bulkRoute.localFacts := by
  rfl

end RemainingBulkBoundaryRoutePackage

/--
The endpoint geometry gap after the boundary and measure route exists.

These are the two theorem-facing geometric inputs still consumed by the
one-package compact-support endpoint: localized chart alignment and chart-box
containment strong enough to generate selected strict margins.
-/
structure RemainingEndpointGeometryPackage
    {C : RemainingChartBoxSelectionPackage I omega rho}
    (B :
      RemainingBulkBoundaryRoutePackage
        C ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu) where
  /-- The localized interior pieces use the selected source/target chart labels. -/
  chartAlignment :
    LocalizedInteriorM8ChartAlignment B.boundaryMeasure.toSelectedReconstructionEndpointSource.localized
  /-- Chart-box containment used to generate endpoint selected strict margins. -/
  strictContainment :
    B.boundaryMeasure.StrictAlignmentChartBoxContainmentData

/--
The current compact-support one-package construction gap.

An inhabitant of this record is precisely enough data to build
`NaturalCompactSupportOnePackageChartBoxStokesInput`, hence enough data for the
current represented compact-support Stokes theorem.
-/
structure RemainingOnePackageConstructionScoreboard
    (I : ModelWithCorners Real (Fin (n + 1) -> Real) H)
    (omega : ManifoldForm I M n)
    (rho : SmoothPartitionOfUnity M I M univ)
    (ExtInteriorPiece : Type ei)
    (ExtBoundaryPiece : Type eb)
    (BoundaryPiece : Type b)
    (mu : Measure (Fin (n + 1) -> Real))
    [IsFiniteMeasureOnCompacts mu]
    [IsManifold I 1 M] where
  /-- Compact support to natural chart boxes. -/
  chartBoxSelection : RemainingChartBoxSelectionPackage I omega rho
  /-- Synchronized bulk, boundary source, and boundary measure route. -/
  bulkBoundary :
    RemainingBulkBoundaryRoutePackage
      chartBoxSelection ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu
  /-- Endpoint chart alignment and strict containment. -/
  endpointGeometry : RemainingEndpointGeometryPackage bulkBoundary

namespace RemainingOnePackageConstructionScoreboard

variable
    (S :
      RemainingOnePackageConstructionScoreboard
        I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu)

/-- The boundary/measure endpoint input produced by the scoreboard. -/
abbrev boundaryMeasure :
    NaturalCompactSupportEndpointNaturalBoundaryMeasureInput
      (I := I) (omega := omega) (rho := rho)
      S.chartBoxSelection.chartBoxes ExtInteriorPiece ExtBoundaryPiece
      BoundaryPiece mu :=
  S.bulkBoundary.boundaryMeasure

/-- The exact theorem-facing one-package input obtained from the scoreboard. -/
def toOnePackageChartBoxInput :
    NaturalCompactSupportOnePackageChartBoxStokesInput
      I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu where
  formData := S.chartBoxSelection.formData
  compactSource := S.chartBoxSelection.compactSource
  boundaryMeasure := S.boundaryMeasure
  chartAlignment := S.endpointGeometry.chartAlignment
  containment := S.endpointGeometry.strictContainment

@[simp]
theorem toOnePackageChartBoxInput_chartBoxes :
    S.toOnePackageChartBoxInput.chartBoxes =
      S.chartBoxSelection.chartBoxes := by
  rfl

@[simp]
theorem toOnePackageChartBoxInput_boundaryMeasure :
    S.toOnePackageChartBoxInput.toSelectedMarginInput.boundaryMeasure =
      S.boundaryMeasure := by
  rfl

/-- The current represented compact-support Stokes statement exposed by the scoreboard. -/
abbrev representedStokesStatement : Prop :=
  S.toOnePackageChartBoxInput.canonicalIntegralInterface.stokesStatement

/--
The current theorem available once all scoreboard inputs have been constructed.

This is not the final mathlib-native manifold integral statement; it is the
represented statement carried by `CanonicalIntegralInterface`.
-/
theorem represented_stokes :
    S.representedStokesStatement :=
  S.toOnePackageChartBoxInput.canonical_stokes

/-- The same result in the current canonical equality fields. -/
theorem represented_manifoldExtDerivIntegral_eq_boundaryFormIntegral :
    S.toOnePackageChartBoxInput.canonicalIntegralInterface.manifoldExtDerivIntegral =
      S.toOnePackageChartBoxInput.canonicalIntegralInterface.boundaryFormIntegral :=
  S.toOnePackageChartBoxInput.manifoldExtDerivIntegral_eq_boundaryFormIntegral

end RemainingOnePackageConstructionScoreboard

/--
The final exit marker from the present one-package theorem to a future general
smooth-manifold theorem.

The codebase currently exposes the conclusion through
`CanonicalIntegralInterface`.  Therefore the remaining "general theorem" work
starts with a proved represented statement and then has to replace the
represented real values by the eventual mathlib-native integration definitions.
-/
structure RemainingGeneralSmoothManifoldExitScoreboard
    (D :
      NaturalCompactSupportOnePackageChartBoxStokesInput
        I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu) where
  /-- The exact current represented theorem statement. -/
  representedStatement : D.canonicalIntegralInterface.stokesStatement
  /-- The current represented canonical integral interface. -/
  representedInterface : CanonicalIntegralInterface I omega
  /-- The represented interface is the one attached to the one-package input. -/
  representedInterface_eq :
    representedInterface = D.canonicalIntegralInterface

namespace RemainingGeneralSmoothManifoldExitScoreboard

variable
    (D :
      NaturalCompactSupportOnePackageChartBoxStokesInput
        I omega rho ExtInteriorPiece ExtBoundaryPiece BoundaryPiece mu)

/-- Automatic exit scoreboard from the current one-package theorem. -/
def ofOnePackageInput :
    RemainingGeneralSmoothManifoldExitScoreboard D where
  representedStatement := D.canonical_stokes
  representedInterface := D.canonicalIntegralInterface
  representedInterface_eq := rfl

@[simp]
theorem ofOnePackageInput_representedInterface :
    (ofOnePackageInput D).representedInterface =
      D.canonicalIntegralInterface := by
  rfl

end RemainingGeneralSmoothManifoldExitScoreboard

end RemainingInputScoreboard

end Stokes

end
