import Stokes.Global.SelectedReconstructionSourceAuto

/-!
# Upstream constructors for selected reconstruction sources

`SelectedPartitionReconstructionSource` packages the active-set compatibility
needed by compact-support endpoint constructors.  This file adds constructor
routes from the earlier exterior-derivative packages that already carry the
same reconstruction data.

The main new endpoint-facing route starts from
`NaturalCompactSupportEndpointExtDerivBaseSources`: its
`ExtDerivOnSupportData` field already contains the reconstruction package, and
its `extDerivActive` field is exactly the selected active-set compatibility.
-/

noncomputable section

set_option linter.unusedSectionVars false

open Set MeasureTheory
open scoped BigOperators Manifold Topology

namespace Stokes

section SelectedReconstructionSourceConstructorsAuto

universe u w cb pb ei eb b

variable {H : Type u} [TopologicalSpace H]
variable {M : Type w} [TopologicalSpace M] [ChartedSpace H M]
variable {BoundaryChart : Type cb} {BoundaryPiece : Type pb}
variable {ExtInteriorPiece : Type ei} {ExtBoundaryPiece : Type eb}
variable {n : Nat}
variable {I : ModelWithCorners Real (Fin (n + 1) -> Real) H}
variable {omega : ManifoldForm I M n}
variable {P : SelectedBoxPartitionOfUnity I omega}
variable {boundary : BoundaryPieceFamilyInput I omega BoundaryChart BoundaryPiece}
variable {localized : LocalizedInteriorM8Fields I omega P}

namespace SelectedPartitionReconstructionSource

/--
Selected reconstruction source from support-local exterior-derivative data.

The support-local package already forgets to a `PartitionReconstructionData`;
the only real input is that its active labels are the selected bulk labels.
-/
def ofExtDerivOnSupportDataSelectedPartition
    (D :
      ExtDerivOnSupportData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (hactive : selectedPartitionBulkActive P boundary = D.activeCharts) :
    SelectedPartitionReconstructionSource I omega P boundary
      ExtInteriorPiece ExtBoundaryPiece where
  reconstruction := D.toPartitionReconstructionData
  active_eq := by
    simpa [ExtDerivOnSupportData.toPartitionReconstructionData] using hactive

@[simp]
theorem ofExtDerivOnSupportDataSelectedPartition_reconstruction
    (D :
      ExtDerivOnSupportData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (hactive : selectedPartitionBulkActive P boundary = D.activeCharts) :
    (ofExtDerivOnSupportDataSelectedPartition
      (P := P) (boundary := boundary)
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      D hactive).reconstruction =
      D.toPartitionReconstructionData := by
  rfl

/--
Selected reconstruction source from the canonical selected-partition
exterior-derivative constructor.

Compared with `ofSelectedPartitionExtDerivConstructorData`, callers no longer
provide the `localizedEventually = bulkSelectedLocalizedEventually` proof: for
this canonical constructor it is definitional.
-/
def ofGeneratedSelectedPartitionExtDerivConstructor
    (R :
      PartitionReconstructionData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (hactive : selectedPartitionBulkActive P boundary = R.activeCharts)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K) :
    SelectedPartitionReconstructionSource I omega P boundary
      ExtInteriorPiece ExtBoundaryPiece :=
  ofSelectedPartitionExtDerivConstructorData
    (P := P) (boundary := boundary)
    (ExtInteriorPiece := ExtInteriorPiece)
    (ExtBoundaryPiece := ExtBoundaryPiece)
    (PartitionExtDerivConstructorData.ofSelectedPartitionReconstructionData
      (P := P) (boundary := boundary)
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      R hactive homegaSupport)
    homegaSupport rfl

@[simp]
theorem ofGeneratedSelectedPartitionExtDerivConstructor_reconstruction
    (R :
      PartitionReconstructionData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (hactive : selectedPartitionBulkActive P boundary = R.activeCharts)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K) :
    (ofGeneratedSelectedPartitionExtDerivConstructor
      (P := P) (boundary := boundary)
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      R hactive homegaSupport).reconstruction = R := by
  rfl

/--
Selected reconstruction source from the project-local automatic bulk input
generated by a selected exterior-derivative constructor.

This is the constructor-side analogue of
`ofBulkIntegrandAEProjectLocalAutoInput`: the bulk input is assembled from the
selected constructor first, so active/coefficient alignment is projected from
the constructor's `localizedEventually` source.
-/
def ofSelectedPartitionExtDerivConstructorBulkAutoInput
    (D :
      PartitionExtDerivConstructorData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K)
    (hselected :
      D.localizedEventually =
        P.bulkSelectedLocalizedEventually
          (BoundaryChart := BoundaryChart) boundary homegaSupport)
    (measure : M -> M -> Measure (Fin (n + 1) -> Real)) :
    SelectedPartitionReconstructionSource I omega P boundary
      ExtInteriorPiece ExtBoundaryPiece :=
  ofBulkIntegrandAEProjectLocalAutoInput
    (P := P) (boundary := boundary) (localized := localized)
    (ExtInteriorPiece := ExtInteriorPiece)
    (ExtBoundaryPiece := ExtBoundaryPiece)
    (BulkIntegrandAEProjectLocalAutoInput.ofSelectedPartitionExtDerivConstructorData
      (P := P) (boundary := boundary) (localized := localized)
      D homegaSupport hselected measure)

@[simp]
theorem ofSelectedPartitionExtDerivConstructorBulkAutoInput_reconstruction
    (D :
      PartitionExtDerivConstructorData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K)
    (hselected :
      D.localizedEventually =
        P.bulkSelectedLocalizedEventually
          (BoundaryChart := BoundaryChart) boundary homegaSupport)
    (measure : M -> M -> Measure (Fin (n + 1) -> Real)) :
    (ofSelectedPartitionExtDerivConstructorBulkAutoInput
      (P := P) (boundary := boundary) (localized := localized)
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      D homegaSupport hselected measure).reconstruction =
      D.toPartitionReconstructionData := by
  rfl

/--
Selected reconstruction source from the project-local automatic bulk input
generated by canonical selected reconstruction data.

This removes the need for callers to name the intermediate bulk a.e. input
when their source is the canonical selected reconstruction constructor.
-/
def ofSelectedPartitionReconstructionBulkAutoInput
    (R :
      PartitionReconstructionData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (hactive : selectedPartitionBulkActive P boundary = R.activeCharts)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K)
    (measure : M -> M -> Measure (Fin (n + 1) -> Real)) :
    SelectedPartitionReconstructionSource I omega P boundary
      ExtInteriorPiece ExtBoundaryPiece :=
  ofBulkIntegrandAEProjectLocalAutoInput
    (P := P) (boundary := boundary) (localized := localized)
    (ExtInteriorPiece := ExtInteriorPiece)
    (ExtBoundaryPiece := ExtBoundaryPiece)
    (BulkIntegrandAEProjectLocalAutoInput.ofSelectedPartitionReconstructionData
      (P := P) (boundary := boundary) (localized := localized)
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      R hactive homegaSupport measure)

@[simp]
theorem ofSelectedPartitionReconstructionBulkAutoInput_reconstruction
    (R :
      PartitionReconstructionData I omega (M ⊕ BoundaryChart)
        ExtInteriorPiece ExtBoundaryPiece)
    (hactive : selectedPartitionBulkActive P boundary = R.activeCharts)
    (homegaSupport : ManifoldForm.support I omega ⊆ P.K)
    (measure : M -> M -> Measure (Fin (n + 1) -> Real)) :
    (ofSelectedPartitionReconstructionBulkAutoInput
      (P := P) (boundary := boundary) (localized := localized)
      (ExtInteriorPiece := ExtInteriorPiece)
      (ExtBoundaryPiece := ExtBoundaryPiece)
      R hactive homegaSupport measure).reconstruction = R := by
  rfl

end SelectedPartitionReconstructionSource

section EndpointConstructors

variable {BoundaryPiece' : Type b}
variable {rho : SmoothPartitionOfUnity M I M univ}
variable {mu : Measure (Fin (n + 1) -> Real)}
variable [IsFiniteMeasureOnCompacts mu]
variable [IsManifold I 1 M]

namespace NaturalCompactSupportEndpointExtDerivBaseSources

variable
    (S :
      NaturalCompactSupportEndpointExtDerivBaseSources
        ExtInteriorPiece ExtBoundaryPiece I omega BoundaryPiece' rho mu)

/--
The selected reconstruction source already present in an ext-deriv endpoint
base source.

This is the endpoint-level constructor that turns the older
`extDerivOnSupport + extDerivActive` route into the newer source-packaged route.
-/
def selectedReconstructionSource :
    SelectedPartitionReconstructionSource I omega
      S.selectedPartition
      S.boundaryUnified.toM8TargetImageInput.targetImages
      ExtInteriorPiece ExtBoundaryPiece :=
  SelectedPartitionReconstructionSource.ofExtDerivOnSupportDataSelectedPartition
    (P := S.selectedPartition)
    (boundary := S.boundaryUnified.toM8TargetImageInput.targetImages)
    (ExtInteriorPiece := ExtInteriorPiece)
    (ExtBoundaryPiece := ExtBoundaryPiece)
    S.extDerivOnSupport S.extDerivActive

@[simp]
theorem selectedReconstructionSource_reconstruction :
    S.selectedReconstructionSource.reconstruction =
      S.extDerivOnSupport.toPartitionReconstructionData := by
  rfl

/--
Convert the older ext-deriv endpoint base source into the source-packaged
selected reconstruction endpoint base.
-/
def toSelectedReconstructionSourceBaseSources :
    NaturalCompactSupportEndpointSelectedReconstructionSourceBaseSources
      ExtInteriorPiece ExtBoundaryPiece I omega BoundaryPiece' rho mu where
  formData := S.formData
  selection := S.selection
  smoothness := S.smoothness
  orientedBoundaryAtlas := S.orientedBoundaryAtlas
  boundaryUnified := S.boundaryUnified
  localized := S.localized
  reconstructionSource := S.selectedReconstructionSource
  extDerivMeasure := S.extDerivMeasure
  omegaSupport_subset_selected := S.omegaSupport_subset_selected
  bulkLocalFacts := S.bulkLocalFacts
  measure_eq_volume := S.measure_eq_volume
  boundaryFaceContinuity := S.boundaryFaceContinuity
  boundaryChartChange := S.boundaryChartChange

@[simp]
theorem toSelectedReconstructionSourceBaseSources_reconstruction :
    S.toSelectedReconstructionSourceBaseSources.reconstruction =
      S.extDerivOnSupport.toPartitionReconstructionData := by
  rfl

@[simp]
theorem toSelectedReconstructionSourceBaseSources_extDerivMeasure :
    S.toSelectedReconstructionSourceBaseSources.extDerivMeasure =
      S.extDerivMeasure := by
  rfl

/--
Endpoint theorem routed through the source-packaged selected reconstruction
base produced from the ext-deriv source.
-/
theorem stokes_ofCompactSelectionFromExtDerivSource
    (compactSelection :
      EndpointCompactSelectionArtificialAlignment
        S.toSelectedReconstructionSourceBaseSources.autoSelectedBaseSources) :
    (S.toSelectedReconstructionSourceBaseSources.toSelectedCompactSources
      compactSelection).measureLocalization.bulkMeasureIntegral =
      (S.toSelectedReconstructionSourceBaseSources.toSelectedCompactSources
        compactSelection).measureLocalization.boundaryMeasureIntegral :=
  (S.toSelectedReconstructionSourceBaseSources.toSelectedCompactSources
    compactSelection).stokes

end NaturalCompactSupportEndpointExtDerivBaseSources

end EndpointConstructors

end SelectedReconstructionSourceConstructorsAuto

end Stokes

end
